// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package tail provides the data types delivered to a Worker's
// tail(events, env, ctx) handler, i.e. a Tail Worker consuming another
// Worker's execution traces via that Worker's `tail_consumers` config
// (https://developers.cloudflare.com/workers/observability/logs/tail-workers/).
// TraceItem and its nested types are generated here; tail.go's hand-written
// Handle registers the Worker's own tail(events, env, ctx) export (added to
// cmd/workers-assets-gen/assets/common/worker.mjs) the same way
// cloudflare/queues.Consume registers queue and exp/cloudflare/email.Handle
// registers email.
//
// TraceItem.event is a 10-way union (TraceItemFetchEventInfo |
// TraceItemJsRpcEventInfo | TraceItemConnectEventInfo |
// TraceItemScheduledEventInfo | TraceItemAlarmEventInfo |
// TraceItemQueueEventInfo | TraceItemEmailEventInfo |
// TraceItemTailEventInfo | TraceItemCustomEventInfo |
// TraceItemHibernatableWebSocketEventInfo | null). Left unconfigured, cfgen's
// union-of-data-shapes rule would merge all ten into one lossy synthesized
// struct instead of preserving the discriminated-union shape, so it's
// overridden to js.Value here; tail.go adds a hand-written EventKind()
// (inferred from which of the branches' distinguishing properties are
// present — TraceItemConnectEventInfo and TraceItemCustomEventInfo carry no
// properties of their own, so they can't be told apart this way and both
// fall back to EventKind() == "") plus typed accessors (FetchEvent(),
// ScheduledEvent(), ...) for every branch that can be identified.
//
// TraceItem.eventTimestamp is `number | null` (a Unix ms timestamp). cfgen's
// "types:" overrides support a "*int" pointer spelling but not "*float64"
// (see scripts/gen-bindings/cfgen/gen/types.go's namedTypeConv), and
// TraceItem is a plain data struct with no retained js.Value to fall back to
// post-decode, so the null/absent case can't be distinguished from a literal
// 0. It's generated as plain float64 (types: override below, matching what
// cfgen would already infer by default — spelled out to document the
// choice); tail.go's EventTime() treats an EventTimestamp of exactly 0 as
// absent, which is the best available approximation given the above.
//
// TraceLogErrorInfo (referenced by TraceLog.errorInfo) is included even
// though it isn't itself part of the TraceItem event-info family, since it's
// a plain data type with no reason to fall back to js.Value.
package tail

import (
	"syscall/js"
	"time"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// TraceItem
type TraceItem struct {
	Event                    js.Value                      `js:"event"`
	EventTimestamp           float64                       `js:"eventTimestamp"`
	Logs                     []TraceLog                    `js:"logs"`
	Exceptions               []TraceException              `js:"exceptions"`
	DiagnosticsChannelEvents []TraceDiagnosticChannelEvent `js:"diagnosticsChannelEvents"`
	ScriptName               string                        `js:"scriptName"`
	Entrypoint               string                        `js:"entrypoint"`
	ScriptVersion            *ScriptVersion                `js:"scriptVersion"`
	DispatchNamespace        string                        `js:"dispatchNamespace"`
	ScriptTags               []string                      `js:"scriptTags"`
	TailAttributes           map[string]js.Value           `js:"tailAttributes"`
	Preview                  *TracePreviewInfo             `js:"preview"`
	DurableObjectID          string                        `js:"durableObjectId"`
	Outcome                  string                        `js:"outcome"`
	ExecutionModel           string                        `js:"executionModel"`
	Truncated                bool                          `js:"truncated"`
	CpuTime                  float64                       `js:"cpuTime"`
	WallTime                 float64                       `js:"wallTime"`
}

func traceItemFromJS(v js.Value) (TraceItem, error) {
	var out TraceItem
	{
		if s := v.Get("event"); !s.IsUndefined() && !s.IsNull() {
			out.Event = s
		}
	}
	{
		if s := v.Get("eventTimestamp"); !s.IsUndefined() && !s.IsNull() {
			out.EventTimestamp = s.Float()
		}
	}
	{
		out.Logs = make([]TraceLog, v.Get("logs").Length())
		for i := range out.Logs {
			if tmp, err := traceLogFromJS(v.Get("logs").Index(i)); err != nil {
				return TraceItem{}, err
			} else {
				out.Logs[i] = tmp
			}
		}
	}
	{
		out.Exceptions = make([]TraceException, v.Get("exceptions").Length())
		for i := range out.Exceptions {
			if tmp, err := traceExceptionFromJS(v.Get("exceptions").Index(i)); err != nil {
				return TraceItem{}, err
			} else {
				out.Exceptions[i] = tmp
			}
		}
	}
	{
		out.DiagnosticsChannelEvents = make([]TraceDiagnosticChannelEvent, v.Get("diagnosticsChannelEvents").Length())
		for i := range out.DiagnosticsChannelEvents {
			if tmp, err := traceDiagnosticChannelEventFromJS(v.Get("diagnosticsChannelEvents").Index(i)); err != nil {
				return TraceItem{}, err
			} else {
				out.DiagnosticsChannelEvents[i] = tmp
			}
		}
	}
	{
		if s := v.Get("scriptName"); !s.IsUndefined() && !s.IsNull() {
			out.ScriptName = s.String()
		}
	}
	{
		if s := v.Get("entrypoint"); !s.IsUndefined() && !s.IsNull() {
			out.Entrypoint = s.String()
		}
	}
	{
		if !jsrt.IsNil(v.Get("scriptVersion")) {
			var val ScriptVersion
			if tmp, err := scriptVersionFromJS(v.Get("scriptVersion")); err != nil {
				return TraceItem{}, err
			} else {
				val = tmp
			}
			out.ScriptVersion = &val
		}
	}
	{
		if s := v.Get("dispatchNamespace"); !s.IsUndefined() && !s.IsNull() {
			out.DispatchNamespace = s.String()
		}
	}
	{
		if s := v.Get("scriptTags"); !s.IsUndefined() && !s.IsNull() {
			out.ScriptTags = make([]string, s.Length())
			for i := range out.ScriptTags {
				out.ScriptTags[i] = s.Index(i).String()
			}
		}
	}
	{
		if s := v.Get("tailAttributes"); !s.IsUndefined() && !s.IsNull() {
			out.TailAttributes = make(map[string]js.Value)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				var vv js.Value
				vv = s.Get(k)
				out.TailAttributes[k] = vv
			}
		}
	}
	{
		if !jsrt.IsNil(v.Get("preview")) {
			var val TracePreviewInfo
			if tmp, err := tracePreviewInfoFromJS(v.Get("preview")); err != nil {
				return TraceItem{}, err
			} else {
				val = tmp
			}
			out.Preview = &val
		}
	}
	{
		if s := v.Get("durableObjectId"); !s.IsUndefined() && !s.IsNull() {
			out.DurableObjectID = s.String()
		}
	}
	{
		out.Outcome = v.Get("outcome").String()
	}
	{
		out.ExecutionModel = v.Get("executionModel").String()
	}
	{
		out.Truncated = v.Get("truncated").Bool()
	}
	{
		out.CpuTime = v.Get("cpuTime").Float()
	}
	{
		out.WallTime = v.Get("wallTime").Float()
	}
	return out, nil
}

func (o TraceItem) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.Event) {
		obj.Set("event", o.Event)
	}
	if o.EventTimestamp != 0 {
		obj.Set("eventTimestamp", o.EventTimestamp)
	}
	if len(o.Logs) > 0 {
		arr := js.Global().Get("Array").New(len(o.Logs))
		for i, e := range o.Logs {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("logs", arr)
	}
	if len(o.Exceptions) > 0 {
		arr := js.Global().Get("Array").New(len(o.Exceptions))
		for i, e := range o.Exceptions {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("exceptions", arr)
	}
	if len(o.DiagnosticsChannelEvents) > 0 {
		arr := js.Global().Get("Array").New(len(o.DiagnosticsChannelEvents))
		for i, e := range o.DiagnosticsChannelEvents {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("diagnosticsChannelEvents", arr)
	}
	if o.ScriptName != "" {
		obj.Set("scriptName", o.ScriptName)
	}
	if o.Entrypoint != "" {
		obj.Set("entrypoint", o.Entrypoint)
	}
	if o.ScriptVersion != nil {
		obj.Set("scriptVersion", (*o.ScriptVersion).toJS())
	}
	if o.DispatchNamespace != "" {
		obj.Set("dispatchNamespace", o.DispatchNamespace)
	}
	if len(o.ScriptTags) > 0 {
		arr := js.Global().Get("Array").New(len(o.ScriptTags))
		for i, e := range o.ScriptTags {
			arr.SetIndex(i, e)
		}
		obj.Set("scriptTags", arr)
	}
	if len(o.TailAttributes) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.TailAttributes {
			m.Set(k, v)
		}
		obj.Set("tailAttributes", m)
	}
	if o.Preview != nil {
		obj.Set("preview", (*o.Preview).toJS())
	}
	if o.DurableObjectID != "" {
		obj.Set("durableObjectId", o.DurableObjectID)
	}
	if o.Outcome != "" {
		obj.Set("outcome", o.Outcome)
	}
	if o.ExecutionModel != "" {
		obj.Set("executionModel", o.ExecutionModel)
	}
	if o.Truncated {
		obj.Set("truncated", o.Truncated)
	}
	if o.CpuTime != 0 {
		obj.Set("cpuTime", o.CpuTime)
	}
	if o.WallTime != 0 {
		obj.Set("wallTime", o.WallTime)
	}
	return obj
}

// TraceLog
type TraceLog struct {
	Timestamp float64             `js:"timestamp"`
	Level     string              `js:"level"`
	Message   js.Value            `js:"message"`
	ErrorInfo []TraceLogErrorInfo `js:"errorInfo"`
}

func traceLogFromJS(v js.Value) (TraceLog, error) {
	var out TraceLog
	{
		out.Timestamp = v.Get("timestamp").Float()
	}
	{
		out.Level = v.Get("level").String()
	}
	{
		out.Message = v.Get("message")
	}
	{
		if s := v.Get("errorInfo"); !s.IsUndefined() && !s.IsNull() {
			out.ErrorInfo = make([]TraceLogErrorInfo, s.Length())
			for i := range out.ErrorInfo {
				if tmp, err := traceLogErrorInfoFromJS(s.Index(i)); err != nil {
					return TraceLog{}, err
				} else {
					out.ErrorInfo[i] = tmp
				}
			}
		}
	}
	return out, nil
}

func (o TraceLog) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Timestamp != 0 {
		obj.Set("timestamp", o.Timestamp)
	}
	if o.Level != "" {
		obj.Set("level", o.Level)
	}
	if !jsrt.IsNil(o.Message) {
		obj.Set("message", o.Message)
	}
	if len(o.ErrorInfo) > 0 {
		arr := js.Global().Get("Array").New(len(o.ErrorInfo))
		for i, e := range o.ErrorInfo {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("errorInfo", arr)
	}
	return obj
}

// TraceLogErrorInfo
type TraceLogErrorInfo struct {
	Name    string `js:"name"`
	Message string `js:"message"`
	Stack   string `js:"stack"`
}

func traceLogErrorInfoFromJS(v js.Value) (TraceLogErrorInfo, error) {
	var out TraceLogErrorInfo
	{
		out.Name = v.Get("name").String()
	}
	{
		out.Message = v.Get("message").String()
	}
	{
		if s := v.Get("stack"); !s.IsUndefined() && !s.IsNull() {
			out.Stack = s.String()
		}
	}
	return out, nil
}

func (o TraceLogErrorInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Message != "" {
		obj.Set("message", o.Message)
	}
	if o.Stack != "" {
		obj.Set("stack", o.Stack)
	}
	return obj
}

// TraceException
type TraceException struct {
	Timestamp float64 `js:"timestamp"`
	Message   string  `js:"message"`
	Name      string  `js:"name"`
	Stack     string  `js:"stack"`
}

func traceExceptionFromJS(v js.Value) (TraceException, error) {
	var out TraceException
	{
		out.Timestamp = v.Get("timestamp").Float()
	}
	{
		out.Message = v.Get("message").String()
	}
	{
		out.Name = v.Get("name").String()
	}
	{
		if s := v.Get("stack"); !s.IsUndefined() && !s.IsNull() {
			out.Stack = s.String()
		}
	}
	return out, nil
}

func (o TraceException) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Timestamp != 0 {
		obj.Set("timestamp", o.Timestamp)
	}
	if o.Message != "" {
		obj.Set("message", o.Message)
	}
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Stack != "" {
		obj.Set("stack", o.Stack)
	}
	return obj
}

// TraceDiagnosticChannelEvent
type TraceDiagnosticChannelEvent struct {
	Timestamp float64  `js:"timestamp"`
	Channel   string   `js:"channel"`
	Message   js.Value `js:"message"`
}

func traceDiagnosticChannelEventFromJS(v js.Value) (TraceDiagnosticChannelEvent, error) {
	var out TraceDiagnosticChannelEvent
	{
		out.Timestamp = v.Get("timestamp").Float()
	}
	{
		out.Channel = v.Get("channel").String()
	}
	{
		out.Message = v.Get("message")
	}
	return out, nil
}

func (o TraceDiagnosticChannelEvent) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Timestamp != 0 {
		obj.Set("timestamp", o.Timestamp)
	}
	if o.Channel != "" {
		obj.Set("channel", o.Channel)
	}
	if !jsrt.IsNil(o.Message) {
		obj.Set("message", o.Message)
	}
	return obj
}

// ScriptVersion
type ScriptVersion struct {
	ID      string `js:"id"`
	Tag     string `js:"tag"`
	Message string `js:"message"`
}

func scriptVersionFromJS(v js.Value) (ScriptVersion, error) {
	var out ScriptVersion
	{
		if s := v.Get("id"); !s.IsUndefined() && !s.IsNull() {
			out.ID = s.String()
		}
	}
	{
		if s := v.Get("tag"); !s.IsUndefined() && !s.IsNull() {
			out.Tag = s.String()
		}
	}
	{
		if s := v.Get("message"); !s.IsUndefined() && !s.IsNull() {
			out.Message = s.String()
		}
	}
	return out, nil
}

func (o ScriptVersion) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if o.Tag != "" {
		obj.Set("tag", o.Tag)
	}
	if o.Message != "" {
		obj.Set("message", o.Message)
	}
	return obj
}

// TracePreviewInfo
type TracePreviewInfo struct {
	ID   string `js:"id"`
	Slug string `js:"slug"`
	Name string `js:"name"`
}

func tracePreviewInfoFromJS(v js.Value) (TracePreviewInfo, error) {
	var out TracePreviewInfo
	{
		out.ID = v.Get("id").String()
	}
	{
		out.Slug = v.Get("slug").String()
	}
	{
		out.Name = v.Get("name").String()
	}
	return out, nil
}

func (o TracePreviewInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if o.Slug != "" {
		obj.Set("slug", o.Slug)
	}
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	return obj
}

// TraceItemFetchEventInfo
type TraceItemFetchEventInfo struct {
	Response *TraceItemFetchEventInfoResponse `js:"response"`
	Request  *TraceItemFetchEventInfoRequest  `js:"request"`
}

func traceItemFetchEventInfoFromJS(v js.Value) (TraceItemFetchEventInfo, error) {
	var out TraceItemFetchEventInfo
	{
		if !jsrt.IsNil(v.Get("response")) {
			var val TraceItemFetchEventInfoResponse
			if tmp, err := traceItemFetchEventInfoResponseFromJS(v.Get("response")); err != nil {
				return TraceItemFetchEventInfo{}, err
			} else {
				val = tmp
			}
			out.Response = &val
		}
	}
	{
		out.Request = TraceItemFetchEventInfoRequestFromJS(v.Get("request"))
	}
	return out, nil
}

func (o TraceItemFetchEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Response != nil {
		obj.Set("response", (*o.Response).toJS())
	}
	if o.Request != nil {
		obj.Set("request", o.Request.JSValue())
	}
	return obj
}

// TraceItemFetchEventInfoRequest
type TraceItemFetchEventInfoRequest struct{ v js.Value }

// TraceItemFetchEventInfoRequestFromJS wraps a JS TraceItemFetchEventInfoRequest value.
func TraceItemFetchEventInfoRequestFromJS(v js.Value) *TraceItemFetchEventInfoRequest {
	return &TraceItemFetchEventInfoRequest{v: v}
}

// JSValue returns the underlying JS value.
func (x *TraceItemFetchEventInfoRequest) JSValue() js.Value { return x.v }

// CF
func (x *TraceItemFetchEventInfoRequest) CF() js.Value {
	var ret js.Value
	if s := x.v.Get("cf"); !s.IsUndefined() && !s.IsNull() {
		ret = s
	}
	return ret
}

// Headers
func (x *TraceItemFetchEventInfoRequest) Headers() map[string]string {
	var ret map[string]string
	ret = make(map[string]string)
	keys := js.Global().Get("Object").Call("keys", x.v.Get("headers"))
	for i := 0; i < keys.Length(); i++ {
		k := keys.Index(i).String()
		var vv string
		vv = x.v.Get("headers").Get(k).String()
		ret[k] = vv
	}
	return ret
}

// Method
func (x *TraceItemFetchEventInfoRequest) Method() string {
	var ret string
	ret = x.v.Get("method").String()
	return ret
}

// URL
func (x *TraceItemFetchEventInfoRequest) URL() string {
	var ret string
	ret = x.v.Get("url").String()
	return ret
}

// GetUnredacted
func (x *TraceItemFetchEventInfoRequest) GetUnredacted() (*TraceItemFetchEventInfoRequest, error) {
	r, err := jsrt.Call(x.v, "getUnredacted")
	if err != nil {
		return nil, err
	}
	var ret *TraceItemFetchEventInfoRequest
	ret = TraceItemFetchEventInfoRequestFromJS(r)
	return ret, nil
}

// TraceItemFetchEventInfoResponse
type TraceItemFetchEventInfoResponse struct {
	Status float64 `js:"status"`
}

func traceItemFetchEventInfoResponseFromJS(v js.Value) (TraceItemFetchEventInfoResponse, error) {
	var out TraceItemFetchEventInfoResponse
	{
		out.Status = v.Get("status").Float()
	}
	return out, nil
}

func (o TraceItemFetchEventInfoResponse) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Status != 0 {
		obj.Set("status", o.Status)
	}
	return obj
}

// TraceItemJsRpcEventInfo
type TraceItemJsRpcEventInfo struct {
	RpcMethod string `js:"rpcMethod"`
}

func traceItemJsRpcEventInfoFromJS(v js.Value) (TraceItemJsRpcEventInfo, error) {
	var out TraceItemJsRpcEventInfo
	{
		out.RpcMethod = v.Get("rpcMethod").String()
	}
	return out, nil
}

func (o TraceItemJsRpcEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.RpcMethod != "" {
		obj.Set("rpcMethod", o.RpcMethod)
	}
	return obj
}

// TraceItemConnectEventInfo
type TraceItemConnectEventInfo struct {
}

func traceItemConnectEventInfoFromJS(v js.Value) (TraceItemConnectEventInfo, error) {
	var out TraceItemConnectEventInfo
	return out, nil
}

func (o TraceItemConnectEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	return obj
}

// TraceItemScheduledEventInfo
type TraceItemScheduledEventInfo struct {
	ScheduledTime float64 `js:"scheduledTime"`
	Cron          string  `js:"cron"`
}

func traceItemScheduledEventInfoFromJS(v js.Value) (TraceItemScheduledEventInfo, error) {
	var out TraceItemScheduledEventInfo
	{
		out.ScheduledTime = v.Get("scheduledTime").Float()
	}
	{
		out.Cron = v.Get("cron").String()
	}
	return out, nil
}

func (o TraceItemScheduledEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ScheduledTime != 0 {
		obj.Set("scheduledTime", o.ScheduledTime)
	}
	if o.Cron != "" {
		obj.Set("cron", o.Cron)
	}
	return obj
}

// TraceItemAlarmEventInfo
type TraceItemAlarmEventInfo struct {
	ScheduledTime time.Time `js:"scheduledTime"`
}

func traceItemAlarmEventInfoFromJS(v js.Value) (TraceItemAlarmEventInfo, error) {
	var out TraceItemAlarmEventInfo
	{
		out.ScheduledTime = jsrt.DateToTime(v.Get("scheduledTime"))
	}
	return out, nil
}

func (o TraceItemAlarmEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if !o.ScheduledTime.IsZero() {
		obj.Set("scheduledTime", jsrt.TimeToDate(o.ScheduledTime))
	}
	return obj
}

// TraceItemQueueEventInfo
type TraceItemQueueEventInfo struct {
	Queue     string  `js:"queue"`
	BatchSize float64 `js:"batchSize"`
}

func traceItemQueueEventInfoFromJS(v js.Value) (TraceItemQueueEventInfo, error) {
	var out TraceItemQueueEventInfo
	{
		out.Queue = v.Get("queue").String()
	}
	{
		out.BatchSize = v.Get("batchSize").Float()
	}
	return out, nil
}

func (o TraceItemQueueEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Queue != "" {
		obj.Set("queue", o.Queue)
	}
	if o.BatchSize != 0 {
		obj.Set("batchSize", o.BatchSize)
	}
	return obj
}

// TraceItemEmailEventInfo
type TraceItemEmailEventInfo struct {
	MailFrom string  `js:"mailFrom"`
	RcptTo   string  `js:"rcptTo"`
	RawSize  float64 `js:"rawSize"`
}

func traceItemEmailEventInfoFromJS(v js.Value) (TraceItemEmailEventInfo, error) {
	var out TraceItemEmailEventInfo
	{
		out.MailFrom = v.Get("mailFrom").String()
	}
	{
		out.RcptTo = v.Get("rcptTo").String()
	}
	{
		out.RawSize = v.Get("rawSize").Float()
	}
	return out, nil
}

func (o TraceItemEmailEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.MailFrom != "" {
		obj.Set("mailFrom", o.MailFrom)
	}
	if o.RcptTo != "" {
		obj.Set("rcptTo", o.RcptTo)
	}
	if o.RawSize != 0 {
		obj.Set("rawSize", o.RawSize)
	}
	return obj
}

// TraceItemTailEventInfo
type TraceItemTailEventInfo struct {
	ConsumedEvents []TraceItemTailEventInfoTailItem `js:"consumedEvents"`
}

func traceItemTailEventInfoFromJS(v js.Value) (TraceItemTailEventInfo, error) {
	var out TraceItemTailEventInfo
	{
		out.ConsumedEvents = make([]TraceItemTailEventInfoTailItem, v.Get("consumedEvents").Length())
		for i := range out.ConsumedEvents {
			if tmp, err := traceItemTailEventInfoTailItemFromJS(v.Get("consumedEvents").Index(i)); err != nil {
				return TraceItemTailEventInfo{}, err
			} else {
				out.ConsumedEvents[i] = tmp
			}
		}
	}
	return out, nil
}

func (o TraceItemTailEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.ConsumedEvents) > 0 {
		arr := js.Global().Get("Array").New(len(o.ConsumedEvents))
		for i, e := range o.ConsumedEvents {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("consumedEvents", arr)
	}
	return obj
}

// TraceItemTailEventInfoTailItem
type TraceItemTailEventInfoTailItem struct {
	ScriptName string `js:"scriptName"`
}

func traceItemTailEventInfoTailItemFromJS(v js.Value) (TraceItemTailEventInfoTailItem, error) {
	var out TraceItemTailEventInfoTailItem
	{
		if s := v.Get("scriptName"); !s.IsUndefined() && !s.IsNull() {
			out.ScriptName = s.String()
		}
	}
	return out, nil
}

func (o TraceItemTailEventInfoTailItem) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ScriptName != "" {
		obj.Set("scriptName", o.ScriptName)
	}
	return obj
}

// TraceItemCustomEventInfo
type TraceItemCustomEventInfo struct {
}

func traceItemCustomEventInfoFromJS(v js.Value) (TraceItemCustomEventInfo, error) {
	var out TraceItemCustomEventInfo
	return out, nil
}

func (o TraceItemCustomEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	return obj
}

// TraceItemHibernatableWebSocketEventInfo
type TraceItemHibernatableWebSocketEventInfo struct {
	GetWebSocketEvent TraceItemHibernatableWebSocketEventInfoGetWebSocketEvent `js:"getWebSocketEvent"`
}

func traceItemHibernatableWebSocketEventInfoFromJS(v js.Value) (TraceItemHibernatableWebSocketEventInfo, error) {
	var out TraceItemHibernatableWebSocketEventInfo
	{
		if tmp, err := traceItemHibernatableWebSocketEventInfoGetWebSocketEventFromJS(v.Get("getWebSocketEvent")); err != nil {
			return TraceItemHibernatableWebSocketEventInfo{}, err
		} else {
			out.GetWebSocketEvent = tmp
		}
	}
	return out, nil
}

func (o TraceItemHibernatableWebSocketEventInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if true {
		obj.Set("getWebSocketEvent", o.GetWebSocketEvent.toJS())
	}
	return obj
}

// TraceItemHibernatableWebSocketEventInfoMessage
type TraceItemHibernatableWebSocketEventInfoMessage struct {
	WebSocketEventType string `js:"webSocketEventType"`
}

func traceItemHibernatableWebSocketEventInfoMessageFromJS(v js.Value) (TraceItemHibernatableWebSocketEventInfoMessage, error) {
	var out TraceItemHibernatableWebSocketEventInfoMessage
	{
		out.WebSocketEventType = v.Get("webSocketEventType").String()
	}
	return out, nil
}

func (o TraceItemHibernatableWebSocketEventInfoMessage) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.WebSocketEventType != "" {
		obj.Set("webSocketEventType", o.WebSocketEventType)
	}
	return obj
}

// TraceItemHibernatableWebSocketEventInfoClose
type TraceItemHibernatableWebSocketEventInfoClose struct {
	WebSocketEventType string  `js:"webSocketEventType"`
	Code               float64 `js:"code"`
	WasClean           bool    `js:"wasClean"`
}

func traceItemHibernatableWebSocketEventInfoCloseFromJS(v js.Value) (TraceItemHibernatableWebSocketEventInfoClose, error) {
	var out TraceItemHibernatableWebSocketEventInfoClose
	{
		out.WebSocketEventType = v.Get("webSocketEventType").String()
	}
	{
		out.Code = v.Get("code").Float()
	}
	{
		out.WasClean = v.Get("wasClean").Bool()
	}
	return out, nil
}

func (o TraceItemHibernatableWebSocketEventInfoClose) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.WebSocketEventType != "" {
		obj.Set("webSocketEventType", o.WebSocketEventType)
	}
	if o.Code != 0 {
		obj.Set("code", o.Code)
	}
	if o.WasClean {
		obj.Set("wasClean", o.WasClean)
	}
	return obj
}

// TraceItemHibernatableWebSocketEventInfoError
type TraceItemHibernatableWebSocketEventInfoError struct {
	WebSocketEventType string `js:"webSocketEventType"`
}

func traceItemHibernatableWebSocketEventInfoErrorFromJS(v js.Value) (TraceItemHibernatableWebSocketEventInfoError, error) {
	var out TraceItemHibernatableWebSocketEventInfoError
	{
		out.WebSocketEventType = v.Get("webSocketEventType").String()
	}
	return out, nil
}

func (o TraceItemHibernatableWebSocketEventInfoError) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.WebSocketEventType != "" {
		obj.Set("webSocketEventType", o.WebSocketEventType)
	}
	return obj
}

// TraceItemHibernatableWebSocketEventInfoGetWebSocketEvent
type TraceItemHibernatableWebSocketEventInfoGetWebSocketEvent struct {
	WebSocketEventType string  `js:"webSocketEventType"`
	Code               float64 `js:"code"`
	WasClean           bool    `js:"wasClean"`
}

func traceItemHibernatableWebSocketEventInfoGetWebSocketEventFromJS(v js.Value) (TraceItemHibernatableWebSocketEventInfoGetWebSocketEvent, error) {
	var out TraceItemHibernatableWebSocketEventInfoGetWebSocketEvent
	{
		out.WebSocketEventType = v.Get("webSocketEventType").String()
	}
	{
		if s := v.Get("code"); !s.IsUndefined() && !s.IsNull() {
			out.Code = s.Float()
		}
	}
	{
		if s := v.Get("wasClean"); !s.IsUndefined() && !s.IsNull() {
			out.WasClean = s.Bool()
		}
	}
	return out, nil
}

func (o TraceItemHibernatableWebSocketEventInfoGetWebSocketEvent) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.WebSocketEventType != "" {
		obj.Set("webSocketEventType", o.WebSocketEventType)
	}
	if o.Code != 0 {
		obj.Set("code", o.Code)
	}
	if o.WasClean {
		obj.Set("wasClean", o.WasClean)
	}
	return obj
}
