// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package workflows provides the Workflows binding
// (https://developers.cloudflare.com/workflows/).
package workflows

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Workflow
type Workflow struct{ v js.Value }

// WorkflowFromJS wraps a JS Workflow value.
func WorkflowFromJS(v js.Value) *Workflow { return &Workflow{v: v} }

// JSValue returns the underlying JS value.
func (x *Workflow) JSValue() js.Value { return x.v }

// NewWorkflow resolves the binding named bindingName from env.
func NewWorkflow(bindingName string) (*Workflow, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &Workflow{v: v}, nil
}

// Get Get a handle to an existing instance of the Workflow.
// @param id Id for the instance of this Workflow
// @returns A promise that resolves with a handle for the Instance
func (x *Workflow) Get(id string) (*WorkflowInstance, error) {
	p, err := jsrt.Call(x.v, "get", id)
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *WorkflowInstance
	ret = WorkflowInstanceFromJS(r)
	return ret, nil
}

// Create Create a new instance and return a handle to it. If a provided id exists, an error will be thrown.
// @param options Options when creating an instance including id and params
// @returns A promise that resolves with a handle for the Instance
func (x *Workflow) Create(options WorkflowInstanceCreateOptions) (*WorkflowInstance, error) {
	p, err := jsrt.Call(x.v, "create", options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *WorkflowInstance
	ret = WorkflowInstanceFromJS(r)
	return ret, nil
}

// DeleteBatch Delete a batch of Workflow instances and their stored state.
// `deleteBatch` is limited to 100 instances at a time. Duplicate IDs are deleted once.
// The result contains one entry for each input position; IDs that do not exist are returned as per-instance errors.
// @param instanceIds IDs of the Workflow instances to delete
// @returns A promise that resolves with the successfully deleted instances and any per-instance errors.
func (x *Workflow) DeleteBatch(instanceIds []string) (WorkflowBatchDeleteResult, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(instanceIds))
		for i, e := range instanceIds {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "deleteBatch", arg0)
	if err != nil {
		return WorkflowBatchDeleteResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return WorkflowBatchDeleteResult{}, err
	}
	var ret WorkflowBatchDeleteResult
	if tmp, err := workflowBatchDeleteResultFromJS(r); err != nil {
		return WorkflowBatchDeleteResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// WorkflowInstance
type WorkflowInstance struct{ v js.Value }

// WorkflowInstanceFromJS wraps a JS WorkflowInstance value.
func WorkflowInstanceFromJS(v js.Value) *WorkflowInstance { return &WorkflowInstance{v: v} }

// JSValue returns the underlying JS value.
func (x *WorkflowInstance) JSValue() js.Value { return x.v }

// ID
func (x *WorkflowInstance) ID() string {
	var ret string
	ret = x.v.Get("id").String()
	return ret
}

// Pause Pause the instance.
func (x *WorkflowInstance) Pause() error {
	p, err := jsrt.Call(x.v, "pause")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Resume Resume the instance. If it is already running, an error will be thrown.
func (x *WorkflowInstance) Resume() error {
	p, err := jsrt.Call(x.v, "resume")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Terminate Terminate the instance. If it is errored, terminated or complete, an error will be thrown.
// @param options Options for termination, including whether registered rollback handlers should run.
func (x *WorkflowInstance) Terminate(options WorkflowInstanceTerminateOptions) error {
	p, err := jsrt.Call(x.v, "terminate", options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Restart Restart the instance. Optionally restart from a specific step, preserving
// cached results for all steps before it.
// @param options Options for the restart, including an optional step to restart from.
func (x *WorkflowInstance) Restart(options WorkflowInstanceRestartOptions) error {
	p, err := jsrt.Call(x.v, "restart", options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Delete Delete the instance and its stored state.
func (x *WorkflowInstance) Delete() error {
	p, err := jsrt.Call(x.v, "delete")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Status Returns the current status of the instance.
func (x *WorkflowInstance) Status() (InstanceStatus, error) {
	p, err := jsrt.Call(x.v, "status")
	if err != nil {
		return InstanceStatus{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return InstanceStatus{}, err
	}
	var ret InstanceStatus
	if tmp, err := instanceStatusFromJS(r); err != nil {
		return InstanceStatus{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// WorkflowInstanceCreateOptions
type WorkflowInstanceCreateOptions struct {
	// An id for your Workflow instance. Must be unique within the Workflow.
	ID string `js:"id"`
	// The event payload the Workflow instance is triggered with
	Params js.Value `js:"params"`
	// The retention policy for Workflow instance.
	// Defaults to the maximum retention period available for the owner's account.
	Retention *WorkflowInstanceCreateOptionsRetention `js:"retention"`
	// A best-effort geographic placement preference for the Workflow instance.
	// See `WorkflowInstanceLocationHint` for supported regions.
	LocationHint WorkflowInstanceLocationHint `js:"locationHint"`
}

func workflowInstanceCreateOptionsFromJS(v js.Value) (WorkflowInstanceCreateOptions, error) {
	var out WorkflowInstanceCreateOptions
	{
		if s := v.Get("id"); !s.IsUndefined() && !s.IsNull() {
			out.ID = s.String()
		}
	}
	{
		if s := v.Get("params"); !s.IsUndefined() && !s.IsNull() {
			out.Params = s
		}
	}
	{
		if !jsrt.IsNil(v.Get("retention")) {
			var val WorkflowInstanceCreateOptionsRetention
			if tmp, err := workflowInstanceCreateOptionsRetentionFromJS(v.Get("retention")); err != nil {
				return WorkflowInstanceCreateOptions{}, err
			} else {
				val = tmp
			}
			out.Retention = &val
		}
	}
	{
		if s := v.Get("locationHint"); !s.IsUndefined() && !s.IsNull() {
			out.LocationHint = WorkflowInstanceLocationHint(s.String())
		}
	}
	return out, nil
}

func (o WorkflowInstanceCreateOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if !jsrt.IsNil(o.Params) {
		obj.Set("params", o.Params)
	}
	if o.Retention != nil {
		obj.Set("retention", (*o.Retention).toJS())
	}
	if o.LocationHint != "" {
		obj.Set("locationHint", string(o.LocationHint))
	}
	return obj
}

// WorkflowInstanceTerminateOptions
type WorkflowInstanceTerminateOptions struct {
	// If true, run registered rollback handlers before terminating the instance.
	// Only steps that registered rollback handlers are rolled back.
	Rollback bool `js:"rollback"`
}

func workflowInstanceTerminateOptionsFromJS(v js.Value) (WorkflowInstanceTerminateOptions, error) {
	var out WorkflowInstanceTerminateOptions
	{
		if s := v.Get("rollback"); !s.IsUndefined() && !s.IsNull() {
			out.Rollback = s.Bool()
		}
	}
	return out, nil
}

func (o WorkflowInstanceTerminateOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Rollback {
		obj.Set("rollback", o.Rollback)
	}
	return obj
}

// WorkflowInstanceRestartOptions
type WorkflowInstanceRestartOptions struct {
	// Restart from a specific step. If omitted, the instance restarts from the beginning.
	// The step must exist in the instance's execution history.
	From *WorkflowInstanceRestartOptionsFrom `js:"from"`
}

func workflowInstanceRestartOptionsFromJS(v js.Value) (WorkflowInstanceRestartOptions, error) {
	var out WorkflowInstanceRestartOptions
	{
		if !jsrt.IsNil(v.Get("from")) {
			var val WorkflowInstanceRestartOptionsFrom
			if tmp, err := workflowInstanceRestartOptionsFromFromJS(v.Get("from")); err != nil {
				return WorkflowInstanceRestartOptions{}, err
			} else {
				val = tmp
			}
			out.From = &val
		}
	}
	return out, nil
}

func (o WorkflowInstanceRestartOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.From != nil {
		obj.Set("from", (*o.From).toJS())
	}
	return obj
}

// WorkflowInstanceLocationHint Geographic regions supported when creating a Workflow instance.
// Location hints are best-effort placement preferences.
type WorkflowInstanceLocationHint string

const (
	WorkflowInstanceLocationHintWnam   WorkflowInstanceLocationHint = "wnam"
	WorkflowInstanceLocationHintEnam   WorkflowInstanceLocationHint = "enam"
	WorkflowInstanceLocationHintSam    WorkflowInstanceLocationHint = "sam"
	WorkflowInstanceLocationHintWeur   WorkflowInstanceLocationHint = "weur"
	WorkflowInstanceLocationHintEeur   WorkflowInstanceLocationHint = "eeur"
	WorkflowInstanceLocationHintApac   WorkflowInstanceLocationHint = "apac"
	WorkflowInstanceLocationHintApacNe WorkflowInstanceLocationHint = "apac-ne"
	WorkflowInstanceLocationHintApacSe WorkflowInstanceLocationHint = "apac-se"
	WorkflowInstanceLocationHintOc     WorkflowInstanceLocationHint = "oc"
	WorkflowInstanceLocationHintAfr    WorkflowInstanceLocationHint = "afr"
	WorkflowInstanceLocationHintMe     WorkflowInstanceLocationHint = "me"
)

// WorkflowBatchDeleteResult
type WorkflowBatchDeleteResult struct {
	Deleted []WorkflowBatchDeleteResultDeleted `js:"deleted"`
	Errors  []WorkflowBatchDeleteResultErrors  `js:"errors"`
}

func workflowBatchDeleteResultFromJS(v js.Value) (WorkflowBatchDeleteResult, error) {
	var out WorkflowBatchDeleteResult
	{
		out.Deleted = make([]WorkflowBatchDeleteResultDeleted, v.Get("deleted").Length())
		for i := range out.Deleted {
			if tmp, err := workflowBatchDeleteResultDeletedFromJS(v.Get("deleted").Index(i)); err != nil {
				return WorkflowBatchDeleteResult{}, err
			} else {
				out.Deleted[i] = tmp
			}
		}
	}
	{
		out.Errors = make([]WorkflowBatchDeleteResultErrors, v.Get("errors").Length())
		for i := range out.Errors {
			if tmp, err := workflowBatchDeleteResultErrorsFromJS(v.Get("errors").Index(i)); err != nil {
				return WorkflowBatchDeleteResult{}, err
			} else {
				out.Errors[i] = tmp
			}
		}
	}
	return out, nil
}

func (o WorkflowBatchDeleteResult) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Deleted) > 0 {
		arr := js.Global().Get("Array").New(len(o.Deleted))
		for i, e := range o.Deleted {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("deleted", arr)
	}
	if len(o.Errors) > 0 {
		arr := js.Global().Get("Array").New(len(o.Errors))
		for i, e := range o.Errors {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("errors", arr)
	}
	return obj
}

// InstanceStatus
type InstanceStatus struct {
	Status string               `js:"status"`
	Error  *InstanceStatusError `js:"error"`
	Output js.Value             `js:"output"`
}

func instanceStatusFromJS(v js.Value) (InstanceStatus, error) {
	var out InstanceStatus
	{
		out.Status = v.Get("status").String()
	}
	{
		if !jsrt.IsNil(v.Get("error")) {
			var val InstanceStatusError
			if tmp, err := instanceStatusErrorFromJS(v.Get("error")); err != nil {
				return InstanceStatus{}, err
			} else {
				val = tmp
			}
			out.Error = &val
		}
	}
	{
		if s := v.Get("output"); !s.IsUndefined() && !s.IsNull() {
			out.Output = s
		}
	}
	return out, nil
}

func (o InstanceStatus) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Status != "" {
		obj.Set("status", o.Status)
	}
	if o.Error != nil {
		obj.Set("error", (*o.Error).toJS())
	}
	if !jsrt.IsNil(o.Output) {
		obj.Set("output", o.Output)
	}
	return obj
}

// WorkflowRetentionDuration
type WorkflowRetentionDuration = js.Value

// WorkflowInstanceCreateOptionsRetention
type WorkflowInstanceCreateOptionsRetention struct {
	SuccessRetention js.Value `js:"successRetention"`
	ErrorRetention   js.Value `js:"errorRetention"`
}

func workflowInstanceCreateOptionsRetentionFromJS(v js.Value) (WorkflowInstanceCreateOptionsRetention, error) {
	var out WorkflowInstanceCreateOptionsRetention
	{
		if s := v.Get("successRetention"); !s.IsUndefined() && !s.IsNull() {
			out.SuccessRetention = s
		}
	}
	{
		if s := v.Get("errorRetention"); !s.IsUndefined() && !s.IsNull() {
			out.ErrorRetention = s
		}
	}
	return out, nil
}

func (o WorkflowInstanceCreateOptionsRetention) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.SuccessRetention) {
		obj.Set("successRetention", o.SuccessRetention)
	}
	if !jsrt.IsNil(o.ErrorRetention) {
		obj.Set("errorRetention", o.ErrorRetention)
	}
	return obj
}

// WorkflowInstanceRestartOptionsFrom
type WorkflowInstanceRestartOptionsFrom struct {
	// The step name as defined in your workflow code.
	Name string `js:"name"`
	// 1-indexed occurrence of this step name. Use when the same step name appears multiple times (e.g. in a loop).
	// @default 1
	Count float64 `js:"count"`
	// Step type filter. Use when different step types share the same name.
	Type string `js:"type"`
}

func workflowInstanceRestartOptionsFromFromJS(v js.Value) (WorkflowInstanceRestartOptionsFrom, error) {
	var out WorkflowInstanceRestartOptionsFrom
	{
		out.Name = v.Get("name").String()
	}
	{
		if s := v.Get("count"); !s.IsUndefined() && !s.IsNull() {
			out.Count = s.Float()
		}
	}
	{
		if s := v.Get("type"); !s.IsUndefined() && !s.IsNull() {
			out.Type = s.String()
		}
	}
	return out, nil
}

func (o WorkflowInstanceRestartOptionsFrom) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Count != 0 {
		obj.Set("count", o.Count)
	}
	if o.Type != "" {
		obj.Set("type", o.Type)
	}
	return obj
}

// WorkflowBatchDeleteResultDeleted
type WorkflowBatchDeleteResultDeleted struct {
	ID string `js:"id"`
}

func workflowBatchDeleteResultDeletedFromJS(v js.Value) (WorkflowBatchDeleteResultDeleted, error) {
	var out WorkflowBatchDeleteResultDeleted
	{
		out.ID = v.Get("id").String()
	}
	return out, nil
}

func (o WorkflowBatchDeleteResultDeleted) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	return obj
}

// WorkflowBatchDeleteResultErrors
type WorkflowBatchDeleteResultErrors struct {
	ID      string  `js:"id"`
	Code    float64 `js:"code"`
	Message string  `js:"message"`
}

func workflowBatchDeleteResultErrorsFromJS(v js.Value) (WorkflowBatchDeleteResultErrors, error) {
	var out WorkflowBatchDeleteResultErrors
	{
		out.ID = v.Get("id").String()
	}
	{
		out.Code = v.Get("code").Float()
	}
	{
		out.Message = v.Get("message").String()
	}
	return out, nil
}

func (o WorkflowBatchDeleteResultErrors) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if o.Code != 0 {
		obj.Set("code", o.Code)
	}
	if o.Message != "" {
		obj.Set("message", o.Message)
	}
	return obj
}

// InstanceStatusError
type InstanceStatusError struct {
	Name    string `js:"name"`
	Message string `js:"message"`
}

func instanceStatusErrorFromJS(v js.Value) (InstanceStatusError, error) {
	var out InstanceStatusError
	{
		out.Name = v.Get("name").String()
	}
	{
		out.Message = v.Get("message").String()
	}
	return out, nil
}

func (o InstanceStatusError) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Message != "" {
		obj.Set("message", o.Message)
	}
	return obj
}
