// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package images provides the Cloudflare Images runtime binding
// (https://developers.cloudflare.com/images/transform-images/bindings/).
//
// ImagesBinding.hosted (HostedImagesBinding, the CRUD API for the Images
// hosting product) is excluded; this package only covers the runtime
// image-transformation API (info/input/text + ImageTransformer).
package images

import (
	"io"
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// ImagesBinding
type ImagesBinding struct{ v js.Value }

// ImagesBindingFromJS wraps a JS ImagesBinding value.
func ImagesBindingFromJS(v js.Value) *ImagesBinding { return &ImagesBinding{v: v} }

// JSValue returns the underlying JS value.
func (x *ImagesBinding) JSValue() js.Value { return x.v }

// NewImagesBinding resolves the binding named bindingName from env.
func NewImagesBinding(bindingName string) (*ImagesBinding, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &ImagesBinding{v: v}, nil
}

// Info Get image metadata (type, width and height)
// @throws {@link ImagesError} with code 9412 if input is not an image
// @param stream The image bytes
func (x *ImagesBinding) Info(stream io.Reader, options ImageInputOptions) (js.Value, error) {
	p, err := jsrt.Call(x.v, "info", jsrt.ReadableStreamFromReader(stream), options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// Input Begin applying a series of transformations to an image
// @param stream The image bytes
// @returns A transform handle
func (x *ImagesBinding) Input(stream io.Reader, options ImageInputOptions) (*ImageTransformer, error) {
	r, err := jsrt.Call(x.v, "input", jsrt.ReadableStreamFromReader(stream), options.toJS())
	if err != nil {
		return nil, err
	}
	var ret *ImageTransformer
	ret = ImageTransformerFromJS(r)
	return ret, nil
}

// Text Begin applying a series of transformations to text
// @param content string to be rendered
// @param options font, optional color and size to use in rendering text
// @returns A transform handle
func (x *ImagesBinding) Text(content string, options TextOptions) (*ImageTransformer, error) {
	r, err := jsrt.Call(x.v, "text", content, options.toJS())
	if err != nil {
		return nil, err
	}
	var ret *ImageTransformer
	ret = ImageTransformerFromJS(r)
	return ret, nil
}

// ImageTransformer
type ImageTransformer struct{ v js.Value }

// ImageTransformerFromJS wraps a JS ImageTransformer value.
func ImageTransformerFromJS(v js.Value) *ImageTransformer { return &ImageTransformer{v: v} }

// JSValue returns the underlying JS value.
func (x *ImageTransformer) JSValue() js.Value { return x.v }

// Transform Apply transform next, returning a transform handle.
// You can then apply more transformations, draw, or retrieve the output.
// @param transform
func (x *ImageTransformer) Transform(transform ImageTransform) (*ImageTransformer, error) {
	r, err := jsrt.Call(x.v, "transform", transform.toJS())
	if err != nil {
		return nil, err
	}
	var ret *ImageTransformer
	ret = ImageTransformerFromJS(r)
	return ret, nil
}

// Draw Draw an image on this transformer, returning a transform handle.
// You can then apply more transformations, draw, or retrieve the output.
// @param image The image (or transformer that will give the image) to draw
// @param options The options configuring how to draw the image
func (x *ImageTransformer) Draw(image io.Reader, options ImageDrawOptions) (*ImageTransformer, error) {
	r, err := jsrt.Call(x.v, "draw", jsrt.ReadableStreamFromReader(image), options.toJS())
	if err != nil {
		return nil, err
	}
	var ret *ImageTransformer
	ret = ImageTransformerFromJS(r)
	return ret, nil
}

// Output Retrieve the image that results from applying the transforms to the
// provided input
// @param options Options that apply to the output e.g. output format
func (x *ImageTransformer) Output(options ImageOutputOptions) (*ImageTransformationResult, error) {
	p, err := jsrt.Call(x.v, "output", options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *ImageTransformationResult
	ret = ImageTransformationResultFromJS(r)
	return ret, nil
}

// ImageTransformationResult
type ImageTransformationResult struct{ v js.Value }

// ImageTransformationResultFromJS wraps a JS ImageTransformationResult value.
func ImageTransformationResultFromJS(v js.Value) *ImageTransformationResult {
	return &ImageTransformationResult{v: v}
}

// JSValue returns the underlying JS value.
func (x *ImageTransformationResult) JSValue() js.Value { return x.v }

// Response The image as a response, ready to store in cache or return to users
// @param options Options that apply to the returned response, e.g. additional headers
func (x *ImageTransformationResult) Response(options ImageTransformationResponseOptions) (js.Value, error) {
	r, err := jsrt.Call(x.v, "response", options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// ContentType The content type of the returned image
func (x *ImageTransformationResult) ContentType() (string, error) {
	r, err := jsrt.Call(x.v, "contentType")
	if err != nil {
		return "", err
	}
	var ret string
	ret = r.String()
	return ret, nil
}

// Image The bytes of the response
func (x *ImageTransformationResult) Image(options ImageTransformationOutputOptions) (io.ReadCloser, error) {
	r, err := jsrt.Call(x.v, "image", options.toJS())
	if err != nil {
		return nil, err
	}
	var ret io.ReadCloser
	ret = jsrt.ReadCloser(r)
	return ret, nil
}

// ImageInputOptions
type ImageInputOptions struct {
	Encoding string `js:"encoding"`
}

func imageInputOptionsFromJS(v js.Value) (ImageInputOptions, error) {
	var out ImageInputOptions
	{
		if s := v.Get("encoding"); !s.IsUndefined() && !s.IsNull() {
			out.Encoding = s.String()
		}
	}
	return out, nil
}

func (o ImageInputOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Encoding != "" {
		obj.Set("encoding", o.Encoding)
	}
	return obj
}

// ImageTransform
type ImageTransform struct {
	Width      float64  `js:"width"`
	Height     float64  `js:"height"`
	Background string   `js:"background"`
	Blur       float64  `js:"blur"`
	Border     js.Value `js:"border"`
	Brightness float64  `js:"brightness"`
	Contrast   float64  `js:"contrast"`
	Fit        string   `js:"fit"`
	Flip       string   `js:"flip"`
	Gamma      float64  `js:"gamma"`
	Segment    string   `js:"segment"`
	Gravity    js.Value `js:"gravity"`
	Rotate     js.Value `js:"rotate"`
	Saturation float64  `js:"saturation"`
	Sharpen    float64  `js:"sharpen"`
	Trim       js.Value `js:"trim"`
}

func imageTransformFromJS(v js.Value) (ImageTransform, error) {
	var out ImageTransform
	{
		if s := v.Get("width"); !s.IsUndefined() && !s.IsNull() {
			out.Width = s.Float()
		}
	}
	{
		if s := v.Get("height"); !s.IsUndefined() && !s.IsNull() {
			out.Height = s.Float()
		}
	}
	{
		if s := v.Get("background"); !s.IsUndefined() && !s.IsNull() {
			out.Background = s.String()
		}
	}
	{
		if s := v.Get("blur"); !s.IsUndefined() && !s.IsNull() {
			out.Blur = s.Float()
		}
	}
	{
		if s := v.Get("border"); !s.IsUndefined() && !s.IsNull() {
			out.Border = s
		}
	}
	{
		if s := v.Get("brightness"); !s.IsUndefined() && !s.IsNull() {
			out.Brightness = s.Float()
		}
	}
	{
		if s := v.Get("contrast"); !s.IsUndefined() && !s.IsNull() {
			out.Contrast = s.Float()
		}
	}
	{
		if s := v.Get("fit"); !s.IsUndefined() && !s.IsNull() {
			out.Fit = s.String()
		}
	}
	{
		if s := v.Get("flip"); !s.IsUndefined() && !s.IsNull() {
			out.Flip = s.String()
		}
	}
	{
		if s := v.Get("gamma"); !s.IsUndefined() && !s.IsNull() {
			out.Gamma = s.Float()
		}
	}
	{
		if s := v.Get("segment"); !s.IsUndefined() && !s.IsNull() {
			out.Segment = s.String()
		}
	}
	{
		if s := v.Get("gravity"); !s.IsUndefined() && !s.IsNull() {
			out.Gravity = s
		}
	}
	{
		if s := v.Get("rotate"); !s.IsUndefined() && !s.IsNull() {
			out.Rotate = s
		}
	}
	{
		if s := v.Get("saturation"); !s.IsUndefined() && !s.IsNull() {
			out.Saturation = s.Float()
		}
	}
	{
		if s := v.Get("sharpen"); !s.IsUndefined() && !s.IsNull() {
			out.Sharpen = s.Float()
		}
	}
	{
		if s := v.Get("trim"); !s.IsUndefined() && !s.IsNull() {
			out.Trim = s
		}
	}
	return out, nil
}

func (o ImageTransform) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Width != 0 {
		obj.Set("width", o.Width)
	}
	if o.Height != 0 {
		obj.Set("height", o.Height)
	}
	if o.Background != "" {
		obj.Set("background", o.Background)
	}
	if o.Blur != 0 {
		obj.Set("blur", o.Blur)
	}
	if !jsrt.IsNil(o.Border) {
		obj.Set("border", o.Border)
	}
	if o.Brightness != 0 {
		obj.Set("brightness", o.Brightness)
	}
	if o.Contrast != 0 {
		obj.Set("contrast", o.Contrast)
	}
	if o.Fit != "" {
		obj.Set("fit", o.Fit)
	}
	if o.Flip != "" {
		obj.Set("flip", o.Flip)
	}
	if o.Gamma != 0 {
		obj.Set("gamma", o.Gamma)
	}
	if o.Segment != "" {
		obj.Set("segment", o.Segment)
	}
	if !jsrt.IsNil(o.Gravity) {
		obj.Set("gravity", o.Gravity)
	}
	if !jsrt.IsNil(o.Rotate) {
		obj.Set("rotate", o.Rotate)
	}
	if o.Saturation != 0 {
		obj.Set("saturation", o.Saturation)
	}
	if o.Sharpen != 0 {
		obj.Set("sharpen", o.Sharpen)
	}
	if !jsrt.IsNil(o.Trim) {
		obj.Set("trim", o.Trim)
	}
	return obj
}

// ImageDrawOptions
type ImageDrawOptions struct {
	Opacity   float64            `js:"opacity"`
	Repeat    js.Value           `js:"repeat"`
	Composite ImageCompositeMode `js:"composite"`
	Top       float64            `js:"top"`
	Left      float64            `js:"left"`
	Bottom    float64            `js:"bottom"`
	Right     float64            `js:"right"`
}

func imageDrawOptionsFromJS(v js.Value) (ImageDrawOptions, error) {
	var out ImageDrawOptions
	{
		if s := v.Get("opacity"); !s.IsUndefined() && !s.IsNull() {
			out.Opacity = s.Float()
		}
	}
	{
		if s := v.Get("repeat"); !s.IsUndefined() && !s.IsNull() {
			out.Repeat = s
		}
	}
	{
		if s := v.Get("composite"); !s.IsUndefined() && !s.IsNull() {
			out.Composite = ImageCompositeMode(s.String())
		}
	}
	{
		if s := v.Get("top"); !s.IsUndefined() && !s.IsNull() {
			out.Top = s.Float()
		}
	}
	{
		if s := v.Get("left"); !s.IsUndefined() && !s.IsNull() {
			out.Left = s.Float()
		}
	}
	{
		if s := v.Get("bottom"); !s.IsUndefined() && !s.IsNull() {
			out.Bottom = s.Float()
		}
	}
	{
		if s := v.Get("right"); !s.IsUndefined() && !s.IsNull() {
			out.Right = s.Float()
		}
	}
	return out, nil
}

func (o ImageDrawOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Opacity != 0 {
		obj.Set("opacity", o.Opacity)
	}
	if !jsrt.IsNil(o.Repeat) {
		obj.Set("repeat", o.Repeat)
	}
	if o.Composite != "" {
		obj.Set("composite", string(o.Composite))
	}
	if o.Top != 0 {
		obj.Set("top", o.Top)
	}
	if o.Left != 0 {
		obj.Set("left", o.Left)
	}
	if o.Bottom != 0 {
		obj.Set("bottom", o.Bottom)
	}
	if o.Right != 0 {
		obj.Set("right", o.Right)
	}
	return obj
}

// ImageCompositeMode
type ImageCompositeMode string

const (
	ImageCompositeModeOver    ImageCompositeMode = "over"
	ImageCompositeModeIn      ImageCompositeMode = "in"
	ImageCompositeModeAtop    ImageCompositeMode = "atop"
	ImageCompositeModeOut     ImageCompositeMode = "out"
	ImageCompositeModeXor     ImageCompositeMode = "xor"
	ImageCompositeModeLighter ImageCompositeMode = "lighter"
)

// ImageOutputOptions
type ImageOutputOptions struct {
	Format     string  `js:"format"`
	Quality    float64 `js:"quality"`
	Background string  `js:"background"`
	Anim       bool    `js:"anim"`
}

func imageOutputOptionsFromJS(v js.Value) (ImageOutputOptions, error) {
	var out ImageOutputOptions
	{
		out.Format = v.Get("format").String()
	}
	{
		if s := v.Get("quality"); !s.IsUndefined() && !s.IsNull() {
			out.Quality = s.Float()
		}
	}
	{
		if s := v.Get("background"); !s.IsUndefined() && !s.IsNull() {
			out.Background = s.String()
		}
	}
	{
		if s := v.Get("anim"); !s.IsUndefined() && !s.IsNull() {
			out.Anim = s.Bool()
		}
	}
	return out, nil
}

func (o ImageOutputOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Format != "" {
		obj.Set("format", o.Format)
	}
	if o.Quality != 0 {
		obj.Set("quality", o.Quality)
	}
	if o.Background != "" {
		obj.Set("background", o.Background)
	}
	if o.Anim {
		obj.Set("anim", o.Anim)
	}
	return obj
}

// ImageInfoResponse
type ImageInfoResponse = js.Value

// ImageTransformationResponseOptions
type ImageTransformationResponseOptions struct {
	Headers js.Value `js:"headers"`
}

func imageTransformationResponseOptionsFromJS(v js.Value) (ImageTransformationResponseOptions, error) {
	var out ImageTransformationResponseOptions
	{
		if s := v.Get("headers"); !s.IsUndefined() && !s.IsNull() {
			out.Headers = s
		}
	}
	return out, nil
}

func (o ImageTransformationResponseOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.Headers) {
		obj.Set("headers", o.Headers)
	}
	return obj
}

// ImageTransformationOutputOptions
type ImageTransformationOutputOptions struct {
	Encoding string `js:"encoding"`
}

func imageTransformationOutputOptionsFromJS(v js.Value) (ImageTransformationOutputOptions, error) {
	var out ImageTransformationOutputOptions
	{
		if s := v.Get("encoding"); !s.IsUndefined() && !s.IsNull() {
			out.Encoding = s.String()
		}
	}
	return out, nil
}

func (o ImageTransformationOutputOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Encoding != "" {
		obj.Set("encoding", o.Encoding)
	}
	return obj
}

// TextOptions
type TextOptions struct {
	// Font configuration
	Font js.Value `js:"font"`
	// Font size in points (pt)
	Size float64 `js:"size"`
	// Text color in CSS format: hex (#RRGGBB or #RRGGBBAA), rgb(r,g,b), rgba(r,g,b,a), or named colors
	Color string `js:"color"`
}

func textOptionsFromJS(v js.Value) (TextOptions, error) {
	var out TextOptions
	{
		out.Font = v.Get("font")
	}
	{
		if s := v.Get("size"); !s.IsUndefined() && !s.IsNull() {
			out.Size = s.Float()
		}
	}
	{
		if s := v.Get("color"); !s.IsUndefined() && !s.IsNull() {
			out.Color = s.String()
		}
	}
	return out, nil
}

func (o TextOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.Font) {
		obj.Set("font", o.Font)
	}
	if o.Size != 0 {
		obj.Set("size", o.Size)
	}
	if o.Color != "" {
		obj.Set("color", o.Color)
	}
	return obj
}
