import { defineMeta } from "blume";

export default defineMeta({
  order: 2,
  title: "Cloudflare",
  pages: [
    "environment-variables",
    "kv",
    "r2",
    "d1",
    "cache",
    "durable-objects",
    "queues",
    "cron",
    "fetch-event",
    "fetch",
    "sockets",
    "pages-functions",
    "ai",
    "analytics",
    "cf",
    "dispatch",
    "email",
    "hyperdrive",
    "images",
    "ratelimit",
    "secrets",
    "tail",
    "vectorize",
    "versions",
    "websocket",
    "workflows",
    "hono",
    "build",
  ],
});
