// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package secretsstore provides the Secrets Store binding
// (https://developers.cloudflare.com/secrets-store/integrations/workers/):
// SecretsStoreSecret, a binding exposing a single async Get() (string,
// error).
package secretsstore

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// SecretsStoreSecret
type SecretsStoreSecret struct{ v js.Value }

// SecretsStoreSecretFromJS wraps a JS SecretsStoreSecret value.
func SecretsStoreSecretFromJS(v js.Value) *SecretsStoreSecret { return &SecretsStoreSecret{v: v} }

// JSValue returns the underlying JS value.
func (x *SecretsStoreSecret) JSValue() js.Value { return x.v }

// NewSecretsStoreSecret resolves the binding named bindingName from env.
func NewSecretsStoreSecret(bindingName string) (*SecretsStoreSecret, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &SecretsStoreSecret{v: v}, nil
}

// Get Get a secret from the Secrets Store, returning a string of the secret value
// if it exists, or throws an error if it does not exist
func (x *SecretsStoreSecret) Get() (string, error) {
	p, err := jsrt.Call(x.v, "get")
	if err != nil {
		return "", err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return "", err
	}
	var ret string
	ret = r.String()
	return ret, nil
}
