// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package ai provides the Workers AI binding
// (https://developers.cloudflare.com/workers-ai/).
//
// Ai.run is a TypeScript overload set keyed by a generic AiModelList[Name]
// type parameter (six type-level overloads picking apart streaming vs.
// non-streaming, batch, and raw-response variants); cfgen cannot generate
// Go from a type parameter indexed like that, so Ai.run itself is
// hand-written in ai.go, calling straight through to the underlying JS
// method with a plain model string and js.Value inputs. Run/RunStream/
// RunTextGeneration/RunTextGenerationStream/RunTextEmbeddings in ai.go
// build on that, using the toJS/fromJS helpers generated below for
// AiTextGenerationInput/Output and AiTextEmbeddingsInput/Output.
//
// Ai.gateway, Ai.aiSearch, Ai.autorag, and Ai.toMarkdown are excluded: they
// return handle types (AiGateway, AiSearchNamespace, AutoRAG) or overloaded
// helpers this package doesn't otherwise wrap yet.
//
// RoleScopedChatInput.role's .d.ts type is a union of the literals "user",
// "assistant", "system", "tool" plus a `string & NonNullable<unknown>`
// branch (a common TypeScript idiom for "one of these, but any other string
// is also fine") — not a pure string-literal union, so cfgen would
// otherwise fall back to js.Value; it is mapped to plain string instead,
// since that's what every branch actually is at runtime.
//
// Model-specific per-model input/output interfaces (the Ai_Cf_* family) and
// the other AiXxxInput/Output pairs beyond text generation and embeddings
// are not included: model IDs are passed as a plain string (AiModels'
// mapped-type keys aren't representable in the IR), so there is no
// strongly-typed model -> input/output pairing to generate here in the
// first place. Callers needing one of those shapes can build the request
// as js.Value and call Ai.Run directly.
//
// Every included declaration name starting with "Ai" is force-renamed to
// keep that exact casing (see rename: below): cfgen's default naming would
// otherwise expand the "ai" acronym per its naming table (ai -> AI, same
// rule that turns IncomingRequestCfProperties into
// IncomingRequestCFProperties in the cf package), producing AI/AIOptions/
// AITextGenerationInput/... — which stutters badly as a type in a package
// already named ai (ai.AI) and doesn't match Cloudflare's own class name
// (Ai, not AI). rename keeps ai.Ai, ai.AiOptions, ai.AiTextGenerationInput,
// and so on, matching the hand-written ai.go call sites (e.g.
// aiTextGenerationOutputFromJS, not aITextGenerationOutputFromJS).
//
// AiTextEmbeddingsOutput.data is (number[])[] in the .d.ts, i.e. Go
// [][]float64 by cfgen's default array-of-array mapping (data is left
// unmapped here; no types: override is needed).
package ai

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Ai
type Ai struct{ v js.Value }

// AiFromJS wraps a JS Ai value.
func AiFromJS(v js.Value) *Ai { return &Ai{v: v} }

// JSValue returns the underlying JS value.
func (x *Ai) JSValue() js.Value { return x.v }

// NewAi resolves the binding named bindingName from env.
func NewAi(bindingName string) (*Ai, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &Ai{v: v}, nil
}

// AIGatewayLogID
func (x *Ai) AIGatewayLogID() string {
	var ret string
	if s := x.v.Get("aiGatewayLogId"); !s.IsUndefined() && !s.IsNull() {
		ret = s.String()
	}
	return ret
}

// Models
func (x *Ai) Models(params AiModelsSearchParams) ([]AiModelsSearchObject, error) {
	p, err := jsrt.Call(x.v, "models", params.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret []AiModelsSearchObject
	ret = make([]AiModelsSearchObject, r.Length())
	for i := range ret {
		if tmp, err := aiModelsSearchObjectFromJS(r.Index(i)); err != nil {
			return nil, err
		} else {
			ret[i] = tmp
		}
	}
	return ret, nil
}

// AiOptions
type AiOptions struct {
	// Send requests as an asynchronous batch job, only works for supported models
	// https://developers.cloudflare.com/workers-ai/features/batch-api
	QueueRequest bool `js:"queueRequest"`
	// Establish websocket connections, only works for supported models
	Websocket bool `js:"websocket"`
	// Tag your requests to group and view them in Cloudflare dashboard.
	//
	// Rules:
	// Tags must only contain letters, numbers, and the symbols: : - . / @
	// Each tag can have maximum 50 characters.
	// Maximum 5 tags are allowed each request.
	// Duplicate tags will removed.
	Tags              []string `js:"tags"`
	Gateway           js.Value `js:"gateway"`
	ReturnRawResponse bool     `js:"returnRawResponse"`
	Prefix            string   `js:"prefix"`
	ExtraHeaders      js.Value `js:"extraHeaders"`
	Signal            js.Value `js:"signal"`
}

func aiOptionsFromJS(v js.Value) (AiOptions, error) {
	var out AiOptions
	{
		if s := v.Get("queueRequest"); !s.IsUndefined() && !s.IsNull() {
			out.QueueRequest = s.Bool()
		}
	}
	{
		if s := v.Get("websocket"); !s.IsUndefined() && !s.IsNull() {
			out.Websocket = s.Bool()
		}
	}
	{
		if s := v.Get("tags"); !s.IsUndefined() && !s.IsNull() {
			out.Tags = make([]string, s.Length())
			for i := range out.Tags {
				out.Tags[i] = s.Index(i).String()
			}
		}
	}
	{
		if s := v.Get("gateway"); !s.IsUndefined() && !s.IsNull() {
			out.Gateway = s
		}
	}
	{
		if s := v.Get("returnRawResponse"); !s.IsUndefined() && !s.IsNull() {
			out.ReturnRawResponse = s.Bool()
		}
	}
	{
		if s := v.Get("prefix"); !s.IsUndefined() && !s.IsNull() {
			out.Prefix = s.String()
		}
	}
	{
		if s := v.Get("extraHeaders"); !s.IsUndefined() && !s.IsNull() {
			out.ExtraHeaders = s
		}
	}
	{
		if s := v.Get("signal"); !s.IsUndefined() && !s.IsNull() {
			out.Signal = s
		}
	}
	return out, nil
}

func (o AiOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.QueueRequest {
		obj.Set("queueRequest", o.QueueRequest)
	}
	if o.Websocket {
		obj.Set("websocket", o.Websocket)
	}
	if len(o.Tags) > 0 {
		arr := js.Global().Get("Array").New(len(o.Tags))
		for i, e := range o.Tags {
			arr.SetIndex(i, e)
		}
		obj.Set("tags", arr)
	}
	if !jsrt.IsNil(o.Gateway) {
		obj.Set("gateway", o.Gateway)
	}
	if o.ReturnRawResponse {
		obj.Set("returnRawResponse", o.ReturnRawResponse)
	}
	if o.Prefix != "" {
		obj.Set("prefix", o.Prefix)
	}
	if !jsrt.IsNil(o.ExtraHeaders) {
		obj.Set("extraHeaders", o.ExtraHeaders)
	}
	if !jsrt.IsNil(o.Signal) {
		obj.Set("signal", o.Signal)
	}
	return obj
}

// AiTextGenerationInput
type AiTextGenerationInput struct {
	Prompt            string                `js:"prompt"`
	Raw               bool                  `js:"raw"`
	Stream            bool                  `js:"stream"`
	MaxTokens         float64               `js:"max_tokens"`
	Temperature       float64               `js:"temperature"`
	TopP              float64               `js:"top_p"`
	TopK              float64               `js:"top_k"`
	Seed              float64               `js:"seed"`
	RepetitionPenalty float64               `js:"repetition_penalty"`
	FrequencyPenalty  float64               `js:"frequency_penalty"`
	PresencePenalty   float64               `js:"presence_penalty"`
	Messages          []RoleScopedChatInput `js:"messages"`
	ResponseFormat    js.Value              `js:"response_format"`
	Tools             js.Value              `js:"tools"`
	Functions         []js.Value            `js:"functions"`
}

func aiTextGenerationInputFromJS(v js.Value) (AiTextGenerationInput, error) {
	var out AiTextGenerationInput
	{
		if s := v.Get("prompt"); !s.IsUndefined() && !s.IsNull() {
			out.Prompt = s.String()
		}
	}
	{
		if s := v.Get("raw"); !s.IsUndefined() && !s.IsNull() {
			out.Raw = s.Bool()
		}
	}
	{
		if s := v.Get("stream"); !s.IsUndefined() && !s.IsNull() {
			out.Stream = s.Bool()
		}
	}
	{
		if s := v.Get("max_tokens"); !s.IsUndefined() && !s.IsNull() {
			out.MaxTokens = s.Float()
		}
	}
	{
		if s := v.Get("temperature"); !s.IsUndefined() && !s.IsNull() {
			out.Temperature = s.Float()
		}
	}
	{
		if s := v.Get("top_p"); !s.IsUndefined() && !s.IsNull() {
			out.TopP = s.Float()
		}
	}
	{
		if s := v.Get("top_k"); !s.IsUndefined() && !s.IsNull() {
			out.TopK = s.Float()
		}
	}
	{
		if s := v.Get("seed"); !s.IsUndefined() && !s.IsNull() {
			out.Seed = s.Float()
		}
	}
	{
		if s := v.Get("repetition_penalty"); !s.IsUndefined() && !s.IsNull() {
			out.RepetitionPenalty = s.Float()
		}
	}
	{
		if s := v.Get("frequency_penalty"); !s.IsUndefined() && !s.IsNull() {
			out.FrequencyPenalty = s.Float()
		}
	}
	{
		if s := v.Get("presence_penalty"); !s.IsUndefined() && !s.IsNull() {
			out.PresencePenalty = s.Float()
		}
	}
	{
		if s := v.Get("messages"); !s.IsUndefined() && !s.IsNull() {
			out.Messages = make([]RoleScopedChatInput, s.Length())
			for i := range out.Messages {
				if tmp, err := roleScopedChatInputFromJS(s.Index(i)); err != nil {
					return AiTextGenerationInput{}, err
				} else {
					out.Messages[i] = tmp
				}
			}
		}
	}
	{
		if s := v.Get("response_format"); !s.IsUndefined() && !s.IsNull() {
			out.ResponseFormat = s
		}
	}
	{
		if s := v.Get("tools"); !s.IsUndefined() && !s.IsNull() {
			out.Tools = s
		}
	}
	{
		if s := v.Get("functions"); !s.IsUndefined() && !s.IsNull() {
			out.Functions = make([]js.Value, s.Length())
			for i := range out.Functions {
				out.Functions[i] = s.Index(i)
			}
		}
	}
	return out, nil
}

func (o AiTextGenerationInput) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Prompt != "" {
		obj.Set("prompt", o.Prompt)
	}
	if o.Raw {
		obj.Set("raw", o.Raw)
	}
	if o.Stream {
		obj.Set("stream", o.Stream)
	}
	if o.MaxTokens != 0 {
		obj.Set("max_tokens", o.MaxTokens)
	}
	if o.Temperature != 0 {
		obj.Set("temperature", o.Temperature)
	}
	if o.TopP != 0 {
		obj.Set("top_p", o.TopP)
	}
	if o.TopK != 0 {
		obj.Set("top_k", o.TopK)
	}
	if o.Seed != 0 {
		obj.Set("seed", o.Seed)
	}
	if o.RepetitionPenalty != 0 {
		obj.Set("repetition_penalty", o.RepetitionPenalty)
	}
	if o.FrequencyPenalty != 0 {
		obj.Set("frequency_penalty", o.FrequencyPenalty)
	}
	if o.PresencePenalty != 0 {
		obj.Set("presence_penalty", o.PresencePenalty)
	}
	if len(o.Messages) > 0 {
		arr := js.Global().Get("Array").New(len(o.Messages))
		for i, e := range o.Messages {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("messages", arr)
	}
	if !jsrt.IsNil(o.ResponseFormat) {
		obj.Set("response_format", o.ResponseFormat)
	}
	if !jsrt.IsNil(o.Tools) {
		obj.Set("tools", o.Tools)
	}
	if len(o.Functions) > 0 {
		arr := js.Global().Get("Array").New(len(o.Functions))
		for i, e := range o.Functions {
			arr.SetIndex(i, e)
		}
		obj.Set("functions", arr)
	}
	return obj
}

// AiTextGenerationOutput
type AiTextGenerationOutput struct {
	Response  string     `js:"response"`
	ToolCalls js.Value   `js:"tool_calls"`
	Usage     *UsageTags `js:"usage"`
}

func aiTextGenerationOutputFromJS(v js.Value) (AiTextGenerationOutput, error) {
	var out AiTextGenerationOutput
	{
		if s := v.Get("response"); !s.IsUndefined() && !s.IsNull() {
			out.Response = s.String()
		}
	}
	{
		if s := v.Get("tool_calls"); !s.IsUndefined() && !s.IsNull() {
			out.ToolCalls = s
		}
	}
	{
		if !jsrt.IsNil(v.Get("usage")) {
			var val UsageTags
			if tmp, err := usageTagsFromJS(v.Get("usage")); err != nil {
				return AiTextGenerationOutput{}, err
			} else {
				val = tmp
			}
			out.Usage = &val
		}
	}
	return out, nil
}

func (o AiTextGenerationOutput) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Response != "" {
		obj.Set("response", o.Response)
	}
	if !jsrt.IsNil(o.ToolCalls) {
		obj.Set("tool_calls", o.ToolCalls)
	}
	if o.Usage != nil {
		obj.Set("usage", (*o.Usage).toJS())
	}
	return obj
}

// RoleScopedChatInput
type RoleScopedChatInput struct {
	Role    string `js:"role"`
	Content string `js:"content"`
	Name    string `js:"name"`
}

func roleScopedChatInputFromJS(v js.Value) (RoleScopedChatInput, error) {
	var out RoleScopedChatInput
	{
		out.Role = v.Get("role").String()
	}
	{
		out.Content = v.Get("content").String()
	}
	{
		if s := v.Get("name"); !s.IsUndefined() && !s.IsNull() {
			out.Name = s.String()
		}
	}
	return out, nil
}

func (o RoleScopedChatInput) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Role != "" {
		obj.Set("role", o.Role)
	}
	if o.Content != "" {
		obj.Set("content", o.Content)
	}
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	return obj
}

// AiTextEmbeddingsInput
type AiTextEmbeddingsInput struct {
	Text []string `js:"text"`
}

func aiTextEmbeddingsInputFromJS(v js.Value) (AiTextEmbeddingsInput, error) {
	var out AiTextEmbeddingsInput
	{
		out.Text = make([]string, v.Get("text").Length())
		for i := range out.Text {
			out.Text[i] = v.Get("text").Index(i).String()
		}
	}
	return out, nil
}

func (o AiTextEmbeddingsInput) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Text) > 0 {
		arr := js.Global().Get("Array").New(len(o.Text))
		for i, e := range o.Text {
			arr.SetIndex(i, e)
		}
		obj.Set("text", arr)
	}
	return obj
}

// AiTextEmbeddingsOutput
type AiTextEmbeddingsOutput struct {
	Shape []float64   `js:"shape"`
	Data  [][]float64 `js:"data"`
}

func aiTextEmbeddingsOutputFromJS(v js.Value) (AiTextEmbeddingsOutput, error) {
	var out AiTextEmbeddingsOutput
	{
		out.Shape = make([]float64, v.Get("shape").Length())
		for i := range out.Shape {
			out.Shape[i] = v.Get("shape").Index(i).Float()
		}
	}
	{
		out.Data = make([][]float64, v.Get("data").Length())
		for i := range out.Data {
			out.Data[i] = make([]float64, v.Get("data").Index(i).Length())
			for i1 := range out.Data[i] {
				out.Data[i][i1] = v.Get("data").Index(i).Index(i1).Float()
			}
		}
	}
	return out, nil
}

func (o AiTextEmbeddingsOutput) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Shape) > 0 {
		arr := js.Global().Get("Array").New(len(o.Shape))
		for i, e := range o.Shape {
			arr.SetIndex(i, e)
		}
		obj.Set("shape", arr)
	}
	if len(o.Data) > 0 {
		arr := js.Global().Get("Array").New(len(o.Data))
		for i, e := range o.Data {
			arr1 := js.Global().Get("Array").New(len(e))
			for i1, e1 := range e {
				arr1.SetIndex(i1, e1)
			}
			arr.SetIndex(i, arr1)
		}
		obj.Set("data", arr)
	}
	return obj
}

// AiModelsSearchParams
type AiModelsSearchParams struct {
	Author           string  `js:"author"`
	HideExperimental bool    `js:"hide_experimental"`
	Page             float64 `js:"page"`
	PerPage          float64 `js:"per_page"`
	Search           string  `js:"search"`
	Source           float64 `js:"source"`
	Task             string  `js:"task"`
}

func aiModelsSearchParamsFromJS(v js.Value) (AiModelsSearchParams, error) {
	var out AiModelsSearchParams
	{
		if s := v.Get("author"); !s.IsUndefined() && !s.IsNull() {
			out.Author = s.String()
		}
	}
	{
		if s := v.Get("hide_experimental"); !s.IsUndefined() && !s.IsNull() {
			out.HideExperimental = s.Bool()
		}
	}
	{
		if s := v.Get("page"); !s.IsUndefined() && !s.IsNull() {
			out.Page = s.Float()
		}
	}
	{
		if s := v.Get("per_page"); !s.IsUndefined() && !s.IsNull() {
			out.PerPage = s.Float()
		}
	}
	{
		if s := v.Get("search"); !s.IsUndefined() && !s.IsNull() {
			out.Search = s.String()
		}
	}
	{
		if s := v.Get("source"); !s.IsUndefined() && !s.IsNull() {
			out.Source = s.Float()
		}
	}
	{
		if s := v.Get("task"); !s.IsUndefined() && !s.IsNull() {
			out.Task = s.String()
		}
	}
	return out, nil
}

func (o AiModelsSearchParams) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Author != "" {
		obj.Set("author", o.Author)
	}
	if o.HideExperimental {
		obj.Set("hide_experimental", o.HideExperimental)
	}
	if o.Page != 0 {
		obj.Set("page", o.Page)
	}
	if o.PerPage != 0 {
		obj.Set("per_page", o.PerPage)
	}
	if o.Search != "" {
		obj.Set("search", o.Search)
	}
	if o.Source != 0 {
		obj.Set("source", o.Source)
	}
	if o.Task != "" {
		obj.Set("task", o.Task)
	}
	return obj
}

// AiModelsSearchObject
type AiModelsSearchObject struct {
	ID          string     `js:"id"`
	Source      float64    `js:"source"`
	Name        string     `js:"name"`
	Description string     `js:"description"`
	Task        js.Value   `js:"task"`
	Tags        []string   `js:"tags"`
	Properties  []js.Value `js:"properties"`
}

func aiModelsSearchObjectFromJS(v js.Value) (AiModelsSearchObject, error) {
	var out AiModelsSearchObject
	{
		out.ID = v.Get("id").String()
	}
	{
		out.Source = v.Get("source").Float()
	}
	{
		out.Name = v.Get("name").String()
	}
	{
		out.Description = v.Get("description").String()
	}
	{
		out.Task = v.Get("task")
	}
	{
		out.Tags = make([]string, v.Get("tags").Length())
		for i := range out.Tags {
			out.Tags[i] = v.Get("tags").Index(i).String()
		}
	}
	{
		out.Properties = make([]js.Value, v.Get("properties").Length())
		for i := range out.Properties {
			out.Properties[i] = v.Get("properties").Index(i)
		}
	}
	return out, nil
}

func (o AiModelsSearchObject) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if o.Source != 0 {
		obj.Set("source", o.Source)
	}
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Description != "" {
		obj.Set("description", o.Description)
	}
	if !jsrt.IsNil(o.Task) {
		obj.Set("task", o.Task)
	}
	if len(o.Tags) > 0 {
		arr := js.Global().Get("Array").New(len(o.Tags))
		for i, e := range o.Tags {
			arr.SetIndex(i, e)
		}
		obj.Set("tags", arr)
	}
	if len(o.Properties) > 0 {
		arr := js.Global().Get("Array").New(len(o.Properties))
		for i, e := range o.Properties {
			arr.SetIndex(i, e)
		}
		obj.Set("properties", arr)
	}
	return obj
}

// UsageTags
type UsageTags struct {
	PromptTokens     float64 `js:"prompt_tokens"`
	CompletionTokens float64 `js:"completion_tokens"`
	TotalTokens      float64 `js:"total_tokens"`
}

func usageTagsFromJS(v js.Value) (UsageTags, error) {
	var out UsageTags
	{
		out.PromptTokens = v.Get("prompt_tokens").Float()
	}
	{
		out.CompletionTokens = v.Get("completion_tokens").Float()
	}
	{
		out.TotalTokens = v.Get("total_tokens").Float()
	}
	return out, nil
}

func (o UsageTags) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.PromptTokens != 0 {
		obj.Set("prompt_tokens", o.PromptTokens)
	}
	if o.CompletionTokens != 0 {
		obj.Set("completion_tokens", o.CompletionTokens)
	}
	if o.TotalTokens != 0 {
		obj.Set("total_tokens", o.TotalTokens)
	}
	return obj
}
