// Code generated by scripts/gen-deno. DO NOT EDIT.

//go:build js && wasm

package deno

import (
	"github.com/syumai/workers-go/internal/jsutil"
	"syscall/js"
)

// An interface containing methods to interact with the process environment
// variables.
//
// Environment variables can also be loaded from a `.env` file by using the
// `--env-file` flag when running a Deno program:
//
// ```sh
// deno run --env-file=.env --allow-env main.ts
// ```
//
// If `--env-file` is specified without a value, it defaults to loading `.env`
// from the current working directory:
//
// ```sh
// deno run --env-file --allow-env main.ts
// ```
//
// Learn more at [the Deno docs](https://docs.deno.com/runtime/reference/env_variables/).
//   - https://docs.deno.com/api/deno/~/Deno.Env
type Env struct {
	instance js.Value
}

func envFromJS(v js.Value) *Env {
	if isNullish(v) {
		return nil
	}
	return &Env{instance: v}
}

func (x *Env) toJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.instance
}

// Retrieve the value of an environment variable.
//
// Returns `undefined` if the supplied environment variable is not defined.
//
// ```ts
// console.log(Deno.env.get("HOME"));  // e.g. outputs "/home/alice"
// console.log(Deno.env.get("MADE_UP_VAR"));  // outputs undefined
// ```
//
// Requires `allow-env` permission.
//   - https://docs.deno.com/api/deno/~/Deno.Env
func (x *Env) Get(key string) *string {
	return ptrFromJS(x.instance.Call("get", js.ValueOf(key)), getString)
}

// Set the value of an environment variable.
//
// ```ts
// Deno.env.set("SOME_VAR", "Value");
// Deno.env.get("SOME_VAR");  // outputs "Value"
// ```
//
// Requires `allow-env` permission.
//   - https://docs.deno.com/api/deno/~/Deno.Env
func (x *Env) Set(key string, value string) {
	x.instance.Call("set", js.ValueOf(key), js.ValueOf(value))
}

// Delete the value of an environment variable.
//
// ```ts
// Deno.env.set("SOME_VAR", "Value");
// Deno.env.delete("SOME_VAR");  // outputs "undefined"
// ```
//
// Requires `allow-env` permission.
//   - https://docs.deno.com/api/deno/~/Deno.Env
func (x *Env) Delete(key string) {
	x.instance.Call("delete", js.ValueOf(key))
}

// Check whether an environment variable is present or not.
//
// ```ts
// Deno.env.set("SOME_VAR", "Value");
// Deno.env.has("SOME_VAR");  // outputs true
// ```
//
// Requires `allow-env` permission.
//   - https://docs.deno.com/api/deno/~/Deno.Env
func (x *Env) Has(key string) bool {
	return getBool(x.instance.Call("has", js.ValueOf(key)))
}

// Returns a snapshot of the environment variables at invocation as a
// simple object of keys and values.
//
// ```ts
// Deno.env.set("TEST_VAR", "A");
// const myEnv = Deno.env.toObject();
// console.log(myEnv.SHELL);
// Deno.env.set("TEST_VAR", "B");
// console.log(myEnv.TEST_VAR);  // outputs "A"
// ```
//
// Requires `allow-env` permission.
//   - https://docs.deno.com/api/deno/~/Deno.Env
func (x *Env) ToObject() map[string]string {
	return jsutil.StrRecordToMap(x.instance.Call("toObject"))
}

// **UNSTABLE**: New API, yet to be vetted.
//
// An iterator over a range of data entries in a {@linkcode Deno.Kv}.
//
// The cursor getter returns the cursor that can be used to resume the
// iteration from the current position in the future.
//   - https://docs.deno.com/api/deno/~/Deno.KvListIterator
type KvListIterator struct {
	instance js.Value
}

func kvListIteratorFromJS(v js.Value) *KvListIterator {
	if isNullish(v) {
		return nil
	}
	return &KvListIterator{instance: v}
}

func (x *KvListIterator) toJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.instance
}

// Returns the cursor of the current position in the iteration. This cursor
// can be used to resume the iteration from the current position in the
// future by passing it to the `cursor` option of the `list` method.
//   - https://docs.deno.com/api/deno/~/Deno.KvListIterator
func (x *KvListIterator) Cursor() string {
	return getString(x.instance.Get("cursor"))
}

// - https://docs.deno.com/api/deno/~/Deno.KvListIterator
func (x *KvListIterator) Next() (js.Value, error) {
	v, err := jsutil.AwaitPromise(x.instance.Call("next"))
	if err != nil {
		return js.Value{}, err
	}
	return v, nil
}

// **UNSTABLE**: New API, yet to be vetted.
//
// An operation on a {@linkcode Deno.Kv} that can be performed
// atomically. Atomic operations do not auto-commit, and must be committed
// explicitly by calling the `commit` method.
//
// Atomic operations can be used to perform multiple mutations on the KV store
// in a single atomic transaction. They can also be used to perform
// conditional mutations by specifying one or more
// {@linkcode Deno.AtomicCheck}s that ensure that a mutation is only performed
// if the key-value pair in the KV has a specific versionstamp. If any of the
// checks fail, the entire operation will fail and no mutations will be made.
//
// The ordering of mutations is guaranteed to be the same as the ordering of
// the mutations specified in the operation. Checks are performed before any
// mutations are performed. The ordering of checks is unobservable.
//
// Atomic operations can be used to implement optimistic locking, where a
// mutation is only performed if the key-value pair in the KV store has not
// been modified since the last read. This can be done by specifying a check
// that ensures that the versionstamp of the key-value pair matches the
// versionstamp that was read. If the check fails, the mutation will not be
// performed and the operation will fail. One can then retry the read-modify-
// write operation in a loop until it succeeds.
//
// The `commit` method of an atomic operation returns a value indicating
// whether checks passed and mutations were performed. If the operation failed
// because of a failed check, the return value will be a
// {@linkcode Deno.KvCommitError} with an `ok: false` property. If the
// operation failed for any other reason (storage error, invalid value, etc.),
// an exception will be thrown. If the operation succeeded, the return value
// will be a {@linkcode Deno.KvCommitResult} object with a `ok: true` property
// and the versionstamp of the value committed to KV.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
type AtomicOperation struct {
	instance js.Value
}

func atomicOperationFromJS(v js.Value) *AtomicOperation {
	if isNullish(v) {
		return nil
	}
	return &AtomicOperation{instance: v}
}

func (x *AtomicOperation) toJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.instance
}

// Add to the operation a check that ensures that the versionstamp of the
// key-value pair in the KV store matches the given versionstamp. If the
// check fails, the entire operation will fail and no mutations will be
// performed during the commit.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Check(checks ...AtomicCheck) *AtomicOperation {
	args := []any{}
	for _, e := range checks {
		args = append(args, e.toJS())
	}
	x.instance.Call("check", args...)
	return x
}

// Add to the operation a mutation that performs the specified mutation on
// the specified key if all checks pass during the commit. The types and
// semantics of all available mutations are described in the documentation
// for {@linkcode Deno.KvMutation}.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Mutate(mutations ...KvMutation) *AtomicOperation {
	args := []any{}
	for _, e := range mutations {
		args = append(args, e.toJS())
	}
	x.instance.Call("mutate", args...)
	return x
}

// Shortcut for creating a `sum` mutation. This method wraps `n` in a
// {@linkcode Deno.KvU64}, so the value of `n` must be in the range
// `[0, 2^64-1]`.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Sum(key KvKey, n uint64) *AtomicOperation {
	x.instance.Call("sum", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }), BigInt(n))
	return x
}

// Shortcut for creating a `min` mutation. This method wraps `n` in a
// {@linkcode Deno.KvU64}, so the value of `n` must be in the range
// `[0, 2^64-1]`.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Min(key KvKey, n uint64) *AtomicOperation {
	x.instance.Call("min", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }), BigInt(n))
	return x
}

// Shortcut for creating a `max` mutation. This method wraps `n` in a
// {@linkcode Deno.KvU64}, so the value of `n` must be in the range
// `[0, 2^64-1]`.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Max(key KvKey, n uint64) *AtomicOperation {
	x.instance.Call("max", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }), BigInt(n))
	return x
}

// Add to the operation a mutation that sets the value of the specified key
// to the specified value if all checks pass during the commit.
//
// Optionally an `expireIn` option can be specified to set a time-to-live
// (TTL) for the key. The TTL is specified in milliseconds, and the key will
// be deleted from the database at earliest after the specified number of
// milliseconds have elapsed. Once the specified duration has passed, the
// key may still be visible for some additional time. If the `expireIn`
// option is not specified, the key will not expire.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Set(key KvKey, value any, options *AtomicOperationSetOptions) *AtomicOperation {
	args := []any{}
	args = append(args, sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationSetOptions) js.Value { return e.toJS() }))
	x.instance.Call("set", args...)
	return x
}

// Add to the operation a mutation that deletes the specified key if all
// checks pass during the commit.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Delete(key KvKey) *AtomicOperation {
	x.instance.Call("delete", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	return x
}

// Add to the operation a mutation that enqueues a value into the queue
// if all checks pass during the commit.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Enqueue(value any, options *AtomicOperationEnqueueOptions) *AtomicOperation {
	args := []any{}
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationEnqueueOptions) js.Value { return e.toJS() }))
	x.instance.Call("enqueue", args...)
	return x
}

// Commit the operation to the KV store. Returns a value indicating whether
// checks passed and mutations were performed. If the operation failed
// because of a failed check, the return value will be a {@linkcode
// Deno.KvCommitError} with an `ok: false` property. If the operation failed
// for any other reason (storage error, invalid value, etc.), an exception
// will be thrown. If the operation succeeded, the return value will be a
// {@linkcode Deno.KvCommitResult} object with a `ok: true` property and the
// versionstamp of the value committed to KV.
//
// If the commit returns `ok: false`, one may create a new atomic operation
// with updated checks and mutations and attempt to commit it again. See the
// note on optimistic locking in the documentation for
// {@linkcode Deno.AtomicOperation}.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicOperation
func (x *AtomicOperation) Commit() (AtomicOperationCommitResult, error) {
	v, err := jsutil.AwaitPromise(x.instance.Call("commit"))
	if err != nil {
		return AtomicOperationCommitResult{}, err
	}
	return atomicOperationCommitResultFromJS(v), nil
}

// **UNSTABLE**: New API, yet to be vetted.
//
// A key-value database that can be used to store and retrieve data.
//
// Data is stored as key-value pairs, where the key is a {@linkcode Deno.KvKey}
// and the value is an arbitrary structured-serializable JavaScript value.
// Keys are ordered lexicographically as described in the documentation for
// {@linkcode Deno.KvKey}. Keys are unique within a database, and the last
// value set for a given key is the one that is returned when reading the
// key. Keys can be deleted from the database, in which case they will no
// longer be returned when reading keys.
//
// Values can be any structured-serializable JavaScript value (objects,
// arrays, strings, numbers, etc.). The special value {@linkcode Deno.KvU64}
// can be used to store 64-bit unsigned integers in the database. This special
// value can not be nested within other objects or arrays. In addition to the
// regular database mutation operations, the unsigned 64-bit integer value
// also supports `sum`, `max`, and `min` mutations.
//
// Keys are versioned on write by assigning the key an ever-increasing
// "versionstamp". The versionstamp represents the version of a key-value pair
// in the database at some point in time, and can be used to perform
// transactional operations on the database without requiring any locking.
// This is enabled by atomic operations, which can have conditions that ensure
// that the operation only succeeds if the versionstamp of the key-value pair
// matches an expected versionstamp.
//
// Keys have a maximum length of 2048 bytes after serialization. Values have a
// maximum length of 64 KiB after serialization. Serialization of both keys
// and values is somewhat opaque, but one can usually assume that the
// serialization of any value is about the same length as the resulting string
// of a JSON serialization of that same value. If theses limits are exceeded,
// an exception will be thrown.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
type Kv struct {
	instance js.Value
}

func kvFromJS(v js.Value) *Kv {
	if isNullish(v) {
		return nil
	}
	return &Kv{instance: v}
}

func (x *Kv) toJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.instance
}

// Retrieve the value and versionstamp for the given key from the database
// in the form of a {@linkcode Deno.KvEntryMaybe}. If no value exists for
// the key, the returned entry will have a `null` value and versionstamp.
//
// ```ts
// const db = await Deno.openKv();
// const result = await db.get(["foo"]);
// result.key; // ["foo"]
// result.value; // "bar"
// result.versionstamp; // "00000000000000010000"
// ```
//
// The `consistency` option can be used to specify the consistency level
// for the read operation. The default consistency level is "strong". Some
// use cases can benefit from using a weaker consistency level. For more
// information on consistency levels, see the documentation for
// {@linkcode Deno.KvConsistencyLevel}.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Get(key KvKey, options *KvGetOptions) (KvEntryMaybe, error) {
	args := []any{}
	args = append(args, sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	args = append(args, ptrToJS(options, func(e KvGetOptions) js.Value { return e.toJS() }))
	v, err := jsutil.AwaitPromise(x.instance.Call("get", args...))
	if err != nil {
		return KvEntryMaybe{}, err
	}
	return kvEntryMaybeFromJS(v), nil
}

// Retrieve multiple values and versionstamps from the database in the form
// of an array of {@linkcode Deno.KvEntryMaybe} objects. The returned array
// will have the same length as the `keys` array, and the entries will be in
// the same order as the keys. If no value exists for a given key, the
// returned entry will have a `null` value and versionstamp.
//
// ```ts
// const db = await Deno.openKv();
// const result = await db.getMany([["foo"], ["baz"]]);
// result[0].key; // ["foo"]
// result[0].value; // "bar"
// result[0].versionstamp; // "00000000000000010000"
// result[1].key; // ["baz"]
// result[1].value; // null
// result[1].versionstamp; // null
// ```
//
// The `consistency` option can be used to specify the consistency level
// for the read operation. The default consistency level is "strong". Some
// use cases can benefit from using a weaker consistency level. For more
// information on consistency levels, see the documentation for
// {@linkcode Deno.KvConsistencyLevel}.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) GetMany(keys []KvKey, options *KvGetOptions) ([]KvEntryMaybe, error) {
	args := []any{}
	args = append(args, sliceToJS(keys, func(e KvKey) js.Value { return sliceToJS(e, func(e KvKeyPart) js.Value { return anyToJS(e) }) }))
	args = append(args, ptrToJS(options, func(e KvGetOptions) js.Value { return e.toJS() }))
	v, err := jsutil.AwaitPromise(x.instance.Call("getMany", args...))
	if err != nil {
		return nil, err
	}
	return sliceFromJS(v, kvEntryMaybeFromJS), nil
}

// Set the value for the given key in the database. If a value already
// exists for the key, it will be overwritten.
//
// ```ts
// const db = await Deno.openKv();
// await db.set(["foo"], "bar");
// ```
//
// Optionally an `expireIn` option can be specified to set a time-to-live
// (TTL) for the key. The TTL is specified in milliseconds, and the key will
// be deleted from the database at earliest after the specified number of
// milliseconds have elapsed. Once the specified duration has passed, the
// key may still be visible for some additional time. If the `expireIn`
// option is not specified, the key will not expire.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Set(key KvKey, value any, options *AtomicOperationSetOptions) (KvCommitResult, error) {
	args := []any{}
	args = append(args, sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationSetOptions) js.Value { return e.toJS() }))
	v, err := jsutil.AwaitPromise(x.instance.Call("set", args...))
	if err != nil {
		return KvCommitResult{}, err
	}
	return kvCommitResultFromJS(v), nil
}

// Delete the value for the given key from the database. If no value exists
// for the key, this operation is a no-op.
//
// ```ts
// const db = await Deno.openKv();
// await db.delete(["foo"]);
// ```
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Delete(key KvKey) error {
	_, err := jsutil.AwaitPromise(x.instance.Call("delete", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) })))
	return err
}

// Retrieve a list of keys in the database. The returned list is an
// {@linkcode Deno.KvListIterator} which can be used to iterate over the
// entries in the database.
//
// Each list operation must specify a selector which is used to specify the
// range of keys to return. The selector can either be a prefix selector, or
// a range selector:
//
//   - A prefix selector selects all keys that start with the given prefix of
//     key parts. For example, the selector `["users"]` will select all keys
//     that start with the prefix `["users"]`, such as `["users", "alice"]`
//     and `["users", "bob"]`. Note that you can not partially match a key
//     part, so the selector `["users", "a"]` will not match the key
//     `["users", "alice"]`. A prefix selector may specify a `start` key that
//     is used to skip over keys that are lexicographically less than the
//     start key.
//   - A range selector selects all keys that are lexicographically between
//     the given start and end keys (including the start, and excluding the
//     end). For example, the selector `["users", "a"], ["users", "n"]` will
//     select all keys that start with the prefix `["users"]` and have a
//     second key part that is lexicographically between `a` and `n`, such as
//     `["users", "alice"]`, `["users", "bob"]`, and `["users", "mike"]`, but
//     not `["users", "noa"]` or `["users", "zoe"]`.
//
// ```ts
// const db = await Deno.openKv();
// const entries = db.list({ prefix: ["users"] });
//
//	for await (const entry of entries) {
//	  entry.key; // ["users", "alice"]
//	  entry.value; // { name: "Alice" }
//	  entry.versionstamp; // "00000000000000010000"
//	}
//
// ```
//
// The `options` argument can be used to specify additional options for the
// list operation. See the documentation for {@linkcode Deno.KvListOptions}
// for more information.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) List(selector KvListSelector, options *KvListOptions) *KvListIterator {
	args := []any{}
	args = append(args, selector.toJS())
	args = append(args, ptrToJS(options, func(e KvListOptions) js.Value { return e.toJS() }))
	return kvListIteratorFromJS(x.instance.Call("list", args...))
}

// Add a value into the database queue to be delivered to the queue
// listener via {@linkcode Deno.Kv.listenQueue}.
//
// ```ts
// const db = await Deno.openKv();
// await db.enqueue("bar");
// ```
//
// The `delay` option can be used to specify the delay (in milliseconds)
// of the value delivery. The default delay is 0, which means immediate
// delivery.
//
// ```ts
// const db = await Deno.openKv();
// await db.enqueue("bar", { delay: 60000 });
// ```
//
// The `keysIfUndelivered` option can be used to specify the keys to
// be set if the value is not successfully delivered to the queue
// listener after several attempts. The values are set to the value of
// the queued message.
//
// The `backoffSchedule` option can be used to specify the retry policy for
// failed message delivery. Each element in the array represents the number of
// milliseconds to wait before retrying the delivery. For example,
// `[1000, 5000, 10000]` means that a failed delivery will be retried
// at most 3 times, with 1 second, 5 seconds, and 10 seconds delay
// between each retry.
//
// ```ts
// const db = await Deno.openKv();
//
//	await db.enqueue("bar", {
//	  keysIfUndelivered: [["foo", "bar"]],
//	  backoffSchedule: [1000, 5000, 10000],
//	});
//
// ```
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Enqueue(value any, options *AtomicOperationEnqueueOptions) (KvCommitResult, error) {
	args := []any{}
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationEnqueueOptions) js.Value { return e.toJS() }))
	v, err := jsutil.AwaitPromise(x.instance.Call("enqueue", args...))
	if err != nil {
		return KvCommitResult{}, err
	}
	return kvCommitResultFromJS(v), nil
}

// Listen for queue values to be delivered from the database queue, which
// were enqueued with {@linkcode Deno.Kv.enqueue}. The provided handler
// callback is invoked on every dequeued value. A failed callback
// invocation is automatically retried multiple times until it succeeds
// or until the maximum number of retries is reached.
//
// ```ts
// const db = await Deno.openKv();
//
//	db.listenQueue(async (msg: unknown) => {
//	  await db.set(["foo"], msg);
//	});
//
// ```
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) ListenQueue(handler js.Value) error {
	_, err := jsutil.AwaitPromise(x.instance.Call("listenQueue", handler))
	return err
}

// Create a new {@linkcode Deno.AtomicOperation} object which can be used to
// perform an atomic transaction on the database. This does not perform any
// operations on the database - the atomic transaction must be committed
// explicitly using the {@linkcode Deno.AtomicOperation.commit} method once
// all checks and mutations have been added to the operation.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Atomic() *AtomicOperation {
	return atomicOperationFromJS(x.instance.Call("atomic"))
}

// Watch for changes to the given keys in the database. The returned stream
// is a {@linkcode ReadableStream} that emits a new value whenever any of
// the watched keys change their versionstamp. The emitted value is an array
// of {@linkcode Deno.KvEntryMaybe} objects, with the same length and order
// as the `keys` array. If no value exists for a given key, the returned
// entry will have a `null` value and versionstamp.
//
// The returned stream does not return every single intermediate state of
// the watched keys, but rather only keeps you up to date with the latest
// state of the keys. This means that if a key is modified multiple times
// quickly, you may not receive a notification for every single change, but
// rather only the latest state of the key.
//
// ```ts
// const db = await Deno.openKv();
//
// const stream = db.watch([["foo"], ["bar"]]);
//
//	for await (const entries of stream) {
//	  entries[0].key; // ["foo"]
//	  entries[0].value; // "bar"
//	  entries[0].versionstamp; // "00000000000000010000"
//	  entries[1].key; // ["bar"]
//	  entries[1].value; // null
//	  entries[1].versionstamp; // null
//	}
//
// ```
//
// The `options` argument can be used to specify additional options for the
// watch operation. The `raw` option can be used to specify whether a new
// value should be emitted whenever a mutation occurs on any of the watched
// keys (even if the value of the key does not change, such as deleting a
// deleted key), or only when entries have observably changed in some way.
// When `raw: true` is used, it is possible for the stream to occasionally
// emit values even if no mutations have occurred on any of the watched
// keys. The default value for this option is `false`.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Watch(keys []KvKey, options *KvWatchOptions) js.Value {
	args := []any{}
	args = append(args, sliceToJS(keys, func(e KvKey) js.Value { return sliceToJS(e, func(e KvKeyPart) js.Value { return anyToJS(e) }) }))
	args = append(args, ptrToJS(options, func(e KvWatchOptions) js.Value { return e.toJS() }))
	return x.instance.Call("watch", args...)
}

// Close the database connection. This will prevent any further operations
// from being performed on the database, and interrupt any in-flight
// operations immediately.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) Close() {
	x.instance.Call("close")
}

// Get a symbol that represents the versionstamp of the current atomic
// operation. This symbol can be used as the last part of a key in
// `.set()`, both directly on the `Kv` object and on an `AtomicOperation`
// object created from this `Kv` instance.
//   - https://docs.deno.com/api/deno/~/Deno.Kv
func (x *Kv) CommitVersionstamp() js.Value {
	return x.instance.Call("commitVersionstamp")
}

// **UNSTABLE**: New API, yet to be vetted.
//
// Wrapper type for 64-bit unsigned integers for use as values in a
// {@linkcode Deno.Kv}.
//   - https://docs.deno.com/api/deno/~/Deno.KvU64
type KvU64 struct {
	instance js.Value
}

func kvU64FromJS(v js.Value) *KvU64 {
	if isNullish(v) {
		return nil
	}
	return &KvU64{instance: v}
}

func (x *KvU64) toJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.instance
}

// Create a new `KvU64` instance from the given bigint value. If the value
// is signed or greater than 64-bits, an error will be thrown.
//   - https://docs.deno.com/api/deno/~/Deno.KvU64
func NewKvU64(value uint64) *KvU64 {
	return kvU64FromJS(deno.Get("KvU64").New(BigInt(value)))
}

// The value of this unsigned 64-bit integer, represented as a bigint.
//   - https://docs.deno.com/api/deno/~/Deno.KvU64
func (x *KvU64) Value() uint64 {
	return bigIntToUint64(x.instance.Get("value"))
}
