// Code generated by scripts/gen-deno. DO NOT EDIT.

//go:build js && wasm

package deno

import (
	"github.com/syumai/workers-go/internal/jsutil"
	"syscall/js"
)

type Env struct {
	v js.Value
}

func EnvFromJS(v js.Value) *Env {
	if isNullish(v) {
		return nil
	}
	return &Env{v: v}
}

func (x *Env) ToJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.v
}

func (x *Env) Get(key string) *string {
	return ptrFromJS(x.v.Call("get", js.ValueOf(key)), getString)
}

func (x *Env) Set(key string, value string) {
	x.v.Call("set", js.ValueOf(key), js.ValueOf(value))
}

func (x *Env) Delete(key string) {
	x.v.Call("delete", js.ValueOf(key))
}

func (x *Env) Has(key string) bool {
	return getBool(x.v.Call("has", js.ValueOf(key)))
}

func (x *Env) ToObject() map[string]string {
	return jsutil.StrRecordToMap(x.v.Call("toObject"))
}

type KvListIterator struct {
	v js.Value
}

func KvListIteratorFromJS(v js.Value) *KvListIterator {
	if isNullish(v) {
		return nil
	}
	return &KvListIterator{v: v}
}

func (x *KvListIterator) ToJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.v
}

func (x *KvListIterator) Cursor() string {
	return getString(x.v.Get("cursor"))
}

func (x *KvListIterator) Next() (js.Value, error) {
	v, err := awaitResult(x.v.Call("next"))
	if err != nil {
		return js.Value{}, err
	}
	return v, nil
}

type AtomicOperation struct {
	v js.Value
}

func AtomicOperationFromJS(v js.Value) *AtomicOperation {
	if isNullish(v) {
		return nil
	}
	return &AtomicOperation{v: v}
}

func (x *AtomicOperation) ToJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.v
}

func (x *AtomicOperation) Check(checks ...AtomicCheck) *AtomicOperation {
	args := []any{}
	for _, e := range checks {
		args = append(args, e.ToJS())
	}
	x.v.Call("check", args...)
	return x
}

func (x *AtomicOperation) Mutate(mutations ...KvMutation) *AtomicOperation {
	args := []any{}
	for _, e := range mutations {
		args = append(args, e.ToJS())
	}
	x.v.Call("mutate", args...)
	return x
}

func (x *AtomicOperation) Sum(key KvKey, n js.Value) *AtomicOperation {
	x.v.Call("sum", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }), n)
	return x
}

func (x *AtomicOperation) Min(key KvKey, n js.Value) *AtomicOperation {
	x.v.Call("min", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }), n)
	return x
}

func (x *AtomicOperation) Max(key KvKey, n js.Value) *AtomicOperation {
	x.v.Call("max", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }), n)
	return x
}

func (x *AtomicOperation) Set(key KvKey, value any, options *AtomicOperationSetOptions) *AtomicOperation {
	args := []any{}
	args = append(args, sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationSetOptions) js.Value { return e.ToJS() }))
	x.v.Call("set", args...)
	return x
}

func (x *AtomicOperation) Delete(key KvKey) *AtomicOperation {
	x.v.Call("delete", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	return x
}

func (x *AtomicOperation) Enqueue(value any, options *AtomicOperationEnqueueOptions) *AtomicOperation {
	args := []any{}
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationEnqueueOptions) js.Value { return e.ToJS() }))
	x.v.Call("enqueue", args...)
	return x
}

func (x *AtomicOperation) Commit() (AtomicOperationCommitResult, error) {
	v, err := awaitResult(x.v.Call("commit"))
	if err != nil {
		return AtomicOperationCommitResult{}, err
	}
	return AtomicOperationCommitResultFromJS(v), nil
}

type Kv struct {
	v js.Value
}

func KvFromJS(v js.Value) *Kv {
	if isNullish(v) {
		return nil
	}
	return &Kv{v: v}
}

func (x *Kv) ToJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.v
}

func (x *Kv) Get(key KvKey, options *KvGetOptions) (KvEntryMaybe, error) {
	args := []any{}
	args = append(args, sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	args = append(args, ptrToJS(options, func(e KvGetOptions) js.Value { return e.ToJS() }))
	v, err := awaitResult(x.v.Call("get", args...))
	if err != nil {
		return KvEntryMaybe{}, err
	}
	return KvEntryMaybeFromJS(v), nil
}

func (x *Kv) GetMany(keys []KvKey, options *KvGetOptions) ([]KvEntryMaybe, error) {
	args := []any{}
	args = append(args, sliceToJS(keys, func(e KvKey) js.Value { return sliceToJS(e, func(e KvKeyPart) js.Value { return anyToJS(e) }) }))
	args = append(args, ptrToJS(options, func(e KvGetOptions) js.Value { return e.ToJS() }))
	v, err := awaitResult(x.v.Call("getMany", args...))
	if err != nil {
		return nil, err
	}
	return sliceFromJS(v, KvEntryMaybeFromJS), nil
}

func (x *Kv) Set(key KvKey, value any, options *AtomicOperationSetOptions) (KvCommitResult, error) {
	args := []any{}
	args = append(args, sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationSetOptions) js.Value { return e.ToJS() }))
	v, err := awaitResult(x.v.Call("set", args...))
	if err != nil {
		return KvCommitResult{}, err
	}
	return KvCommitResultFromJS(v), nil
}

func (x *Kv) Delete(key KvKey) error {
	_, err := awaitResult(x.v.Call("delete", sliceToJS(key, func(e KvKeyPart) js.Value { return anyToJS(e) })))
	return err
}

func (x *Kv) List(selector KvListSelector, options *KvListOptions) *KvListIterator {
	args := []any{}
	args = append(args, selector.ToJS())
	args = append(args, ptrToJS(options, func(e KvListOptions) js.Value { return e.ToJS() }))
	return KvListIteratorFromJS(x.v.Call("list", args...))
}

func (x *Kv) Enqueue(value any, options *AtomicOperationEnqueueOptions) (KvCommitResult, error) {
	args := []any{}
	args = append(args, anyToJS(value))
	args = append(args, ptrToJS(options, func(e AtomicOperationEnqueueOptions) js.Value { return e.ToJS() }))
	v, err := awaitResult(x.v.Call("enqueue", args...))
	if err != nil {
		return KvCommitResult{}, err
	}
	return KvCommitResultFromJS(v), nil
}

func (x *Kv) ListenQueue(handler js.Value) error {
	_, err := awaitResult(x.v.Call("listenQueue", handler))
	return err
}

func (x *Kv) Atomic() *AtomicOperation {
	return AtomicOperationFromJS(x.v.Call("atomic"))
}

func (x *Kv) Watch(keys []KvKey, options *KvWatchOptions) js.Value {
	args := []any{}
	args = append(args, sliceToJS(keys, func(e KvKey) js.Value { return sliceToJS(e, func(e KvKeyPart) js.Value { return anyToJS(e) }) }))
	args = append(args, ptrToJS(options, func(e KvWatchOptions) js.Value { return e.ToJS() }))
	return x.v.Call("watch", args...)
}

func (x *Kv) Close() {
	x.v.Call("close")
}

func (x *Kv) CommitVersionstamp() js.Value {
	return x.v.Call("commitVersionstamp")
}

type KvU64 struct {
	v js.Value
}

func KvU64FromJS(v js.Value) *KvU64 {
	if isNullish(v) {
		return nil
	}
	return &KvU64{v: v}
}

func (x *KvU64) ToJS() js.Value {
	if x == nil {
		return js.Undefined()
	}
	return x.v
}

func NewKvU64(value js.Value) *KvU64 {
	return KvU64FromJS(deno.Get("KvU64").New(value))
}

func (x *KvU64) Value() js.Value {
	return x.v.Get("value")
}
