// Code generated by scripts/gen-deno. DO NOT EDIT.

//go:build js && wasm

package deno

import (
	"syscall/js"
)

func GetMemoryUsage() MemoryUsage {
	return MemoryUsageFromJS(deno.Call("memoryUsage"))
}

func Hostname() string {
	return getString(deno.Call("hostname"))
}

func Loadavg() []float64 {
	return sliceFromJS(deno.Call("loadavg"), getFloat)
}

func NetworkInterfaces() []NetworkInterfaceInfo {
	return sliceFromJS(deno.Call("networkInterfaces"), NetworkInterfaceInfoFromJS)
}

func GetSystemMemoryInfo() SystemMemoryInfo {
	return SystemMemoryInfoFromJS(deno.Call("systemMemoryInfo"))
}

func OsRelease() string {
	return getString(deno.Call("osRelease"))
}

func OsUptime() float64 {
	return getFloat(deno.Call("osUptime"))
}

func ExecPath() string {
	return getString(deno.Call("execPath"))
}

func Cwd() string {
	return getString(deno.Call("cwd"))
}

func Uid() *float64 {
	return ptrFromJS(deno.Call("uid"), getFloat)
}

func Gid() *float64 {
	return ptrFromJS(deno.Call("gid"), getFloat)
}

func OpenKv(path ...string) (*Kv, error) {
	args := []any{}
	if len(path) > 0 {
		args = append(args, js.ValueOf(path[0]))
	}
	v, err := awaitResult(deno.Call("openKv", args...))
	if err != nil {
		return nil, err
	}
	return KvFromJS(v), nil
}

func Cron(name string, schedule any, options *CronOptions, handler js.Value) error {
	_, err := awaitResult(deno.Call("cron", js.ValueOf(name), anyToJS(schedule), ptrToJS(options, func(e CronOptions) js.Value { return e.ToJS() }), handler))
	return err
}
