// Code generated by scripts/gen-deno. DO NOT EDIT.

//go:build js && wasm

package deno

import (
	"github.com/syumai/workers-go/internal/jsutil"
	"syscall/js"
)

// **UNSTABLE**: New API, yet to be vetted.
//
// CronScheduleExpression is used as the type of `minute`, `hour`,
// `dayOfMonth`, `month`, and `dayOfWeek` in {@linkcode CronSchedule}.
//   - https://docs.deno.com/api/deno/~/Deno.CronScheduleExpression
type CronScheduleExpression = any

// **UNSTABLE**: New API, yet to be vetted.
//
// A key to be persisted in a {@linkcode Deno.Kv}. A key is a sequence
// of {@linkcode Deno.KvKeyPart}s.
//
// Keys are ordered lexicographically by their parts. The first part is the
// most significant, and the last part is the least significant. The order of
// the parts is determined by both the type and the value of the part. The
// relative significance of the types can be found in documentation for the
// {@linkcode Deno.KvKeyPart} type.
//
// Keys have a maximum size of 2048 bytes serialized. If the size of the key
// exceeds this limit, an error will be thrown on the operation that this key
// was passed to.
//   - https://docs.deno.com/api/deno/~/Deno.KvKey
type KvKey = []KvKeyPart

// **UNSTABLE**: New API, yet to be vetted.
//
// A single part of a {@linkcode Deno.KvKey}. Parts are ordered
// lexicographically, first by their type, and within a given type by their
// value.
//
// The ordering of types is as follows:
//
// 1. `Uint8Array`
// 2. `string`
// 3. `number`
// 4. `bigint`
// 5. `boolean`
//
// Within a given type, the ordering is as follows:
//
//   - `Uint8Array` is ordered by the byte ordering of the array
//   - `string` is ordered by the byte ordering of the UTF-8 encoding of the
//     string
//   - `number` is ordered following this pattern: `-NaN`
//     < `-Infinity` < `-100.0` < `-1.0` < -`0.5` < `-0.0` < `0.0` < `0.5`
//     < `1.0` < `100.0` < `Infinity` < `NaN`
//   - `bigint` is ordered by mathematical ordering, with the largest negative
//     number being the least first value, and the largest positive number
//     being the last value
//   - `boolean` is ordered by `false` < `true`
//
// This means that the part `1.0` (a number) is ordered before the part `2.0`
// (also a number), but is greater than the part `0n` (a bigint), because
// `1.0` is a number and `0n` is a bigint, and type ordering has precedence
// over the ordering of values within a type.
//   - https://docs.deno.com/api/deno/~/Deno.KvKeyPart
type KvKeyPart = any

// **UNSTABLE**: New API, yet to be vetted.
//
// Consistency level of a KV operation.
//
// - `strong` - This operation must be strongly-consistent.
// - `eventual` - Eventually-consistent behavior is allowed.
//   - https://docs.deno.com/api/deno/~/Deno.KvConsistencyLevel
type KvConsistencyLevel = string

const (
	KvConsistencyLevelStrong   KvConsistencyLevel = "strong"
	KvConsistencyLevelEventual KvConsistencyLevel = "eventual"
)

// - https://docs.deno.com/api/deno/~/Deno.MemoryUsage
type MemoryUsage struct {
	// The number of bytes of the current Deno's process resident set size,
	// which is the amount of memory occupied in main memory (RAM).
	Rss float64
	// The total size of the heap for V8, in bytes.
	HeapTotal float64
	// The amount of the heap used for V8, in bytes.
	HeapUsed float64
	// Memory, in bytes, associated with JavaScript objects outside of the
	// JavaScript isolate.
	External float64
}

func (x MemoryUsage) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("rss", js.ValueOf(x.Rss))
	o.Set("heapTotal", js.ValueOf(x.HeapTotal))
	o.Set("heapUsed", js.ValueOf(x.HeapUsed))
	o.Set("external", js.ValueOf(x.External))
	return o
}

func memoryUsageFromJS(v js.Value) MemoryUsage {
	var x MemoryUsage
	if isNullish(v) {
		return x
	}
	x.Rss = getFloat(v.Get("rss"))
	x.HeapTotal = getFloat(v.Get("heapTotal"))
	x.HeapUsed = getFloat(v.Get("heapUsed"))
	x.External = getFloat(v.Get("external"))
	return x
}

// The information for a network interface returned from a call to
// {@linkcode Deno.networkInterfaces}.
//   - https://docs.deno.com/api/deno/~/Deno.NetworkInterfaceInfo
type NetworkInterfaceInfo struct {
	// The network interface name.
	Name string
	// The IP protocol version.
	Family string
	// The IP address bound to the interface.
	Address string
	// The netmask applied to the interface.
	Netmask string
	// The IPv6 scope id or `null`.
	Scopeid *float64
	// The CIDR range.
	Cidr string
	// The MAC address.
	Mac string
}

func (x NetworkInterfaceInfo) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("name", js.ValueOf(x.Name))
	o.Set("family", js.ValueOf(x.Family))
	o.Set("address", js.ValueOf(x.Address))
	o.Set("netmask", js.ValueOf(x.Netmask))
	if x.Scopeid == nil {
		o.Set("scopeid", js.Null())
	} else {
		o.Set("scopeid", ptrToJS(x.Scopeid, func(e float64) js.Value { return js.ValueOf(e) }))
	}
	o.Set("cidr", js.ValueOf(x.Cidr))
	o.Set("mac", js.ValueOf(x.Mac))
	return o
}

func networkInterfaceInfoFromJS(v js.Value) NetworkInterfaceInfo {
	var x NetworkInterfaceInfo
	if isNullish(v) {
		return x
	}
	x.Name = getString(v.Get("name"))
	x.Family = getString(v.Get("family"))
	x.Address = getString(v.Get("address"))
	x.Netmask = getString(v.Get("netmask"))
	x.Scopeid = ptrFromJS(v.Get("scopeid"), getFloat)
	x.Cidr = getString(v.Get("cidr"))
	x.Mac = getString(v.Get("mac"))
	return x
}

// Information returned from a call to {@linkcode Deno.systemMemoryInfo}.
//   - https://docs.deno.com/api/deno/~/Deno.SystemMemoryInfo
type SystemMemoryInfo struct {
	// Total installed memory in bytes.
	Total float64
	// Unused memory in bytes.
	Free float64
	// Estimation of how much memory, in bytes, is available for starting new
	// applications, without swapping. Unlike the data provided by the cache or
	// free fields, this field takes into account page cache and also that not
	// all reclaimable memory will be reclaimed due to items being in use.
	Available float64
	// Memory used by kernel buffers.
	Buffers float64
	// Memory used by the page cache and slabs.
	Cached float64
	// Total swap memory.
	SwapTotal float64
	// Unused swap memory.
	SwapFree float64
}

func (x SystemMemoryInfo) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("total", js.ValueOf(x.Total))
	o.Set("free", js.ValueOf(x.Free))
	o.Set("available", js.ValueOf(x.Available))
	o.Set("buffers", js.ValueOf(x.Buffers))
	o.Set("cached", js.ValueOf(x.Cached))
	o.Set("swapTotal", js.ValueOf(x.SwapTotal))
	o.Set("swapFree", js.ValueOf(x.SwapFree))
	return o
}

func systemMemoryInfoFromJS(v js.Value) SystemMemoryInfo {
	var x SystemMemoryInfo
	if isNullish(v) {
		return x
	}
	x.Total = getFloat(v.Get("total"))
	x.Free = getFloat(v.Get("free"))
	x.Available = getFloat(v.Get("available"))
	x.Buffers = getFloat(v.Get("buffers"))
	x.Cached = getFloat(v.Get("cached"))
	x.SwapTotal = getFloat(v.Get("swapTotal"))
	x.SwapFree = getFloat(v.Get("swapFree"))
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// CronSchedule is the interface used for JSON format
// cron `schedule`.
//   - https://docs.deno.com/api/deno/~/Deno.CronSchedule
type CronSchedule struct {
	Minute     CronScheduleExpression
	Hour       CronScheduleExpression
	DayOfMonth CronScheduleExpression
	Month      CronScheduleExpression
	DayOfWeek  CronScheduleExpression
}

func (x CronSchedule) toJS() js.Value {
	o := jsutil.NewObject()
	if x.Minute != nil {
		o.Set("minute", anyToJS(x.Minute))
	}
	if x.Hour != nil {
		o.Set("hour", anyToJS(x.Hour))
	}
	if x.DayOfMonth != nil {
		o.Set("dayOfMonth", anyToJS(x.DayOfMonth))
	}
	if x.Month != nil {
		o.Set("month", anyToJS(x.Month))
	}
	if x.DayOfWeek != nil {
		o.Set("dayOfWeek", anyToJS(x.DayOfWeek))
	}
	return o
}

func cronScheduleFromJS(v js.Value) CronSchedule {
	var x CronSchedule
	if isNullish(v) {
		return x
	}
	x.Minute = CronScheduleExpression(jsToAny(v.Get("minute")))
	x.Hour = CronScheduleExpression(jsToAny(v.Get("hour")))
	x.DayOfMonth = CronScheduleExpression(jsToAny(v.Get("dayOfMonth")))
	x.Month = CronScheduleExpression(jsToAny(v.Get("month")))
	x.DayOfWeek = CronScheduleExpression(jsToAny(v.Get("dayOfWeek")))
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// A selector that selects the range of data returned by a list operation on a
// {@linkcode Deno.Kv}.
//
// The selector can either be a prefix selector or a range selector. A prefix
// selector selects all keys that start with the given prefix (optionally
// starting at a given key). A range selector selects all keys that are
// lexicographically between the given start and end keys.
//   - https://docs.deno.com/api/deno/~/Deno.KvListSelector
type KvListSelector struct {
	Prefix KvKey
	Start  KvKey
	End    KvKey
}

func (x KvListSelector) toJS() js.Value {
	o := jsutil.NewObject()
	if x.Prefix != nil {
		o.Set("prefix", sliceToJS(x.Prefix, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	}
	if x.Start != nil {
		o.Set("start", sliceToJS(x.Start, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	}
	if x.End != nil {
		o.Set("end", sliceToJS(x.End, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	}
	return o
}

func kvListSelectorFromJS(v js.Value) KvListSelector {
	var x KvListSelector
	if isNullish(v) {
		return x
	}
	x.Prefix = KvKey(sliceFromJS(v.Get("prefix"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Start = KvKey(sliceFromJS(v.Get("start"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.End = KvKey(sliceFromJS(v.Get("end"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// A mutation to a key in a {@linkcode Deno.Kv}. A mutation is a
// combination of a key, a value, and a type. The type determines how the
// mutation is applied to the key.
//
//   - `set` - Sets the value of the key to the given value, overwriting any
//     existing value. Optionally an `expireIn` option can be specified to
//     set a time-to-live (TTL) for the key. The TTL is specified in
//     milliseconds, and the key will be deleted from the database at earliest
//     after the specified number of milliseconds have elapsed. Once the
//     specified duration has passed, the key may still be visible for some
//     additional time. If the `expireIn` option is not specified, the key will
//     not expire.
//   - `delete` - Deletes the key from the database. The mutation is a no-op if
//     the key does not exist.
//   - `sum` - Adds the given value to the existing value of the key. Both the
//     value specified in the mutation, and any existing value must be of type
//     `Deno.KvU64`. If the key does not exist, the value is set to the given
//     value (summed with 0). If the result of the sum overflows an unsigned
//     64-bit integer, the result is wrapped around.
//   - `max` - Sets the value of the key to the maximum of the existing value
//     and the given value. Both the value specified in the mutation, and any
//     existing value must be of type `Deno.KvU64`. If the key does not exist,
//     the value is set to the given value.
//   - `min` - Sets the value of the key to the minimum of the existing value
//     and the given value. Both the value specified in the mutation, and any
//     existing value must be of type `Deno.KvU64`. If the key does not exist,
//     the value is set to the given value.
//   - https://docs.deno.com/api/deno/~/Deno.KvMutation
type KvMutation struct {
	Key      KvKey
	Type     string
	Value    any
	ExpireIn *float64
}

func (x KvMutation) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	o.Set("type", js.ValueOf(x.Type))
	if x.Value != nil {
		o.Set("value", anyToJS(x.Value))
	}
	if x.ExpireIn != nil {
		o.Set("expireIn", js.ValueOf(*x.ExpireIn))
	}
	return o
}

func kvMutationFromJS(v js.Value) KvMutation {
	var x KvMutation
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Type = getString(v.Get("type"))
	x.Value = jsToAny(v.Get("value"))
	x.ExpireIn = ptrFromJS(v.Get("expireIn"), getFloat)
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// A versioned pair of key and value in a {@linkcode Deno.Kv}.
//
// The `versionstamp` is a string that represents the current version of the
// key-value pair. It can be used to perform atomic operations on the KV store
// by passing it to the `check` method of a {@linkcode Deno.AtomicOperation}.
//   - https://docs.deno.com/api/deno/~/Deno.KvEntry
type KvEntry struct {
	Key          KvKey
	Value        any
	Versionstamp string
}

func (x KvEntry) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	o.Set("value", anyToJS(x.Value))
	o.Set("versionstamp", js.ValueOf(x.Versionstamp))
	return o
}

func kvEntryFromJS(v js.Value) KvEntry {
	var x KvEntry
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Value = jsToAny(v.Get("value"))
	x.Versionstamp = getString(v.Get("versionstamp"))
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// An optional versioned pair of key and value in a {@linkcode Deno.Kv}.
//
// This is the same as a {@linkcode KvEntry}, but the `value` and `versionstamp`
// fields may be `null` if no value exists for the given key in the KV store.
//   - https://docs.deno.com/api/deno/~/Deno.KvEntryMaybe
type KvEntryMaybe struct {
	Key          KvKey
	Value        any
	Versionstamp *string
}

func (x KvEntryMaybe) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	o.Set("value", anyToJS(x.Value))
	if x.Versionstamp == nil {
		o.Set("versionstamp", js.Null())
	} else {
		o.Set("versionstamp", ptrToJS(x.Versionstamp, func(e string) js.Value { return js.ValueOf(e) }))
	}
	return o
}

func kvEntryMaybeFromJS(v js.Value) KvEntryMaybe {
	var x KvEntryMaybe
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Value = jsToAny(v.Get("value"))
	x.Versionstamp = ptrFromJS(v.Get("versionstamp"), getString)
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// Options for listing key-value pairs in a {@linkcode Deno.Kv}.
//   - https://docs.deno.com/api/deno/~/Deno.KvListOptions
type KvListOptions struct {
	// The maximum number of key-value pairs to return. If not specified, all
	// matching key-value pairs will be returned.
	Limit *float64
	// The cursor to resume the iteration from. If not specified, the iteration
	// will start from the beginning.
	Cursor *string
	// Whether to reverse the order of the returned key-value pairs. If not
	// specified, the order will be ascending from the start of the range as per
	// the lexicographical ordering of the keys. If `true`, the order will be
	// descending from the end of the range.
	//
	// The default value is `false`.
	Reverse *bool
	// The consistency level of the list operation. The default consistency
	// level is "strong". Some use cases can benefit from using a weaker
	// consistency level. For more information on consistency levels, see the
	// documentation for {@linkcode Deno.KvConsistencyLevel}.
	//
	// List operations are performed in batches (in sizes specified by the
	// `batchSize` option). The consistency level of the list operation is
	// applied to each batch individually. This means that while each batch is
	// guaranteed to be consistent within itself, the entire list operation may
	// not be consistent across batches because a mutation may be applied to a
	// key-value pair between batches, in a batch that has already been returned
	// by the list operation.
	Consistency *KvConsistencyLevel
	// The size of the batches in which the list operation is performed. Larger
	// or smaller batch sizes may positively or negatively affect the
	// performance of a list operation depending on the specific use case and
	// iteration behavior. Slow iterating queries may benefit from using a
	// smaller batch size for increased overall consistency, while fast
	// iterating queries may benefit from using a larger batch size for better
	// performance.
	//
	// The default batch size is equal to the `limit` option, or 100 if this is
	// unset. The maximum value for this option is 500. Larger values will be
	// clamped.
	BatchSize *float64
}

func (x KvListOptions) toJS() js.Value {
	o := jsutil.NewObject()
	if x.Limit != nil {
		o.Set("limit", js.ValueOf(*x.Limit))
	}
	if x.Cursor != nil {
		o.Set("cursor", js.ValueOf(*x.Cursor))
	}
	if x.Reverse != nil {
		o.Set("reverse", js.ValueOf(*x.Reverse))
	}
	if x.Consistency != nil {
		o.Set("consistency", js.ValueOf(string(*x.Consistency)))
	}
	if x.BatchSize != nil {
		o.Set("batchSize", js.ValueOf(*x.BatchSize))
	}
	return o
}

func kvListOptionsFromJS(v js.Value) KvListOptions {
	var x KvListOptions
	if isNullish(v) {
		return x
	}
	x.Limit = ptrFromJS(v.Get("limit"), getFloat)
	x.Cursor = ptrFromJS(v.Get("cursor"), getString)
	x.Reverse = ptrFromJS(v.Get("reverse"), getBool)
	x.Consistency = ptrFromJS(v.Get("consistency"), func(e js.Value) KvConsistencyLevel { return KvConsistencyLevel(getString(e)) })
	x.BatchSize = ptrFromJS(v.Get("batchSize"), getFloat)
	return x
}

// - https://docs.deno.com/api/deno/~/Deno.KvCommitResult
type KvCommitResult struct {
	Ok bool
	// The versionstamp of the value committed to KV.
	Versionstamp string
}

func (x KvCommitResult) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("ok", js.ValueOf(x.Ok))
	o.Set("versionstamp", js.ValueOf(x.Versionstamp))
	return o
}

func kvCommitResultFromJS(v js.Value) KvCommitResult {
	var x KvCommitResult
	if isNullish(v) {
		return x
	}
	x.Ok = getBool(v.Get("ok"))
	x.Versionstamp = getString(v.Get("versionstamp"))
	return x
}

// - https://docs.deno.com/api/deno/~/Deno.KvCommitError
type KvCommitError struct {
	Ok bool
}

func (x KvCommitError) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("ok", js.ValueOf(x.Ok))
	return o
}

func kvCommitErrorFromJS(v js.Value) KvCommitError {
	var x KvCommitError
	if isNullish(v) {
		return x
	}
	x.Ok = getBool(v.Get("ok"))
	return x
}

// **UNSTABLE**: New API, yet to be vetted.
//
// A check to perform as part of a {@linkcode Deno.AtomicOperation}. The check
// will fail if the versionstamp for the key-value pair in the KV store does
// not match the given versionstamp. A check with a `null` versionstamp checks
// that the key-value pair does not currently exist in the KV store.
//   - https://docs.deno.com/api/deno/~/Deno.AtomicCheck
type AtomicCheck struct {
	Key          KvKey
	Versionstamp *string
}

func (x AtomicCheck) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	if x.Versionstamp == nil {
		o.Set("versionstamp", js.Null())
	} else {
		o.Set("versionstamp", ptrToJS(x.Versionstamp, func(e string) js.Value { return js.ValueOf(e) }))
	}
	return o
}

func atomicCheckFromJS(v js.Value) AtomicCheck {
	var x AtomicCheck
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Versionstamp = ptrFromJS(v.Get("versionstamp"), getString)
	return x
}

type Version struct {
	// Deno CLI's version. For example: `"1.26.0"`.
	Deno string
	// The V8 version used by Deno. For example: `"10.7.100.0"`.
	//
	// V8 is the underlying JavaScript runtime platform that Deno is built on
	// top of.
	V8 string
	// The TypeScript version used by Deno. For example: `"4.8.3"`.
	//
	// A version of the TypeScript type checker and language server is built-in
	// to the Deno CLI.
	Typescript string
}

func (x Version) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("deno", js.ValueOf(x.Deno))
	o.Set("v8", js.ValueOf(x.V8))
	o.Set("typescript", js.ValueOf(x.Typescript))
	return o
}

func versionFromJS(v js.Value) Version {
	var x Version
	if isNullish(v) {
		return x
	}
	x.Deno = getString(v.Get("deno"))
	x.V8 = getString(v.Get("v8"))
	x.Typescript = getString(v.Get("typescript"))
	return x
}

type CronOptions struct {
	BackoffSchedule []float64
	Signal          js.Value
}

func (x CronOptions) toJS() js.Value {
	o := jsutil.NewObject()
	if x.BackoffSchedule != nil {
		o.Set("backoffSchedule", sliceToJS(x.BackoffSchedule, func(e float64) js.Value { return js.ValueOf(e) }))
	}
	if x.Signal.Truthy() {
		o.Set("signal", x.Signal)
	}
	return o
}

func cronOptionsFromJS(v js.Value) CronOptions {
	var x CronOptions
	if isNullish(v) {
		return x
	}
	x.BackoffSchedule = sliceFromJS(v.Get("backoffSchedule"), getFloat)
	x.Signal = v.Get("signal")
	return x
}

type AtomicOperationSetOptions struct {
	ExpireIn *float64
}

func (x AtomicOperationSetOptions) toJS() js.Value {
	o := jsutil.NewObject()
	if x.ExpireIn != nil {
		o.Set("expireIn", js.ValueOf(*x.ExpireIn))
	}
	return o
}

func atomicOperationSetOptionsFromJS(v js.Value) AtomicOperationSetOptions {
	var x AtomicOperationSetOptions
	if isNullish(v) {
		return x
	}
	x.ExpireIn = ptrFromJS(v.Get("expireIn"), getFloat)
	return x
}

type AtomicOperationEnqueueOptions struct {
	Delay             *float64
	KeysIfUndelivered []KvKey
	BackoffSchedule   []float64
}

func (x AtomicOperationEnqueueOptions) toJS() js.Value {
	o := jsutil.NewObject()
	if x.Delay != nil {
		o.Set("delay", js.ValueOf(*x.Delay))
	}
	if x.KeysIfUndelivered != nil {
		o.Set("keysIfUndelivered", sliceToJS(x.KeysIfUndelivered, func(e KvKey) js.Value { return sliceToJS(e, func(e KvKeyPart) js.Value { return anyToJS(e) }) }))
	}
	if x.BackoffSchedule != nil {
		o.Set("backoffSchedule", sliceToJS(x.BackoffSchedule, func(e float64) js.Value { return js.ValueOf(e) }))
	}
	return o
}

func atomicOperationEnqueueOptionsFromJS(v js.Value) AtomicOperationEnqueueOptions {
	var x AtomicOperationEnqueueOptions
	if isNullish(v) {
		return x
	}
	x.Delay = ptrFromJS(v.Get("delay"), getFloat)
	x.KeysIfUndelivered = sliceFromJS(v.Get("keysIfUndelivered"), func(e js.Value) KvKey {
		return KvKey(sliceFromJS(e, func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	})
	x.BackoffSchedule = sliceFromJS(v.Get("backoffSchedule"), getFloat)
	return x
}

type AtomicOperationCommitResult struct {
	Ok bool
	// The versionstamp of the value committed to KV.
	Versionstamp *string
}

func (x AtomicOperationCommitResult) toJS() js.Value {
	o := jsutil.NewObject()
	o.Set("ok", js.ValueOf(x.Ok))
	if x.Versionstamp != nil {
		o.Set("versionstamp", js.ValueOf(*x.Versionstamp))
	}
	return o
}

func atomicOperationCommitResultFromJS(v js.Value) AtomicOperationCommitResult {
	var x AtomicOperationCommitResult
	if isNullish(v) {
		return x
	}
	x.Ok = getBool(v.Get("ok"))
	x.Versionstamp = ptrFromJS(v.Get("versionstamp"), getString)
	return x
}

type KvGetOptions struct {
	Consistency *KvConsistencyLevel
}

func (x KvGetOptions) toJS() js.Value {
	o := jsutil.NewObject()
	if x.Consistency != nil {
		o.Set("consistency", js.ValueOf(string(*x.Consistency)))
	}
	return o
}

func kvGetOptionsFromJS(v js.Value) KvGetOptions {
	var x KvGetOptions
	if isNullish(v) {
		return x
	}
	x.Consistency = ptrFromJS(v.Get("consistency"), func(e js.Value) KvConsistencyLevel { return KvConsistencyLevel(getString(e)) })
	return x
}

type KvWatchOptions struct {
	Raw *bool
}

func (x KvWatchOptions) toJS() js.Value {
	o := jsutil.NewObject()
	if x.Raw != nil {
		o.Set("raw", js.ValueOf(*x.Raw))
	}
	return o
}

func kvWatchOptionsFromJS(v js.Value) KvWatchOptions {
	var x KvWatchOptions
	if isNullish(v) {
		return x
	}
	x.Raw = ptrFromJS(v.Get("raw"), getBool)
	return x
}
