// Code generated by scripts/gen-deno. DO NOT EDIT.

//go:build js && wasm

package deno

import (
	"github.com/syumai/workers-go/internal/jsutil"
	"syscall/js"
)

type CronScheduleExpression = any

type KvKey = []KvKeyPart

type KvKeyPart = any

type KvConsistencyLevel = string

const (
	KvConsistencyLevelStrong   KvConsistencyLevel = "strong"
	KvConsistencyLevelEventual KvConsistencyLevel = "eventual"
)

type MemoryUsage struct {
	Rss       float64
	HeapTotal float64
	HeapUsed  float64
	External  float64
}

func (x MemoryUsage) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("rss", js.ValueOf(x.Rss))
	o.Set("heapTotal", js.ValueOf(x.HeapTotal))
	o.Set("heapUsed", js.ValueOf(x.HeapUsed))
	o.Set("external", js.ValueOf(x.External))
	return o
}

func MemoryUsageFromJS(v js.Value) MemoryUsage {
	var x MemoryUsage
	if isNullish(v) {
		return x
	}
	x.Rss = getFloat(v.Get("rss"))
	x.HeapTotal = getFloat(v.Get("heapTotal"))
	x.HeapUsed = getFloat(v.Get("heapUsed"))
	x.External = getFloat(v.Get("external"))
	return x
}

type NetworkInterfaceInfo struct {
	Name    string
	Family  string
	Address string
	Netmask string
	Scopeid *float64
	Cidr    string
	Mac     string
}

func (x NetworkInterfaceInfo) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("name", js.ValueOf(x.Name))
	o.Set("family", js.ValueOf(x.Family))
	o.Set("address", js.ValueOf(x.Address))
	o.Set("netmask", js.ValueOf(x.Netmask))
	if x.Scopeid == nil {
		o.Set("scopeid", js.Null())
	} else {
		o.Set("scopeid", ptrToJS(x.Scopeid, func(e float64) js.Value { return js.ValueOf(e) }))
	}
	o.Set("cidr", js.ValueOf(x.Cidr))
	o.Set("mac", js.ValueOf(x.Mac))
	return o
}

func NetworkInterfaceInfoFromJS(v js.Value) NetworkInterfaceInfo {
	var x NetworkInterfaceInfo
	if isNullish(v) {
		return x
	}
	x.Name = getString(v.Get("name"))
	x.Family = getString(v.Get("family"))
	x.Address = getString(v.Get("address"))
	x.Netmask = getString(v.Get("netmask"))
	x.Scopeid = ptrFromJS(v.Get("scopeid"), getFloat)
	x.Cidr = getString(v.Get("cidr"))
	x.Mac = getString(v.Get("mac"))
	return x
}

type SystemMemoryInfo struct {
	Total     float64
	Free      float64
	Available float64
	Buffers   float64
	Cached    float64
	SwapTotal float64
	SwapFree  float64
}

func (x SystemMemoryInfo) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("total", js.ValueOf(x.Total))
	o.Set("free", js.ValueOf(x.Free))
	o.Set("available", js.ValueOf(x.Available))
	o.Set("buffers", js.ValueOf(x.Buffers))
	o.Set("cached", js.ValueOf(x.Cached))
	o.Set("swapTotal", js.ValueOf(x.SwapTotal))
	o.Set("swapFree", js.ValueOf(x.SwapFree))
	return o
}

func SystemMemoryInfoFromJS(v js.Value) SystemMemoryInfo {
	var x SystemMemoryInfo
	if isNullish(v) {
		return x
	}
	x.Total = getFloat(v.Get("total"))
	x.Free = getFloat(v.Get("free"))
	x.Available = getFloat(v.Get("available"))
	x.Buffers = getFloat(v.Get("buffers"))
	x.Cached = getFloat(v.Get("cached"))
	x.SwapTotal = getFloat(v.Get("swapTotal"))
	x.SwapFree = getFloat(v.Get("swapFree"))
	return x
}

type CronSchedule struct {
	Minute     CronScheduleExpression
	Hour       CronScheduleExpression
	DayOfMonth CronScheduleExpression
	Month      CronScheduleExpression
	DayOfWeek  CronScheduleExpression
}

func (x CronSchedule) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.Minute != nil {
		o.Set("minute", anyToJS(x.Minute))
	}
	if x.Hour != nil {
		o.Set("hour", anyToJS(x.Hour))
	}
	if x.DayOfMonth != nil {
		o.Set("dayOfMonth", anyToJS(x.DayOfMonth))
	}
	if x.Month != nil {
		o.Set("month", anyToJS(x.Month))
	}
	if x.DayOfWeek != nil {
		o.Set("dayOfWeek", anyToJS(x.DayOfWeek))
	}
	return o
}

func CronScheduleFromJS(v js.Value) CronSchedule {
	var x CronSchedule
	if isNullish(v) {
		return x
	}
	x.Minute = CronScheduleExpression(jsToAny(v.Get("minute")))
	x.Hour = CronScheduleExpression(jsToAny(v.Get("hour")))
	x.DayOfMonth = CronScheduleExpression(jsToAny(v.Get("dayOfMonth")))
	x.Month = CronScheduleExpression(jsToAny(v.Get("month")))
	x.DayOfWeek = CronScheduleExpression(jsToAny(v.Get("dayOfWeek")))
	return x
}

type KvListSelector struct {
	Prefix KvKey
	Start  KvKey
	End    KvKey
}

func (x KvListSelector) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.Prefix != nil {
		o.Set("prefix", sliceToJS(x.Prefix, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	}
	if x.Start != nil {
		o.Set("start", sliceToJS(x.Start, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	}
	if x.End != nil {
		o.Set("end", sliceToJS(x.End, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	}
	return o
}

func KvListSelectorFromJS(v js.Value) KvListSelector {
	var x KvListSelector
	if isNullish(v) {
		return x
	}
	x.Prefix = KvKey(sliceFromJS(v.Get("prefix"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Start = KvKey(sliceFromJS(v.Get("start"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.End = KvKey(sliceFromJS(v.Get("end"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	return x
}

type KvMutation struct {
	Key      KvKey
	Type     string
	Value    any
	ExpireIn *float64
}

func (x KvMutation) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	o.Set("type", js.ValueOf(x.Type))
	if x.Value != nil {
		o.Set("value", anyToJS(x.Value))
	}
	if x.ExpireIn != nil {
		o.Set("expireIn", js.ValueOf(*x.ExpireIn))
	}
	return o
}

func KvMutationFromJS(v js.Value) KvMutation {
	var x KvMutation
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Type = getString(v.Get("type"))
	x.Value = jsToAny(v.Get("value"))
	x.ExpireIn = ptrFromJS(v.Get("expireIn"), getFloat)
	return x
}

type KvEntry struct {
	Key          KvKey
	Value        any
	Versionstamp string
}

func (x KvEntry) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	o.Set("value", anyToJS(x.Value))
	o.Set("versionstamp", js.ValueOf(x.Versionstamp))
	return o
}

func KvEntryFromJS(v js.Value) KvEntry {
	var x KvEntry
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Value = jsToAny(v.Get("value"))
	x.Versionstamp = getString(v.Get("versionstamp"))
	return x
}

type KvEntryMaybe struct {
	Key          KvKey
	Value        any
	Versionstamp *string
}

func (x KvEntryMaybe) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	o.Set("value", anyToJS(x.Value))
	if x.Versionstamp == nil {
		o.Set("versionstamp", js.Null())
	} else {
		o.Set("versionstamp", ptrToJS(x.Versionstamp, func(e string) js.Value { return js.ValueOf(e) }))
	}
	return o
}

func KvEntryMaybeFromJS(v js.Value) KvEntryMaybe {
	var x KvEntryMaybe
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Value = jsToAny(v.Get("value"))
	x.Versionstamp = ptrFromJS(v.Get("versionstamp"), getString)
	return x
}

type KvListOptions struct {
	Limit       *float64
	Cursor      *string
	Reverse     *bool
	Consistency *KvConsistencyLevel
	BatchSize   *float64
}

func (x KvListOptions) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.Limit != nil {
		o.Set("limit", js.ValueOf(*x.Limit))
	}
	if x.Cursor != nil {
		o.Set("cursor", js.ValueOf(*x.Cursor))
	}
	if x.Reverse != nil {
		o.Set("reverse", js.ValueOf(*x.Reverse))
	}
	if x.Consistency != nil {
		o.Set("consistency", js.ValueOf(string(*x.Consistency)))
	}
	if x.BatchSize != nil {
		o.Set("batchSize", js.ValueOf(*x.BatchSize))
	}
	return o
}

func KvListOptionsFromJS(v js.Value) KvListOptions {
	var x KvListOptions
	if isNullish(v) {
		return x
	}
	x.Limit = ptrFromJS(v.Get("limit"), getFloat)
	x.Cursor = ptrFromJS(v.Get("cursor"), getString)
	x.Reverse = ptrFromJS(v.Get("reverse"), getBool)
	x.Consistency = ptrFromJS(v.Get("consistency"), func(e js.Value) KvConsistencyLevel { return KvConsistencyLevel(getString(e)) })
	x.BatchSize = ptrFromJS(v.Get("batchSize"), getFloat)
	return x
}

type KvCommitResult struct {
	Ok           bool
	Versionstamp string
}

func (x KvCommitResult) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("ok", js.ValueOf(x.Ok))
	o.Set("versionstamp", js.ValueOf(x.Versionstamp))
	return o
}

func KvCommitResultFromJS(v js.Value) KvCommitResult {
	var x KvCommitResult
	if isNullish(v) {
		return x
	}
	x.Ok = getBool(v.Get("ok"))
	x.Versionstamp = getString(v.Get("versionstamp"))
	return x
}

type KvCommitError struct {
	Ok bool
}

func (x KvCommitError) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("ok", js.ValueOf(x.Ok))
	return o
}

func KvCommitErrorFromJS(v js.Value) KvCommitError {
	var x KvCommitError
	if isNullish(v) {
		return x
	}
	x.Ok = getBool(v.Get("ok"))
	return x
}

type AtomicCheck struct {
	Key          KvKey
	Versionstamp *string
}

func (x AtomicCheck) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("key", sliceToJS(x.Key, func(e KvKeyPart) js.Value { return anyToJS(e) }))
	if x.Versionstamp == nil {
		o.Set("versionstamp", js.Null())
	} else {
		o.Set("versionstamp", ptrToJS(x.Versionstamp, func(e string) js.Value { return js.ValueOf(e) }))
	}
	return o
}

func AtomicCheckFromJS(v js.Value) AtomicCheck {
	var x AtomicCheck
	if isNullish(v) {
		return x
	}
	x.Key = KvKey(sliceFromJS(v.Get("key"), func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	x.Versionstamp = ptrFromJS(v.Get("versionstamp"), getString)
	return x
}

type Version struct {
	Deno       string
	V8         string
	Typescript string
}

func (x Version) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("deno", js.ValueOf(x.Deno))
	o.Set("v8", js.ValueOf(x.V8))
	o.Set("typescript", js.ValueOf(x.Typescript))
	return o
}

func VersionFromJS(v js.Value) Version {
	var x Version
	if isNullish(v) {
		return x
	}
	x.Deno = getString(v.Get("deno"))
	x.V8 = getString(v.Get("v8"))
	x.Typescript = getString(v.Get("typescript"))
	return x
}

type CronOptions struct {
	BackoffSchedule []float64
	Signal          js.Value
}

func (x CronOptions) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.BackoffSchedule != nil {
		o.Set("backoffSchedule", sliceToJS(x.BackoffSchedule, func(e float64) js.Value { return js.ValueOf(e) }))
	}
	if x.Signal.Truthy() {
		o.Set("signal", x.Signal)
	}
	return o
}

func CronOptionsFromJS(v js.Value) CronOptions {
	var x CronOptions
	if isNullish(v) {
		return x
	}
	x.BackoffSchedule = sliceFromJS(v.Get("backoffSchedule"), getFloat)
	x.Signal = v.Get("signal")
	return x
}

type AtomicOperationSetOptions struct {
	ExpireIn *float64
}

func (x AtomicOperationSetOptions) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.ExpireIn != nil {
		o.Set("expireIn", js.ValueOf(*x.ExpireIn))
	}
	return o
}

func AtomicOperationSetOptionsFromJS(v js.Value) AtomicOperationSetOptions {
	var x AtomicOperationSetOptions
	if isNullish(v) {
		return x
	}
	x.ExpireIn = ptrFromJS(v.Get("expireIn"), getFloat)
	return x
}

type AtomicOperationEnqueueOptions struct {
	Delay             *float64
	KeysIfUndelivered []KvKey
	BackoffSchedule   []float64
}

func (x AtomicOperationEnqueueOptions) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.Delay != nil {
		o.Set("delay", js.ValueOf(*x.Delay))
	}
	if x.KeysIfUndelivered != nil {
		o.Set("keysIfUndelivered", sliceToJS(x.KeysIfUndelivered, func(e KvKey) js.Value { return sliceToJS(e, func(e KvKeyPart) js.Value { return anyToJS(e) }) }))
	}
	if x.BackoffSchedule != nil {
		o.Set("backoffSchedule", sliceToJS(x.BackoffSchedule, func(e float64) js.Value { return js.ValueOf(e) }))
	}
	return o
}

func AtomicOperationEnqueueOptionsFromJS(v js.Value) AtomicOperationEnqueueOptions {
	var x AtomicOperationEnqueueOptions
	if isNullish(v) {
		return x
	}
	x.Delay = ptrFromJS(v.Get("delay"), getFloat)
	x.KeysIfUndelivered = sliceFromJS(v.Get("keysIfUndelivered"), func(e js.Value) KvKey {
		return KvKey(sliceFromJS(e, func(e js.Value) KvKeyPart { return KvKeyPart(jsToAny(e)) }))
	})
	x.BackoffSchedule = sliceFromJS(v.Get("backoffSchedule"), getFloat)
	return x
}

type AtomicOperationCommitResult struct {
	Ok           bool
	Versionstamp *string
}

func (x AtomicOperationCommitResult) ToJS() js.Value {
	o := jsutil.NewObject()
	o.Set("ok", js.ValueOf(x.Ok))
	if x.Versionstamp != nil {
		o.Set("versionstamp", js.ValueOf(*x.Versionstamp))
	}
	return o
}

func AtomicOperationCommitResultFromJS(v js.Value) AtomicOperationCommitResult {
	var x AtomicOperationCommitResult
	if isNullish(v) {
		return x
	}
	x.Ok = getBool(v.Get("ok"))
	x.Versionstamp = ptrFromJS(v.Get("versionstamp"), getString)
	return x
}

type KvGetOptions struct {
	Consistency *KvConsistencyLevel
}

func (x KvGetOptions) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.Consistency != nil {
		o.Set("consistency", js.ValueOf(string(*x.Consistency)))
	}
	return o
}

func KvGetOptionsFromJS(v js.Value) KvGetOptions {
	var x KvGetOptions
	if isNullish(v) {
		return x
	}
	x.Consistency = ptrFromJS(v.Get("consistency"), func(e js.Value) KvConsistencyLevel { return KvConsistencyLevel(getString(e)) })
	return x
}

type KvWatchOptions struct {
	Raw *bool
}

func (x KvWatchOptions) ToJS() js.Value {
	o := jsutil.NewObject()
	if x.Raw != nil {
		o.Set("raw", js.ValueOf(*x.Raw))
	}
	return o
}

func KvWatchOptionsFromJS(v js.Value) KvWatchOptions {
	var x KvWatchOptions
	if isNullish(v) {
		return x
	}
	x.Raw = ptrFromJS(v.Get("raw"), getBool)
	return x
}
