// Code generated by scripts/gen-deno. DO NOT EDIT.

//go:build js && wasm

package deno

func GetPid() float64 {
	return getFloat(deno.Get("pid"))
}

func GetPpid() float64 {
	return getFloat(deno.Get("ppid"))
}

func GetNoColor() bool {
	return getBool(deno.Get("noColor"))
}

func GetEnv() *Env {
	return EnvFromJS(deno.Get("env"))
}

func GetVersion() Version {
	return VersionFromJS(deno.Get("version"))
}

func GetArgs() []string {
	return sliceFromJS(deno.Get("args"), getString)
}

func GetMainModule() string {
	return getString(deno.Get("mainModule"))
}
