// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package dispatch provides the Workers for Platforms dynamic dispatch
// binding (https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/get-started/dynamic-dispatch/):
// DispatchNamespace, DynamicDispatchOptions, and DynamicDispatchLimits.
//
// DispatchNamespace.get returns a Fetcher, which (like Request/Response) has
// no generated Go type of its own — it's left as js.Value, a raw escape
// hatch, by the standard "ref not in include" fallback. dispatch.go's
// hand-written GetClient wraps Get and bridges that js.Value straight into
// cloudflare/fetch.NewClient(fetch.WithBinding(v)), the same way
// exp/cloudflare/hyperdrive.Hyperdrive.Connect bridges a synchronous JS
// return value into another package's Go type.
//
// DispatchNamespace.get's args parameter and DynamicDispatchOptions.outbound
// are both TypeScript index-signature object types ({ [key: string]: any }),
// which cfgen's inline-object synthesis doesn't recognize as a Record-style
// map on its own (unlike a named Record<string, T> ref) — both are
// overridden to map[string]any below, per tmp/06-codegen-spec.md 6.1 item 3.
package dispatch

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// DispatchNamespace
type DispatchNamespace struct{ v js.Value }

// DispatchNamespaceFromJS wraps a JS DispatchNamespace value.
func DispatchNamespaceFromJS(v js.Value) *DispatchNamespace { return &DispatchNamespace{v: v} }

// JSValue returns the underlying JS value.
func (x *DispatchNamespace) JSValue() js.Value { return x.v }

// NewDispatchNamespace resolves the binding named bindingName from env.
func NewDispatchNamespace(bindingName string) (*DispatchNamespace, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &DispatchNamespace{v: v}, nil
}

// Get @param name Name of the Worker script.
// @param args Arguments to Worker script.
// @param options Options for Dynamic Dispatch invocation.
// @returns A Fetcher object that allows you to send requests to the Worker script.
// @throws If the Worker script does not exist in this dispatch namespace, an error will be thrown.
func (x *DispatchNamespace) Get(name string, args map[string]any, options DynamicDispatchOptions) (js.Value, error) {
	var arg1 js.Value
	{
		m := jsrt.NewObject()
		for k, v := range args {
			m.Set(k, v)
		}
		arg1 = m
	}
	r, err := jsrt.Call(x.v, "get", name, arg1, options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// DynamicDispatchOptions
type DynamicDispatchOptions struct {
	// Limit resources of invoked Worker script.
	Limits *DynamicDispatchLimits `js:"limits"`
	// Arguments for outbound Worker script, if configured.
	Outbound map[string]any `js:"outbound"`
}

func dynamicDispatchOptionsFromJS(v js.Value) (DynamicDispatchOptions, error) {
	var out DynamicDispatchOptions
	{
		if !jsrt.IsNil(v.Get("limits")) {
			var val DynamicDispatchLimits
			if tmp, err := dynamicDispatchLimitsFromJS(v.Get("limits")); err != nil {
				return DynamicDispatchOptions{}, err
			} else {
				val = tmp
			}
			out.Limits = &val
		}
	}
	{
		if s := v.Get("outbound"); !s.IsUndefined() && !s.IsNull() {
			out.Outbound = make(map[string]any)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				out.Outbound[k] = s.Get(k)
			}
		}
	}
	return out, nil
}

func (o DynamicDispatchOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Limits != nil {
		obj.Set("limits", (*o.Limits).toJS())
	}
	if len(o.Outbound) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.Outbound {
			m.Set(k, v)
		}
		obj.Set("outbound", m)
	}
	return obj
}

// DynamicDispatchLimits
type DynamicDispatchLimits struct {
	// Limit CPU time in milliseconds.
	CpuMs float64 `js:"cpuMs"`
	// Limit number of subrequests.
	SubRequests float64 `js:"subRequests"`
}

func dynamicDispatchLimitsFromJS(v js.Value) (DynamicDispatchLimits, error) {
	var out DynamicDispatchLimits
	{
		if s := v.Get("cpuMs"); !s.IsUndefined() && !s.IsNull() {
			out.CpuMs = s.Float()
		}
	}
	{
		if s := v.Get("subRequests"); !s.IsUndefined() && !s.IsNull() {
			out.SubRequests = s.Float()
		}
	}
	return out, nil
}

func (o DynamicDispatchLimits) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.CpuMs != 0 {
		obj.Set("cpuMs", o.CpuMs)
	}
	if o.SubRequests != 0 {
		obj.Set("subRequests", o.SubRequests)
	}
	return obj
}
