//go:build js && wasm

package email

import (
	"fmt"
	"io"
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
	"github.com/syumai/workers-go/internal/jsutil"
)

// EmailMessage is an outbound email message, passed to SendEmail.Send or
// ForwardableEmailMessage.Reply. Construct one with NewEmailMessage or
// NewEmailMessageString.
//
// It wraps an instance of the "cloudflare:email" module's EmailMessage
// class (`new EmailMessage(from, to, raw)`). That class isn't an
// interface/class declaration extract.ts can see in workers-types'
// top-level .d.ts (it only shows up as an ambient module export), so
// unlike every other type in this package it can't be generated by cfgen
// at all — see email.yaml's doc comment for why the from/to-only
// EmailMessage *interface* that IS in the IR is deliberately excluded from
// generation rather than reused here.
//
// Getting at the real class is the same problem cloudflare/sockets.Connect
// solves for connect(): the runtime shims under
// cmd/workers-assets-gen/assets/runtime/{cloudflare,browser}.mjs import it
// from "cloudflare:email" and add it to the object createRuntimeContext
// returns, and NewEmailMessage/NewEmailMessageString read it back out via
// jsrt.RuntimeContextValue.
type EmailMessage struct{ v js.Value }

// JSValue returns the underlying JS EmailMessage value.
func (m *EmailMessage) JSValue() js.Value { return m.v }

// NewEmailMessage constructs an outbound EmailMessage. from and to are
// envelope addresses; raw is streamed in full as the message's raw MIME
// content (headers plus body) via a JS ReadableStream.
func NewEmailMessage(from, to string, raw io.Reader) (*EmailMessage, error) {
	class, err := emailMessageClass()
	if err != nil {
		return nil, err
	}
	stream := jsrt.ReadableStreamFromReader(raw)
	v, err := newInstance(class, from, to, stream)
	if err != nil {
		return nil, err
	}
	return &EmailMessage{v: v}, nil
}

// NewEmailMessageString is NewEmailMessage, except raw is given directly as
// a string instead of being streamed from an io.Reader.
func NewEmailMessageString(from, to, raw string) (*EmailMessage, error) {
	class, err := emailMessageClass()
	if err != nil {
		return nil, err
	}
	v, err := newInstance(class, from, to, raw)
	if err != nil {
		return nil, err
	}
	return &EmailMessage{v: v}, nil
}

func emailMessageClass() (js.Value, error) {
	class, err := jsrt.RuntimeContextValue("EmailMessage")
	if err != nil {
		return js.Value{}, fmt.Errorf("email: EmailMessage class is not available in this runtime (browser.mjs doesn't provide one): %w", err)
	}
	return class, nil
}

// newInstance calls class as a JS constructor, recovering the Go panic
// syscall/js raises for a thrown JS exception into an error instead (the
// same treatment jsrt.Call gives synchronous method calls; there's no
// jsrt.New equivalent for constructors since EmailMessage is the only
// hand-written type in exp/cloudflare/... that needs one).
func newInstance(class js.Value, args ...any) (v js.Value, err error) {
	defer func() {
		if r := recover(); r != nil {
			v = js.Value{}
			err = fmt.Errorf("email: constructing EmailMessage: %v", r)
		}
	}()
	return class.New(args...), nil
}

// Handler handles one inbound email message delivered to a Worker's
// email(message, env, ctx) handler — i.e. a Cloudflare Email Routing rule
// with a "Send to a Worker" action pointing at this Worker. A returned
// error rejects the underlying Promise, which Email Routing treats as a
// temporary failure (the message is not accepted, and delivery may be
// retried by the sending server).
type Handler func(msg *ForwardableEmailMessage) error

//go:wasmimport workers ready
func ready()

// Handle registers h as the Worker's email handler and blocks until the
// Worker instance is torn down. It is meant for a Worker whose only job is
// handling inbound email (see _examples/email-forward); a Worker that also
// serves HTTP or other triggers should register other handlers (e.g.
// http.Handle, queues.ConsumeNonBlock) before calling a single blocking
// entry point such as workers.Serve instead of calling Handle.
func Handle(h Handler) {
	registerHandler(h)
	ready()
	select {}
}

// registerHandler wires h up to the "handleEmail" JS-callable binding
// worker.mjs's email(message, env, ctx) export calls, without touching
// ready/select{} — split out from Handle so tests can register a handler
// and drive it directly through jsutil.Binding without also pulling in
// (and blocking forever on) Handle's ready()/select{} tail.
func registerHandler(h Handler) {
	jsutil.RegisterAsyncHandler("handleEmail", 1, func(args []js.Value) (js.Value, error) {
		msg := ForwardableEmailMessageFromJS(args[0])
		return js.Undefined(), h(msg)
	})
}
