// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package email provides the Email Workers binding
// (https://developers.cloudflare.com/email-routing/email-workers/) and the
// ForwardableEmailMessage passed to a Worker's email(message, env, ctx)
// handler (registered from exp/cloudflare/email's sibling hand-written
// email.go via jsutil.RegisterAsyncHandler("handleEmail", ...) and
// cmd/workers-assets-gen/assets/common/worker.mjs's email export).
//
// EmailMessage (the outbound message type SendEmail.send and
// ForwardableEmailMessage.reply take) is deliberately left out of include:.
// In workers-types it is an ambient global interface exposing only
// readonly from/to getters — a stub for the real cloudflare:email module
// class (`new EmailMessage(from, to, raw)`), which isn't represented in the
// extracted IR at all (extract.ts only walks .d.ts top-level declarations,
// not runtime module exports). Generating a data type from that from/to-only
// stub would be actively wrong here: SendEmail.send and
// ForwardableEmailMessage.reply need to pass the real class instance
// (constructed from the runtime's own EmailMessage constructor, carrying
// the raw MIME content) through unchanged, not a plain {from, to} object
// encoded by a generated toJS(). So EmailMessage is left out of include:,
// which makes every ref to it in this package fall back to the standard
// "ref exists in the IR but not in this package's include list -> js.Value"
// path (see exp/cloudflare/README.md's type mapping table) instead of a
// lossy generated struct. The hand-written email.go's own EmailMessage type
// fills that gap: it holds the real JS instance (obtained via
// cfruntimecontext.GetRuntimeContextValue("EmailMessage"), set by the
// runtime shims in cmd/workers-assets-gen/assets/runtime/{cloudflare,browser}.mjs)
// and exposes JSValue() for SendEmail.Send/ForwardableEmailMessage.Reply to
// pass straight through as the js.Value parameter cfgen already generates
// for them.
//
// ForwardableEmailMessage still gets From()/To() getters despite
// EmailMessage being excluded from include:, because cfgen's extends
// flattening resolves ancestor types against the full IR, not just this
// package's include list.
//
// SendEmail.send and ForwardableEmailMessage.reply are each overloaded on a
// plain (from, to, raw) EmailMessage vs. a builder-object
// (EmailMessageBuilder / EmailReplyMessageBuilder) form; only the plain
// EmailMessage overload (index 0 for both) is generated, as Send/Reply. The
// builder overloads (index 1) are skipped.
package email

import (
	"io"
	"net/http"
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// SendEmail A binding that allows a Worker to send email messages.
type SendEmail struct{ v js.Value }

// SendEmailFromJS wraps a JS SendEmail value.
func SendEmailFromJS(v js.Value) *SendEmail { return &SendEmail{v: v} }

// JSValue returns the underlying JS value.
func (x *SendEmail) JSValue() js.Value { return x.v }

// NewSendEmail resolves the binding named bindingName from env.
func NewSendEmail(bindingName string) (*SendEmail, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &SendEmail{v: v}, nil
}

// Send
func (x *SendEmail) Send(message js.Value) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "send", message)
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// ForwardableEmailMessage An email message that is sent to a consumer Worker and can be rejected/forwarded.
type ForwardableEmailMessage struct{ v js.Value }

// ForwardableEmailMessageFromJS wraps a JS ForwardableEmailMessage value.
func ForwardableEmailMessageFromJS(v js.Value) *ForwardableEmailMessage {
	return &ForwardableEmailMessage{v: v}
}

// JSValue returns the underlying JS value.
func (x *ForwardableEmailMessage) JSValue() js.Value { return x.v }

// From Envelope From attribute of the email message.
func (x *ForwardableEmailMessage) From() string {
	var ret string
	ret = x.v.Get("from").String()
	return ret
}

// To Envelope To attribute of the email message.
func (x *ForwardableEmailMessage) To() string {
	var ret string
	ret = x.v.Get("to").String()
	return ret
}

// Raw Stream of the email message content.
func (x *ForwardableEmailMessage) Raw() io.ReadCloser {
	var ret io.ReadCloser
	ret = jsrt.ReadCloser(x.v.Get("raw"))
	return ret
}

// Headers An [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).
func (x *ForwardableEmailMessage) Headers() http.Header {
	var ret http.Header
	ret = jsrt.HeadersFromJS(x.v.Get("headers"))
	return ret
}

// RawSize Size of the email message content.
func (x *ForwardableEmailMessage) RawSize() int {
	var ret int
	ret = x.v.Get("rawSize").Int()
	return ret
}

// SetReject Reject this email message by returning a permanent SMTP error back to the connecting client including the given reason.
// @param reason The reject reason.
// @returns void
func (x *ForwardableEmailMessage) SetReject(reason string) error {
	_, err := jsrt.Call(x.v, "setReject", reason)
	return err
}

// Forward Forward this email message to a verified destination address of the account.
// @param rcptTo Verified destination address.
// @param headers A [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).
// @returns A promise that resolves when the email message is forwarded.
func (x *ForwardableEmailMessage) Forward(rcptTo string, headers http.Header) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "forward", rcptTo, jsrt.HeadersToJS(headers))
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Reply Reply to the sender of this email message with a new EmailMessage object.
// @param message The reply message.
// @returns A promise that resolves when the email message is replied.
func (x *ForwardableEmailMessage) Reply(message js.Value) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "reply", message)
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// EmailSendResult The returned data after sending an email
type EmailSendResult struct {
	// The Email Message ID
	MessageID string `js:"messageId"`
}

func emailSendResultFromJS(v js.Value) (EmailSendResult, error) {
	var out EmailSendResult
	{
		out.MessageID = v.Get("messageId").String()
	}
	return out, nil
}

func (o EmailSendResult) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.MessageID != "" {
		obj.Set("messageId", o.MessageID)
	}
	return obj
}
