// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package email provides the Email Workers binding
// (https://developers.cloudflare.com/email-routing/email-workers/) and the
// ForwardableEmailMessage passed to a Worker's email(message, env, ctx)
// handler (registered from exp/cloudflare/email's sibling hand-written
// email.go via jsutil.RegisterAsyncHandler("handleEmail", ...) and
// cmd/workers-assets-gen/assets/runtimes/cloudflare/worker.mjs's email export).
//
// EmailMessage (the outbound message type SendEmail.send and
// ForwardableEmailMessage.reply take) is deliberately left out of include:.
// In workers-types it is an ambient global interface exposing only
// readonly from/to getters — a stub for the real cloudflare:email module
// class (`new EmailMessage(from, to, raw)`), which isn't represented in the
// extracted IR at all (extract.ts only walks .d.ts top-level declarations,
// not runtime module exports). Generating a data type from that from/to-only
// stub would be actively wrong here: SendEmail.send and
// ForwardableEmailMessage.reply need to pass the real class instance
// (constructed from the runtime's own EmailMessage constructor, carrying
// the raw MIME content) through unchanged, not a plain {from, to} object
// encoded by a generated toJS(). So EmailMessage is left out of include:,
// which makes every ref to it in this package fall back to the standard
// "ref exists in the IR but not in this package's include list -> js.Value"
// path (see exp/cloudflare/README.md's type mapping table) instead of a
// lossy generated struct. The hand-written email.go's own EmailMessage type
// fills that gap: it holds the real JS instance (obtained via
// cfruntimecontext.GetRuntimeContextValue("EmailMessage"), set by the
// runtime shims in cmd/workers-assets-gen/assets/runtimes/cloudflare/runtime.mjs)
// and exposes JSValue() for SendEmail.Send/ForwardableEmailMessage.Reply to
// pass straight through as the js.Value parameter cfgen already generates
// for them.
//
// ForwardableEmailMessage still gets From()/To() getters despite
// EmailMessage being excluded from include:, because cfgen's extends
// flattening resolves ancestor types against the full IR, not just this
// package's include list.
//
// SendEmail.send and ForwardableEmailMessage.reply are each overloaded on a
// plain (from, to, raw) EmailMessage vs. a builder-object
// (EmailMessageBuilder / EmailReplyMessageBuilder) form. The plain
// EmailMessage overload (index 0 for both) is generated as Send/Reply.
// The builder overload (index 1) is generated as SendBuilder/ReplyBuilder
// (tmp/06-codegen-spec.md 6.2 item 2): EmailMessageBuilder is an alias for
// an intersection (EmailReplyMessageBuilder & EmailDestinations) that 5.1's
// intersection-flattening resolves into a plain data struct, the same way
// as GeoCombined in cfgen's own golden-test fixture; EmailReplyMessageBuilder
// is an ordinary interface data type. Both are included below so cfgen
// generates them (and their own dependencies, EmailAddress and
// EmailAttachment) as named Go structs instead of js.Value.
package email

import (
	"io"
	"net/http"
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// SendEmail A binding that allows a Worker to send email messages.
type SendEmail struct{ v js.Value }

// SendEmailFromJS wraps a JS SendEmail value.
func SendEmailFromJS(v js.Value) *SendEmail { return &SendEmail{v: v} }

// JSValue returns the underlying JS value.
func (x *SendEmail) JSValue() js.Value { return x.v }

// NewSendEmail resolves the binding named bindingName from env.
func NewSendEmail(bindingName string) (*SendEmail, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &SendEmail{v: v}, nil
}

// Send
func (x *SendEmail) Send(message js.Value) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "send", message)
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// SendBuilder
func (x *SendEmail) SendBuilder(builder EmailMessageBuilder) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "send", builder.toJS())
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// ForwardableEmailMessage An email message that is sent to a consumer Worker and can be rejected/forwarded.
type ForwardableEmailMessage struct{ v js.Value }

// ForwardableEmailMessageFromJS wraps a JS ForwardableEmailMessage value.
func ForwardableEmailMessageFromJS(v js.Value) *ForwardableEmailMessage {
	return &ForwardableEmailMessage{v: v}
}

// JSValue returns the underlying JS value.
func (x *ForwardableEmailMessage) JSValue() js.Value { return x.v }

// From Envelope From attribute of the email message.
func (x *ForwardableEmailMessage) From() string {
	var ret string
	ret = x.v.Get("from").String()
	return ret
}

// To Envelope To attribute of the email message.
func (x *ForwardableEmailMessage) To() string {
	var ret string
	ret = x.v.Get("to").String()
	return ret
}

// Raw Stream of the email message content.
func (x *ForwardableEmailMessage) Raw() io.ReadCloser {
	var ret io.ReadCloser
	ret = jsrt.ReadCloser(x.v.Get("raw"))
	return ret
}

// Headers An [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).
func (x *ForwardableEmailMessage) Headers() http.Header {
	var ret http.Header
	ret = jsrt.HeadersFromJS(x.v.Get("headers"))
	return ret
}

// RawSize Size of the email message content.
func (x *ForwardableEmailMessage) RawSize() int {
	var ret int
	ret = x.v.Get("rawSize").Int()
	return ret
}

// SetReject Reject this email message by returning a permanent SMTP error back to the connecting client including the given reason.
// @param reason The reject reason.
// @returns void
func (x *ForwardableEmailMessage) SetReject(reason string) error {
	_, err := jsrt.Call(x.v, "setReject", reason)
	return err
}

// Forward Forward this email message to a verified destination address of the account.
// @param rcptTo Verified destination address.
// @param headers A [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).
// @returns A promise that resolves when the email message is forwarded.
func (x *ForwardableEmailMessage) Forward(rcptTo string, headers http.Header) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "forward", rcptTo, jsrt.HeadersToJS(headers))
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Reply Reply to the sender of this email message with a new EmailMessage object.
// @param message The reply message.
// @returns A promise that resolves when the email message is replied.
func (x *ForwardableEmailMessage) Reply(message js.Value) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "reply", message)
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// ReplyBuilder Reply to the sender of this email message with a message built from the given
// fields. Threading headers (In-Reply-To/References) are set automatically.
// @param builder The reply message contents.
// @returns A promise that resolves when the email message is replied.
func (x *ForwardableEmailMessage) ReplyBuilder(builder EmailReplyMessageBuilder) (EmailSendResult, error) {
	p, err := jsrt.Call(x.v, "reply", builder.toJS())
	if err != nil {
		return EmailSendResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return EmailSendResult{}, err
	}
	var ret EmailSendResult
	if tmp, err := emailSendResultFromJS(r); err != nil {
		return EmailSendResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// EmailSendResult The returned data after sending an email
type EmailSendResult struct {
	// The Email Message ID
	MessageID string `js:"messageId"`
}

func emailSendResultFromJS(v js.Value) (EmailSendResult, error) {
	var out EmailSendResult
	{
		out.MessageID = v.Get("messageId").String()
	}
	return out, nil
}

func (o EmailSendResult) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.MessageID != "" {
		obj.Set("messageId", o.MessageID)
	}
	return obj
}

// EmailMessageBuilder Fields for composing an email without constructing raw MIME, for
// `SendEmail.send()`. Requires at least one of `to`, `cc`, or `bcc`.
type EmailMessageBuilder struct {
	From        js.Value          `js:"from"`
	Subject     string            `js:"subject"`
	ReplyTo     js.Value          `js:"replyTo"`
	Headers     map[string]string `js:"headers"`
	Text        string            `js:"text"`
	HTML        string            `js:"html"`
	Attachments []js.Value        `js:"attachments"`
	To          js.Value          `js:"to"`
	Cc          js.Value          `js:"cc"`
	Bcc         js.Value          `js:"bcc"`
}

func emailMessageBuilderFromJS(v js.Value) (EmailMessageBuilder, error) {
	var out EmailMessageBuilder
	{
		out.From = v.Get("from")
	}
	{
		out.Subject = v.Get("subject").String()
	}
	{
		if s := v.Get("replyTo"); !s.IsUndefined() && !s.IsNull() {
			out.ReplyTo = s
		}
	}
	{
		if s := v.Get("headers"); !s.IsUndefined() && !s.IsNull() {
			out.Headers = make(map[string]string)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				var vv string
				vv = s.Get(k).String()
				out.Headers[k] = vv
			}
		}
	}
	{
		if s := v.Get("text"); !s.IsUndefined() && !s.IsNull() {
			out.Text = s.String()
		}
	}
	{
		if s := v.Get("html"); !s.IsUndefined() && !s.IsNull() {
			out.HTML = s.String()
		}
	}
	{
		if s := v.Get("attachments"); !s.IsUndefined() && !s.IsNull() {
			out.Attachments = make([]js.Value, s.Length())
			for i := range out.Attachments {
				out.Attachments[i] = s.Index(i)
			}
		}
	}
	{
		if s := v.Get("to"); !s.IsUndefined() && !s.IsNull() {
			out.To = s
		}
	}
	{
		if s := v.Get("cc"); !s.IsUndefined() && !s.IsNull() {
			out.Cc = s
		}
	}
	{
		if s := v.Get("bcc"); !s.IsUndefined() && !s.IsNull() {
			out.Bcc = s
		}
	}
	return out, nil
}

func (o EmailMessageBuilder) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.From) {
		obj.Set("from", o.From)
	}
	if o.Subject != "" {
		obj.Set("subject", o.Subject)
	}
	if !jsrt.IsNil(o.ReplyTo) {
		obj.Set("replyTo", o.ReplyTo)
	}
	if len(o.Headers) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.Headers {
			m.Set(k, v)
		}
		obj.Set("headers", m)
	}
	if o.Text != "" {
		obj.Set("text", o.Text)
	}
	if o.HTML != "" {
		obj.Set("html", o.HTML)
	}
	if len(o.Attachments) > 0 {
		arr := js.Global().Get("Array").New(len(o.Attachments))
		for i, e := range o.Attachments {
			arr.SetIndex(i, e)
		}
		obj.Set("attachments", arr)
	}
	if !jsrt.IsNil(o.To) {
		obj.Set("to", o.To)
	}
	if !jsrt.IsNil(o.Cc) {
		obj.Set("cc", o.Cc)
	}
	if !jsrt.IsNil(o.Bcc) {
		obj.Set("bcc", o.Bcc)
	}
	return obj
}

// EmailReplyMessageBuilder Fields shared by all composed emails (no recipients). Used directly by
// `ForwardableEmailMessage.reply()`, which always replies to the original
// sender, and extended by `EmailMessageBuilder` for `SendEmail.send()`.
type EmailReplyMessageBuilder struct {
	From        js.Value          `js:"from"`
	Subject     string            `js:"subject"`
	ReplyTo     js.Value          `js:"replyTo"`
	Headers     map[string]string `js:"headers"`
	Text        string            `js:"text"`
	HTML        string            `js:"html"`
	Attachments []js.Value        `js:"attachments"`
}

func emailReplyMessageBuilderFromJS(v js.Value) (EmailReplyMessageBuilder, error) {
	var out EmailReplyMessageBuilder
	{
		out.From = v.Get("from")
	}
	{
		out.Subject = v.Get("subject").String()
	}
	{
		if s := v.Get("replyTo"); !s.IsUndefined() && !s.IsNull() {
			out.ReplyTo = s
		}
	}
	{
		if s := v.Get("headers"); !s.IsUndefined() && !s.IsNull() {
			out.Headers = make(map[string]string)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				var vv string
				vv = s.Get(k).String()
				out.Headers[k] = vv
			}
		}
	}
	{
		if s := v.Get("text"); !s.IsUndefined() && !s.IsNull() {
			out.Text = s.String()
		}
	}
	{
		if s := v.Get("html"); !s.IsUndefined() && !s.IsNull() {
			out.HTML = s.String()
		}
	}
	{
		if s := v.Get("attachments"); !s.IsUndefined() && !s.IsNull() {
			out.Attachments = make([]js.Value, s.Length())
			for i := range out.Attachments {
				out.Attachments[i] = s.Index(i)
			}
		}
	}
	return out, nil
}

func (o EmailReplyMessageBuilder) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.From) {
		obj.Set("from", o.From)
	}
	if o.Subject != "" {
		obj.Set("subject", o.Subject)
	}
	if !jsrt.IsNil(o.ReplyTo) {
		obj.Set("replyTo", o.ReplyTo)
	}
	if len(o.Headers) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.Headers {
			m.Set(k, v)
		}
		obj.Set("headers", m)
	}
	if o.Text != "" {
		obj.Set("text", o.Text)
	}
	if o.HTML != "" {
		obj.Set("html", o.HTML)
	}
	if len(o.Attachments) > 0 {
		arr := js.Global().Get("Array").New(len(o.Attachments))
		for i, e := range o.Attachments {
			arr.SetIndex(i, e)
		}
		obj.Set("attachments", arr)
	}
	return obj
}

// EmailAddress An Email Address
type EmailAddress struct {
	Name  string `js:"name"`
	Email string `js:"email"`
}

func emailAddressFromJS(v js.Value) (EmailAddress, error) {
	var out EmailAddress
	{
		out.Name = v.Get("name").String()
	}
	{
		out.Email = v.Get("email").String()
	}
	return out, nil
}

func (o EmailAddress) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Email != "" {
		obj.Set("email", o.Email)
	}
	return obj
}

// EmailAttachment A file attachment for an email message
type EmailAttachment = js.Value
