// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package durableobjects provides the Level 1 (generated) Durable Objects
// bindings: DurableObjectState, DurableObjectStorage, DurableObjectId,
// DurableObjectNamespace, SqlStorage, and SqlStorageCursor. See
// tmp/06-codegen-spec.md section 4.1.
//
// Hosting a Go type as a Durable Object class (running DurableObjectState's
// fetch/alarm/webSocket* triggers against a registered Go implementation) is
// hand-written, not generated — see host.go.
package durableobjects

import (
	"syscall/js"
	"time"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// DurableObjectState
type DurableObjectState struct{ v js.Value }

// DurableObjectStateFromJS wraps a JS DurableObjectState value.
func DurableObjectStateFromJS(v js.Value) *DurableObjectState { return &DurableObjectState{v: v} }

// JSValue returns the underlying JS value.
func (x *DurableObjectState) JSValue() js.Value { return x.v }

// WaitUntil
func (x *DurableObjectState) WaitUntil(promise js.Value) error {
	_, err := jsrt.Call(x.v, "waitUntil", promise)
	return err
}

// ID
func (x *DurableObjectState) ID() *DurableObjectID {
	var ret *DurableObjectID
	ret = DurableObjectIDFromJS(x.v.Get("id"))
	return ret
}

// Storage
func (x *DurableObjectState) Storage() *DurableObjectStorage {
	var ret *DurableObjectStorage
	ret = DurableObjectStorageFromJS(x.v.Get("storage"))
	return ret
}

// AcceptWebSocket
func (x *DurableObjectState) AcceptWebSocket(ws js.Value, tags []string) error {
	var arg1 js.Value
	{
		arr := js.Global().Get("Array").New(len(tags))
		for i, e := range tags {
			arr.SetIndex(i, e)
		}
		arg1 = arr
	}
	_, err := jsrt.Call(x.v, "acceptWebSocket", ws, arg1)
	return err
}

// GetWebSockets
func (x *DurableObjectState) GetWebSockets(tag string) ([]js.Value, error) {
	r, err := jsrt.Call(x.v, "getWebSockets", tag)
	if err != nil {
		return nil, err
	}
	var ret []js.Value
	ret = make([]js.Value, r.Length())
	for i := range ret {
		ret[i] = r.Index(i)
	}
	return ret, nil
}

// GetTags
func (x *DurableObjectState) GetTags(ws js.Value) ([]string, error) {
	r, err := jsrt.Call(x.v, "getTags", ws)
	if err != nil {
		return nil, err
	}
	var ret []string
	ret = make([]string, r.Length())
	for i := range ret {
		ret[i] = r.Index(i).String()
	}
	return ret, nil
}

// Abort
func (x *DurableObjectState) Abort(reason string, options DurableObjectAbortOptions) error {
	_, err := jsrt.Call(x.v, "abort", reason, options.toJS())
	return err
}

// DurableObjectStorage
type DurableObjectStorage struct{ v js.Value }

// DurableObjectStorageFromJS wraps a JS DurableObjectStorage value.
func DurableObjectStorageFromJS(v js.Value) *DurableObjectStorage { return &DurableObjectStorage{v: v} }

// JSValue returns the underlying JS value.
func (x *DurableObjectStorage) JSValue() js.Value { return x.v }

// Get
func (x *DurableObjectStorage) Get(key string, options DurableObjectGetOptions) (js.Value, error) {
	p, err := jsrt.Call(x.v, "get", key, options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// GetMultiple
func (x *DurableObjectStorage) GetMultiple(keys []string, options DurableObjectGetOptions) (map[string]js.Value, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(keys))
		for i, e := range keys {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "get", arg0, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret map[string]js.Value
	ret = make(map[string]js.Value)
	mapKeys := js.Global().Get("Array").Call("from", r.Call("keys"))
	for mapIdx := 0; mapIdx < mapKeys.Length(); mapIdx++ {
		mapKey := mapKeys.Index(mapIdx).String()
		var mapVal js.Value
		mapVal = r.Call("get", mapKey)
		ret[mapKey] = mapVal
	}
	return ret, nil
}

// List
func (x *DurableObjectStorage) List(options DurableObjectListOptions) (map[string]js.Value, error) {
	p, err := jsrt.Call(x.v, "list", options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret map[string]js.Value
	ret = make(map[string]js.Value)
	mapKeys := js.Global().Get("Array").Call("from", r.Call("keys"))
	for mapIdx := 0; mapIdx < mapKeys.Length(); mapIdx++ {
		mapKey := mapKeys.Index(mapIdx).String()
		var mapVal js.Value
		mapVal = r.Call("get", mapKey)
		ret[mapKey] = mapVal
	}
	return ret, nil
}

// Put
func (x *DurableObjectStorage) Put(key string, value js.Value, options DurableObjectPutOptions) error {
	p, err := jsrt.Call(x.v, "put", key, value, options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// PutMultiple
func (x *DurableObjectStorage) PutMultiple(entries map[string]js.Value, options DurableObjectPutOptions) error {
	var arg0 js.Value
	{
		m := jsrt.NewObject()
		for k, v := range entries {
			m.Set(k, v)
		}
		arg0 = m
	}
	p, err := jsrt.Call(x.v, "put", arg0, options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Delete
func (x *DurableObjectStorage) Delete(key string, options DurableObjectPutOptions) (bool, error) {
	p, err := jsrt.Call(x.v, "delete", key, options.toJS())
	if err != nil {
		return false, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return false, err
	}
	var ret bool
	ret = r.Bool()
	return ret, nil
}

// DeleteMultiple
func (x *DurableObjectStorage) DeleteMultiple(keys []string, options DurableObjectPutOptions) (float64, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(keys))
		for i, e := range keys {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "delete", arg0, options.toJS())
	if err != nil {
		return 0, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return 0, err
	}
	var ret float64
	ret = r.Float()
	return ret, nil
}

// DeleteAll
func (x *DurableObjectStorage) DeleteAll(options DurableObjectPutOptions) error {
	p, err := jsrt.Call(x.v, "deleteAll", options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// GetAlarm
func (x *DurableObjectStorage) GetAlarm(options DurableObjectGetAlarmOptions) (*float64, error) {
	p, err := jsrt.Call(x.v, "getAlarm", options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *float64
	if !jsrt.IsNil(r) {
		var val float64
		val = r.Float()
		ret = &val
	}
	return ret, nil
}

// SetAlarm
func (x *DurableObjectStorage) SetAlarm(scheduledTime time.Time, options DurableObjectSetAlarmOptions) error {
	p, err := jsrt.Call(x.v, "setAlarm", jsrt.TimeToDate(scheduledTime), options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// DeleteAlarm
func (x *DurableObjectStorage) DeleteAlarm(options DurableObjectSetAlarmOptions) error {
	p, err := jsrt.Call(x.v, "deleteAlarm", options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Sync
func (x *DurableObjectStorage) Sync() error {
	p, err := jsrt.Call(x.v, "sync")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// SQL
func (x *DurableObjectStorage) SQL() *SQLStorage {
	var ret *SQLStorage
	ret = SQLStorageFromJS(x.v.Get("sql"))
	return ret
}

// DurableObjectGetOptions
type DurableObjectGetOptions struct {
	AllowConcurrency bool `js:"allowConcurrency"`
	NoCache          bool `js:"noCache"`
}

func durableObjectGetOptionsFromJS(v js.Value) (DurableObjectGetOptions, error) {
	var out DurableObjectGetOptions
	{
		if s := v.Get("allowConcurrency"); !s.IsUndefined() && !s.IsNull() {
			out.AllowConcurrency = s.Bool()
		}
	}
	{
		if s := v.Get("noCache"); !s.IsUndefined() && !s.IsNull() {
			out.NoCache = s.Bool()
		}
	}
	return out, nil
}

func (o DurableObjectGetOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.AllowConcurrency {
		obj.Set("allowConcurrency", o.AllowConcurrency)
	}
	if o.NoCache {
		obj.Set("noCache", o.NoCache)
	}
	return obj
}

// DurableObjectPutOptions
type DurableObjectPutOptions struct {
	AllowConcurrency bool `js:"allowConcurrency"`
	AllowUnconfirmed bool `js:"allowUnconfirmed"`
	NoCache          bool `js:"noCache"`
}

func durableObjectPutOptionsFromJS(v js.Value) (DurableObjectPutOptions, error) {
	var out DurableObjectPutOptions
	{
		if s := v.Get("allowConcurrency"); !s.IsUndefined() && !s.IsNull() {
			out.AllowConcurrency = s.Bool()
		}
	}
	{
		if s := v.Get("allowUnconfirmed"); !s.IsUndefined() && !s.IsNull() {
			out.AllowUnconfirmed = s.Bool()
		}
	}
	{
		if s := v.Get("noCache"); !s.IsUndefined() && !s.IsNull() {
			out.NoCache = s.Bool()
		}
	}
	return out, nil
}

func (o DurableObjectPutOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.AllowConcurrency {
		obj.Set("allowConcurrency", o.AllowConcurrency)
	}
	if o.AllowUnconfirmed {
		obj.Set("allowUnconfirmed", o.AllowUnconfirmed)
	}
	if o.NoCache {
		obj.Set("noCache", o.NoCache)
	}
	return obj
}

// DurableObjectListOptions
type DurableObjectListOptions struct {
	Start            string  `js:"start"`
	StartAfter       string  `js:"startAfter"`
	End              string  `js:"end"`
	Prefix           string  `js:"prefix"`
	Reverse          bool    `js:"reverse"`
	Limit            float64 `js:"limit"`
	AllowConcurrency bool    `js:"allowConcurrency"`
	NoCache          bool    `js:"noCache"`
}

func durableObjectListOptionsFromJS(v js.Value) (DurableObjectListOptions, error) {
	var out DurableObjectListOptions
	{
		if s := v.Get("start"); !s.IsUndefined() && !s.IsNull() {
			out.Start = s.String()
		}
	}
	{
		if s := v.Get("startAfter"); !s.IsUndefined() && !s.IsNull() {
			out.StartAfter = s.String()
		}
	}
	{
		if s := v.Get("end"); !s.IsUndefined() && !s.IsNull() {
			out.End = s.String()
		}
	}
	{
		if s := v.Get("prefix"); !s.IsUndefined() && !s.IsNull() {
			out.Prefix = s.String()
		}
	}
	{
		if s := v.Get("reverse"); !s.IsUndefined() && !s.IsNull() {
			out.Reverse = s.Bool()
		}
	}
	{
		if s := v.Get("limit"); !s.IsUndefined() && !s.IsNull() {
			out.Limit = s.Float()
		}
	}
	{
		if s := v.Get("allowConcurrency"); !s.IsUndefined() && !s.IsNull() {
			out.AllowConcurrency = s.Bool()
		}
	}
	{
		if s := v.Get("noCache"); !s.IsUndefined() && !s.IsNull() {
			out.NoCache = s.Bool()
		}
	}
	return out, nil
}

func (o DurableObjectListOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Start != "" {
		obj.Set("start", o.Start)
	}
	if o.StartAfter != "" {
		obj.Set("startAfter", o.StartAfter)
	}
	if o.End != "" {
		obj.Set("end", o.End)
	}
	if o.Prefix != "" {
		obj.Set("prefix", o.Prefix)
	}
	if o.Reverse {
		obj.Set("reverse", o.Reverse)
	}
	if o.Limit != 0 {
		obj.Set("limit", o.Limit)
	}
	if o.AllowConcurrency {
		obj.Set("allowConcurrency", o.AllowConcurrency)
	}
	if o.NoCache {
		obj.Set("noCache", o.NoCache)
	}
	return obj
}

// DurableObjectSetAlarmOptions
type DurableObjectSetAlarmOptions struct {
	AllowConcurrency bool `js:"allowConcurrency"`
	AllowUnconfirmed bool `js:"allowUnconfirmed"`
}

func durableObjectSetAlarmOptionsFromJS(v js.Value) (DurableObjectSetAlarmOptions, error) {
	var out DurableObjectSetAlarmOptions
	{
		if s := v.Get("allowConcurrency"); !s.IsUndefined() && !s.IsNull() {
			out.AllowConcurrency = s.Bool()
		}
	}
	{
		if s := v.Get("allowUnconfirmed"); !s.IsUndefined() && !s.IsNull() {
			out.AllowUnconfirmed = s.Bool()
		}
	}
	return out, nil
}

func (o DurableObjectSetAlarmOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.AllowConcurrency {
		obj.Set("allowConcurrency", o.AllowConcurrency)
	}
	if o.AllowUnconfirmed {
		obj.Set("allowUnconfirmed", o.AllowUnconfirmed)
	}
	return obj
}

// DurableObjectGetAlarmOptions
type DurableObjectGetAlarmOptions struct {
	AllowConcurrency bool `js:"allowConcurrency"`
}

func durableObjectGetAlarmOptionsFromJS(v js.Value) (DurableObjectGetAlarmOptions, error) {
	var out DurableObjectGetAlarmOptions
	{
		if s := v.Get("allowConcurrency"); !s.IsUndefined() && !s.IsNull() {
			out.AllowConcurrency = s.Bool()
		}
	}
	return out, nil
}

func (o DurableObjectGetAlarmOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.AllowConcurrency {
		obj.Set("allowConcurrency", o.AllowConcurrency)
	}
	return obj
}

// DurableObjectAbortOptions
type DurableObjectAbortOptions struct {
	RetryAlarm bool `js:"retryAlarm"`
}

func durableObjectAbortOptionsFromJS(v js.Value) (DurableObjectAbortOptions, error) {
	var out DurableObjectAbortOptions
	{
		if s := v.Get("retryAlarm"); !s.IsUndefined() && !s.IsNull() {
			out.RetryAlarm = s.Bool()
		}
	}
	return out, nil
}

func (o DurableObjectAbortOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.RetryAlarm {
		obj.Set("retryAlarm", o.RetryAlarm)
	}
	return obj
}

// DurableObjectID
type DurableObjectID struct{ v js.Value }

// DurableObjectIDFromJS wraps a JS DurableObjectID value.
func DurableObjectIDFromJS(v js.Value) *DurableObjectID { return &DurableObjectID{v: v} }

// JSValue returns the underlying JS value.
func (x *DurableObjectID) JSValue() js.Value { return x.v }

// String
func (x *DurableObjectID) String() (string, error) {
	r, err := jsrt.Call(x.v, "toString")
	if err != nil {
		return "", err
	}
	var ret string
	ret = r.String()
	return ret, nil
}

// Equals
func (x *DurableObjectID) Equals(other *DurableObjectID) (bool, error) {
	r, err := jsrt.Call(x.v, "equals", other.JSValue())
	if err != nil {
		return false, err
	}
	var ret bool
	ret = r.Bool()
	return ret, nil
}

// Name
func (x *DurableObjectID) Name() string {
	var ret string
	if s := x.v.Get("name"); !s.IsUndefined() && !s.IsNull() {
		ret = s.String()
	}
	return ret
}

// Jurisdiction
func (x *DurableObjectID) Jurisdiction() string {
	var ret string
	if s := x.v.Get("jurisdiction"); !s.IsUndefined() && !s.IsNull() {
		ret = s.String()
	}
	return ret
}

// DurableObjectNamespace
type DurableObjectNamespace struct{ v js.Value }

// DurableObjectNamespaceFromJS wraps a JS DurableObjectNamespace value.
func DurableObjectNamespaceFromJS(v js.Value) *DurableObjectNamespace {
	return &DurableObjectNamespace{v: v}
}

// JSValue returns the underlying JS value.
func (x *DurableObjectNamespace) JSValue() js.Value { return x.v }

// NewDurableObjectNamespace resolves the binding named bindingName from env.
func NewDurableObjectNamespace(bindingName string) (*DurableObjectNamespace, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &DurableObjectNamespace{v: v}, nil
}

// NewUniqueID
func (x *DurableObjectNamespace) NewUniqueID(options DurableObjectNamespaceNewUniqueIDOptions) (*DurableObjectID, error) {
	r, err := jsrt.Call(x.v, "newUniqueId", options.toJS())
	if err != nil {
		return nil, err
	}
	var ret *DurableObjectID
	ret = DurableObjectIDFromJS(r)
	return ret, nil
}

// IDFromName
func (x *DurableObjectNamespace) IDFromName(name string) (*DurableObjectID, error) {
	r, err := jsrt.Call(x.v, "idFromName", name)
	if err != nil {
		return nil, err
	}
	var ret *DurableObjectID
	ret = DurableObjectIDFromJS(r)
	return ret, nil
}

// IDFromString
func (x *DurableObjectNamespace) IDFromString(id string) (*DurableObjectID, error) {
	r, err := jsrt.Call(x.v, "idFromString", id)
	if err != nil {
		return nil, err
	}
	var ret *DurableObjectID
	ret = DurableObjectIDFromJS(r)
	return ret, nil
}

// Get
func (x *DurableObjectNamespace) Get(id *DurableObjectID, options DurableObjectNamespaceGetDurableObjectOptions) (js.Value, error) {
	r, err := jsrt.Call(x.v, "get", id.JSValue(), options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// GetByName
func (x *DurableObjectNamespace) GetByName(name string, options DurableObjectNamespaceGetDurableObjectOptions) (js.Value, error) {
	r, err := jsrt.Call(x.v, "getByName", name, options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// Jurisdiction
func (x *DurableObjectNamespace) Jurisdiction(jurisdiction DurableObjectJurisdiction) (*DurableObjectNamespace, error) {
	r, err := jsrt.Call(x.v, "jurisdiction", string(jurisdiction))
	if err != nil {
		return nil, err
	}
	var ret *DurableObjectNamespace
	ret = DurableObjectNamespaceFromJS(r)
	return ret, nil
}

// DurableObjectNamespaceNewUniqueIDOptions
type DurableObjectNamespaceNewUniqueIDOptions struct {
	Jurisdiction DurableObjectJurisdiction `js:"jurisdiction"`
}

func durableObjectNamespaceNewUniqueIDOptionsFromJS(v js.Value) (DurableObjectNamespaceNewUniqueIDOptions, error) {
	var out DurableObjectNamespaceNewUniqueIDOptions
	{
		if s := v.Get("jurisdiction"); !s.IsUndefined() && !s.IsNull() {
			out.Jurisdiction = DurableObjectJurisdiction(s.String())
		}
	}
	return out, nil
}

func (o DurableObjectNamespaceNewUniqueIDOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Jurisdiction != "" {
		obj.Set("jurisdiction", string(o.Jurisdiction))
	}
	return obj
}

// DurableObjectNamespaceGetDurableObjectOptions
type DurableObjectNamespaceGetDurableObjectOptions struct {
	LocationHint DurableObjectLocationHint `js:"locationHint"`
	RoutingMode  string                    `js:"routingMode"`
}

func durableObjectNamespaceGetDurableObjectOptionsFromJS(v js.Value) (DurableObjectNamespaceGetDurableObjectOptions, error) {
	var out DurableObjectNamespaceGetDurableObjectOptions
	{
		if s := v.Get("locationHint"); !s.IsUndefined() && !s.IsNull() {
			out.LocationHint = DurableObjectLocationHint(s.String())
		}
	}
	{
		if s := v.Get("routingMode"); !s.IsUndefined() && !s.IsNull() {
			out.RoutingMode = s.String()
		}
	}
	return out, nil
}

func (o DurableObjectNamespaceGetDurableObjectOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.LocationHint != "" {
		obj.Set("locationHint", string(o.LocationHint))
	}
	if o.RoutingMode != "" {
		obj.Set("routingMode", o.RoutingMode)
	}
	return obj
}

// DurableObjectJurisdiction
type DurableObjectJurisdiction string

const (
	DurableObjectJurisdictionEu          DurableObjectJurisdiction = "eu"
	DurableObjectJurisdictionFedramp     DurableObjectJurisdiction = "fedramp"
	DurableObjectJurisdictionFedrampHigh DurableObjectJurisdiction = "fedramp-high"
	DurableObjectJurisdictionUs          DurableObjectJurisdiction = "us"
)

// DurableObjectLocationHint
type DurableObjectLocationHint string

const (
	DurableObjectLocationHintWnam   DurableObjectLocationHint = "wnam"
	DurableObjectLocationHintEnam   DurableObjectLocationHint = "enam"
	DurableObjectLocationHintSam    DurableObjectLocationHint = "sam"
	DurableObjectLocationHintWeur   DurableObjectLocationHint = "weur"
	DurableObjectLocationHintEeur   DurableObjectLocationHint = "eeur"
	DurableObjectLocationHintApac   DurableObjectLocationHint = "apac"
	DurableObjectLocationHintApacNe DurableObjectLocationHint = "apac-ne"
	DurableObjectLocationHintApacSe DurableObjectLocationHint = "apac-se"
	DurableObjectLocationHintOc     DurableObjectLocationHint = "oc"
	DurableObjectLocationHintAfr    DurableObjectLocationHint = "afr"
	DurableObjectLocationHintMe     DurableObjectLocationHint = "me"
)

// DurableObjectRoutingMode
type DurableObjectRoutingMode = string

// SQLStorage
type SQLStorage struct{ v js.Value }

// SQLStorageFromJS wraps a JS SQLStorage value.
func SQLStorageFromJS(v js.Value) *SQLStorage { return &SQLStorage{v: v} }

// JSValue returns the underlying JS value.
func (x *SQLStorage) JSValue() js.Value { return x.v }

// Exec
func (x *SQLStorage) Exec(query string, bindings ...any) (*SQLStorageCursor, error) {
	r, err := jsrt.Call(x.v, "exec", append([]any{query}, bindings...)...)
	if err != nil {
		return nil, err
	}
	var ret *SQLStorageCursor
	ret = SQLStorageCursorFromJS(r)
	return ret, nil
}

// DatabaseSize
func (x *SQLStorage) DatabaseSize() float64 {
	var ret float64
	ret = x.v.Get("databaseSize").Float()
	return ret
}

// SQLStorageCursor
type SQLStorageCursor struct{ v js.Value }

// SQLStorageCursorFromJS wraps a JS SQLStorageCursor value.
func SQLStorageCursorFromJS(v js.Value) *SQLStorageCursor { return &SQLStorageCursor{v: v} }

// JSValue returns the underlying JS value.
func (x *SQLStorageCursor) JSValue() js.Value { return x.v }

// ToArray
func (x *SQLStorageCursor) ToArray() ([]js.Value, error) {
	r, err := jsrt.Call(x.v, "toArray")
	if err != nil {
		return nil, err
	}
	var ret []js.Value
	ret = make([]js.Value, r.Length())
	for i := range ret {
		ret[i] = r.Index(i)
	}
	return ret, nil
}

// One
func (x *SQLStorageCursor) One() (js.Value, error) {
	r, err := jsrt.Call(x.v, "one")
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// ColumnNames
func (x *SQLStorageCursor) ColumnNames() []string {
	var ret []string
	ret = make([]string, x.v.Get("columnNames").Length())
	for i := range ret {
		ret[i] = x.v.Get("columnNames").Index(i).String()
	}
	return ret
}

// RowsRead
func (x *SQLStorageCursor) RowsRead() float64 {
	var ret float64
	ret = x.v.Get("rowsRead").Float()
	return ret
}

// RowsWritten
func (x *SQLStorageCursor) RowsWritten() float64 {
	var ret float64
	ret = x.v.Get("rowsWritten").Float()
	return ret
}

// AlarmInvocationInfo
type AlarmInvocationInfo struct {
	IsRetry       bool    `js:"isRetry"`
	RetryCount    float64 `js:"retryCount"`
	ScheduledTime float64 `js:"scheduledTime"`
}

func alarmInvocationInfoFromJS(v js.Value) (AlarmInvocationInfo, error) {
	var out AlarmInvocationInfo
	{
		out.IsRetry = v.Get("isRetry").Bool()
	}
	{
		out.RetryCount = v.Get("retryCount").Float()
	}
	{
		out.ScheduledTime = v.Get("scheduledTime").Float()
	}
	return out, nil
}

func (o AlarmInvocationInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.IsRetry {
		obj.Set("isRetry", o.IsRetry)
	}
	if o.RetryCount != 0 {
		obj.Set("retryCount", o.RetryCount)
	}
	if o.ScheduledTime != 0 {
		obj.Set("scheduledTime", o.ScheduledTime)
	}
	return obj
}
